### ISSUE TITLE
Do we want to use CSS modules?

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#1]
See: https://facebook.github.io/create-react-app/docs/adding-a-css-modules-stylesheet

The main benefit is:

> CSS Modules let you use the same CSS class name in different files without worrying about naming clashes.

See also: https://css-tricks.com/css-modules-part-1-need/

> With CSS Modules, it’s a guarantee that all the styles for a single component:
>  - Live in one place
>  - Only apply to that component and nothing else

**Comment by kumar303** [comment]
I don't know much about them but it seems like a sane convention. I would still like to use SCSS, though.

**Comment by kumar303** [comment]
It looks like their setup of css modules supports scss, too https://facebook.github.io/create-react-app/docs/adding-a-sass-stylesheet

**Comment by willdurand** [comment]
I went ahead and submitted a PR with an example: https://github.com/mozilla/addons-code-manager/pull/28
