### ISSUE TITLE
Add react-diff-view library

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#10]
[This library](https://github.com/otakustay/react-diff-view) will be used to write one of the main screens of this app.

⚠️ v2 of this library is about to be released, and it would be a good idea to use it directly. More information at: https://github.com/otakustay/react-diff-view/issues/24#issuecomment-453703703

**Comment by bobsilverberg** [comment]
Assigning this to myself as I think it makes sense to dig into how we would use this as part of making a decision about which UI lib to use for #7. I think we can use the alpha of v2 for development for now.

**Comment by willdurand** [comment]
> Assigning this to myself as I think it makes sense to dig into how we would use this as part of making a decision about which UI lib to use for #7. I think we can use the alpha of v2 for development for now.

:+1:
