### ISSUE TITLE
Quick way to jump to the first file with changes

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-code-manager#1003]
When looking at the compare view, it is great to see the manifest first to see what the add-on is about. My next step after is going to the first file with changes. Right now (and also in the old file viewer), I had to scroll all the way up, open all the folders on the way down to the first file with changes.

If there was a keyboard shortcut, or a button, or anything else that would allow me to jump to that first file, it would be great!

**Comment by kumar303** [comment]
Thanks for filing an issue. When you say the first file with changes, are you thinking of the first one in the list, i.e. the first one recursive-alphabetically? For example, would `META-INF/code.manifest` be the first in this case? https://code.addons-dev.allizom.org/en-US/compare/616959/versions/1688391...1688394/?path=META-INF%2Fcose.manifest

**Comment by kewisch** [comment]
Sorry I missed this, my inbox has too many github notifications. I mean the first one visually in the list, so if you expand all directories then look from top to bottom, the first file that has changes from the top.

**Comment by kumar303** [comment]
Is this because `n` (which loads the next change) will begin in the manifest file and that's not what you want? I'm just wondering if we can make the `n` feature better in some way.
