### ISSUE TITLE
Convert stories to use style modules

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1033]
Our components rendered in stories sometimes need custom styles, which all get stuffed into [`setup/styles.scss`](https://github.com/mozilla/addons-code-manager/blob/98d5770786e4e1687225928329ea56132556ec0e/stories/setup/styles.scss).

Instead, let's convert each story to use style modules so that the styles are easier to maintain. 

This would involve moving each story module to a directory. As an example, `stories/AccordionMenu.stories.tsx` would move to `stories/AccordionMenu/stories.tsx` or something like that. Beware that [the discovery code](https://github.com/mozilla/addons-code-manager/blob/98d5770786e4e1687225928329ea56132556ec0e/stories/setup/config.tsx#L24-L25) will need some adjustment.

**Comment by ruchikabgosain** [comment]
hey @kumar303 is this issue available? I would love to take this up!

**Comment by kumar303** [comment]
It is! Thanks. After working on https://github.com/mozilla/addons-code-manager/issues/1032 , give me a shout and I can help you with this one.

**Comment by ruchikabgosain** [comment]
hey @kumar303 , I suppose all these story modules would move into their own directories? also, `const req = require.context('../', true, /.stories.tsx$/); ` changes to `const req = require.context('../', true, / '../',stories.tsx$/);' ? 
let me know if this works? 

![image](https://user-images.githubusercontent.com/30324532/66115352-43900580-e5ee-11e9-8085-7e3d41630e62.png)

**Comment by kumar303** [comment]
@ruchikabgosain I think that will work, yep. Let's work on https://github.com/mozilla/addons-code-manager/issues/1032 together then tackle more issues after that. Thanks for diving in!
