### ISSUE TITLE
Preload next diff in compare mode to increase perceived performance

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1062]
### Describe the problem and steps to reproduce it:

When reviewing a version comparison, reviewers often go from the first diff to the next diff, one at a time, in order.

### What happened?

When the next diff lives in a new file, the reviewer has to wait for the file / diff to load.

### What did you expect to happen?

The new file / diff should be preloaded so that it appears instantly.

### Anything else we should know?

The flow would look like this:

- When viewing a version comparison, the reviewer loads the first file, this takes the normal time it takes
- The reviewer presses `n` to jump to the next diff in a new file
- This new file / diff should load instantly
- If the reviewer navigates to a file / diff out of order then it can load just like normal and the pre-load process repeats

See https://github.com/mozilla/addons-code-manager/issues/919 for pre-loading in browse mode.

**Comment by ioanarusiczki** [comment]
@kumar303 I tested with a couple of compare pages and it works for me. 

![moves well ](https://user-images.githubusercontent.com/33448286/67295825-53fe1680-f4f0-11e9-829b-40fe47a67420.gif)

Verified on dev with FF69(Win10).
