### ISSUE TITLE
Switching between a minified file in browse mode causes a browser hang

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1068]
### Describe the problem and steps to reproduce it:

* Sign in
* Go to https://code.addons-dev.allizom.org/en-US/browse/502868/versions/1688187/?path=src%2Fjs%2FGrammarly-signin.styles.js
* Press `k` to go up to the file `Grammarly-signin.js`. Let it load.
* Press `k` to go up one more file
* Press `j` to go back down to `Grammarly-signin.js`

### What happened?

Firefox (Chrome, too) hangs and shows a yellow warning banner asking if you want to stop the page.

### What did you expect to happen?

Definitely not that.

### Anything else we should know?

Using a development build I see this in the profiler:

<details>
<summary>Screenshot</summary>

<img width="1319" alt="Screenshot 2019-09-19 17 03 18" src="https://user-images.githubusercontent.com/55398/65284681-e9784600-daff-11e9-8fce-9b0ea890a3e2.png">

</details>

It says: "(Committing Changes) Warning: Lifecycle hook scheduled a cascading update"

After some searching, I found https://github.com/reduxjs/react-redux/issues/834 , which suggests that something in our `mapStateToProps` is returning a prop value which is constantly triggering an update. It does eventually render if you wait long enough, though.

**Comment by kumar303** [comment]
Well, huh. I thought I could bisect this but it's still broken all the way back in 253b5294ca8a4f1bb0269fb8f3604c01d44f7104 (Jun 12, 2019) so maybe it has always been broken.

**Comment by willdurand** [comment]
mmh I cannot reproduce this issue anymore.

**Comment by bobsilverberg** [comment]
> mmh I cannot reproduce this issue anymore.

Perhaps this was fixed by https://github.com/mozilla/addons-code-manager/commit/112e2ebb71ad233e805799fab045f9b6d9a08a37?

**Comment by willdurand** [comment]
> Perhaps this was fixed by [112e2eb](https://github.com/mozilla/addons-code-manager/commit/112e2ebb71ad233e805799fab045f9b6d9a08a37)?

ah yes, probably. We should probably display the `Syntax highlighting was disabled for performance` warning.

**Comment by bobsilverberg** [comment]
> > Perhaps this was fixed by [112e2eb](https://github.com/mozilla/addons-code-manager/commit/112e2ebb71ad233e805799fab045f9b6d9a08a37)?
> 
> ah yes, probably. We should probably display the `Syntax highlighting was disabled for performance` warning.

Yes, that should have been added during [112e2eb](https://github.com/mozilla/addons-code-manager/commit/112e2ebb71ad233e805799fab045f9b6d9a08a37), but I believe I have added that in https://github.com/mozilla/addons-code-manager/issues/1347.

**Comment by bobsilverberg** [comment]
This is no longer reproducible.
