### ISSUE TITLE
View a list of files in an add-on

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#107]
This supports the user story:

> As a code reviewer, I want to be able to inspect the entire source code and image assets of any version of an add-on I’m reviewing.

API: https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#browse

This requires a `version_id` that should be applied through the URL the user clicks on the reviewer tools page.

<img src="https://user-images.githubusercontent.com/139033/51308927-8cddfc00-1a43-11e9-9c5e-88516b07ee2a.png" width="240">

The left side shows an example of viewing a list of files in an add-on:

![51308318-21475f00-1a42-11e9-9d60-01d005a6ffe6](https://user-images.githubusercontent.com/55398/52148738-3cb08d80-2630-11e9-82fe-b749a02a2b3b.png)

**Comment by willdurand** [comment]
The basic version has been implemented in #160.
