### ISSUE TITLE
Browsing to a minified file is slow

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1086]
### Describe the problem and steps to reproduce it:

- Log in
- Go to https://code.addons-dev.allizom.org/en-US/browse/494431/versions/1532144/?path=jquery-ui%2Fjs%2Fjquery-1.7.1.min.js
- Press `j` to load https://code.addons-dev.allizom.org/en-US/browse/494431/versions/1532144/?path=jquery-ui%2Fjs%2Fjquery-ui-1.8.16.custom.min.js
- Go back and forth between the files to make sure they are loaded in the cache

### What happened?

Even when cached, the `jquery-ui-1.8.16.custom.min.js` renders slowly.

### What did you expect to happen?

It should load quicker because it's unclear if the UI is working or not. It is violating the [100ms rule](https://www.nngroup.com/articles/response-times-3-important-limits/).

### Anything else we should know?

This sounds similar to https://github.com/mozilla/addons-code-manager/issues/1068 but I think it might be different. I *think* it's because minified files have very long (wide) lines so there are a lot of DOM mutations.

This might be fixed by rendering truncated lines. You can't see the overflow content without scrolling anyway.

Truncated lines will also help with https://github.com/mozilla/addons-code-manager/issues/997

**Comment by bobsilverberg** [comment]
I was doing some experimentation to try to figure out what was going on for #1284, which is still a bit of a mystery, but while doing so I discovered that *not* highlighting the code for minified files makes everything considerably faster. 

I wonder how reviewers treat minified files. Do they actually attempt to review the code in them (which seems like it would be very difficult to do)? If not, then maybe we can not highlight them and that would make everything snappier.

Of course being able to recognize a minified file (which, I believe, we have nothing in place to do as of yet), is another matter, but maybe we could start with a simple heuristic like any file with a line longer than `x` could be considered minified and therefore a candidate to not highlight? We could also include a toggle like we have for truncated files which would allow a reviewer to turn highlighting back on if the app made a bad decision about a particular file.

@wagnerand and @willdurand what are your thoughts on this?

**Comment by willdurand** [comment]
Yeah, I agree that we could come up with an heuristic to detect minified files. Such files are always a problem anyway, no matter the editor (e.g., I use `vim` because it is fast but loading (large) minified files is still... slow).

> We could also include a toggle like we have for truncated files which would allow a reviewer to turn highlighting back on if the app made a bad decision about a particular file.

+1

**Comment by wagnerand** [comment]
> I wonder how reviewers treat minified files. Do they actually attempt to review the code in them (which seems like it would be very difficult to do)? If not, then maybe we can not highlight them and that would make everything snappier.

Usually, reviewers do not attempt to review minified code. Most important for reviewers is to identify code as minified vs not minified. If we can add tooling that supports reviewers in that, even better.

I'm fine with both disabling highlighting and also truncating minified files by default.

**Comment by wagnerand** [comment]
@bobsilverberg Sounds good!

**Comment by bobsilverberg** [comment]
https://github.com/mozilla/addons-code-manager/issues/1337 has fixed this issue. We haven't implemented a check for minified files, per se, but we are checking for files with very long lines, which tends to be the case for minified files. Any files that meet that criteria will have highlighting disabled for them, which resolves the issue discussed here.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I could no longer reproduced the issue described above. 
Verified on dev with FF71(Win10). 

![loads fast](https://user-images.githubusercontent.com/33448286/71364771-d3b66900-25a5-11ea-86a3-a80bdb13c535.gif)
