### ISSUE TITLE
View an image file

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#109]
This supports the user story:

> As a code reviewer, I want to be able to inspect the entire source code and image assets of any version of an add-on I’m reviewing.

After selecting an image file (https://github.com/mozilla/addons-code-manager/issues/107), see the image. This is similar to viewing a text file (https://github.com/mozilla/addons-code-manager/issues/108).

**Comment by bobsilverberg** [comment]
Just a note that this also came up in our walkthrough of the current reviewer tools, as a feature that is currently missing but desired.

**Comment by AlexandraMoga** [comment]
Verified on -dev with Fx66, Win10x64

I've submitted an add-on with various image formats and then checked if and how they were rendered in the file viewer. I've tried to use most of the accepted images listed in https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Firefox

Here is the example: https://code.addons-dev.allizom.org/en-US/browse/616837/versions/1688164/

 - I haven't noticed issues with `.jpg`, `.png` `.gif` or `.webp` 

@bobsilverberg I have some potential issues:
 - `bmp`s are not rendered - see [this](https://code.addons-dev.allizom.org/en-US/browse/616837/versions/1688164/?path=Img%2Fmydearbonnie.bmp) and [this](https://code.addons-dev.allizom.org/en-US/browse/616837/versions/1688164/?path=Img%2F640x400%20%28png%29.bmp)
 - `svg`s are not rendered - see [this](https://code.addons-dev.allizom.org/en-US/browse/616837/versions/1688164/?path=Img%2Flisting-small.svg) and [this](https://code.addons-dev.allizom.org/en-US/browse/385621/versions/1655456/?path=img%2Fhero-warning-major-networks.svg)
- invalid images (for example a non-image file that has an image extension type) are decoded as text - see [this example](https://code.addons-dev.allizom.org/en-US/browse/616837/versions/1688164/?path=Img%2Finvalid%20image%20type.png); Is this the expected outcome?

**Comment by bobsilverberg** [comment]
Thanks for the testing, @AlexandraMoga!

> - `bmp`s are not rendered - see [this](https://code.addons-dev.allizom.org/en-US/browse/616837/versions/1688164/?path=Img%2Fmydearbonnie.bmp) and [this](https://code.addons-dev.allizom.org/en-US/browse/616837/versions/1688164/?path=Img%2F640x400%20%28png%29.bmp)

I notice that the bmps you used have a mime type of `image/x-ms-bmp`, which I had not included in the list of valid mime types. When I add it everything seems to work, so I will make that change. Could you please open a follow-up issue to track this change?

> - `svg`s are not rendered - see [this](https://code.addons-dev.allizom.org/en-US/browse/616837/versions/1688164/?path=Img%2Flisting-small.svg) and [this](https://code.addons-dev.allizom.org/en-US/browse/385621/versions/1655456/?path=img%2Fhero-warning-major-networks.svg)

This one is a bit odd. I noticed again that the mime type of these svgs is different than the one I coded for. The app currently supports `image/svg+xml`, but these ones are `image/svg`. When I tried updating the code to also support `image/svg` I ended up with broken images for any of these files. This is going to require more investigation. Could you please open an issue for this?

> - invalid images (for example a non-image file that has an image extension type) are decoded as text - see [this example](https://code.addons-dev.allizom.org/en-US/browse/616837/versions/1688164/?path=Img%2Finvalid%20image%20type.png); Is this the expected outcome?

For this specific example, I can see the mime type of the file is `application/zip`, so even though you named the file with an extension of `png`, when it was extracted from the xpi file it was not categorized as an image. Therefore none of the code that processes images was used when rendering it, and we simply render the contents of the file, much like we do for `cose.sig`, for example. So yes, this is the expected outcome.

**Comment by AlexandraMoga** [comment]
I've filed follow-ups for the `.bmp` and `.svg` issues.
