### ISSUE TITLE
Simplify how comments are fetched and loaded

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1096]
A thunk to fetch and load comments was added in https://github.com/mozilla/addons-code-manager/issues/1091

This contained some mapping code to minimize the number of redux dispatches when fetching comments. I think we can make changes to the `setComments` action so that this mapping isn't needed.

This supports rendering comments: https://github.com/mozilla/addons-code-manager/issues/713

**Comment by ioanarusiczki** [comment]
@kumar303 I tested yesterday the comment text box for https://github.com/mozilla/addons-code-manager/issues/1082
If there's anything else I can check for this issue please let me know.

**Comment by kumar303** [comment]
Ah, yes, I forgot to mention that QA for this is just regression testing. What you checked already should cover it. Thanks!
