### ISSUE TITLE
Show code files with syntax highlighting

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#110]
User story:

> As a code reviewer, I want the file viewer and diff viewer to provide code syntax highlighting when possible, so I can read the code more easily.

When viewing text files (https://github.com/mozilla/addons-code-manager/issues/108), the code should have syntax highlighting. This will probably happen by default but we should verify that all common add-on files will get syntax highlighting.

**Comment by EnTeQuAk** [comment]
For that, I wonder if highlighting happens in the client or if the backend should expose highlighted code. With http://pygments.org/ we have a crazy powerful tool to do so.

In any case, we should make sure that code-highlighting works while viewing diffs too.

**Comment by willdurand** [comment]
I don't think we should highlight code in the backend, that will make things complicated in the frontend. The frontend must control all the UI bits. There are popular libs for that, and depending on the code renderer, that might be provided already

**Comment by wagnerand** [comment]
Some file formats we can test support for (in order of importance, most important ones first):
* JS
* JSON
* HTML
* CSS
* XML (search-plugins)
