### ISSUE TITLE
Cancel entering a comment

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1101]
### Describe the problem and steps to reproduce it:

* Sign in
* Browse a version
* Click the plus sign next to a line of a file to enter a comment
* Decide you want to cancel entering a comment

### What happened?

There is only a *Save* button, no cancel button.

### What did you expect to happen?

There should be a cancel button that closes the form.

**Comment by mirefly** [comment]
@kumar303 May I take on this?

**Comment by kumar303** [comment]
Yep, go for it. You can check out the current delete button to get an idea for it.

**Comment by kumar303** [comment]
btw, I've been using http://localhost:3000/en-US/browse/616959/versions/1688394/ to test comments but I think it should work fine in other versions.

**Comment by ioanarusiczki** [comment]
@kumar303 I verified this on dev with FF70(Win10) and the `Discard` button is available and works as expected. 
It is available only when writing a new comment (editing is not available yet). 

![Discard](https://user-images.githubusercontent.com/33448286/68744150-9cdf5180-05fc-11ea-9178-907e6849dc4e.gif)
