### ISSUE TITLE
Continuous " Saving" state is displayed when saving an empty comment 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1106]
Followup for https://github.com/mozilla/addons-code-manager/issues/1082

STR:
1. Load a file for an add-on in code-manager such as https://code.addons-dev.allizom.org/en-US/browse/617545/versions/1688861/
2. Submit an empty comment (just click "Save")

Expected result:
An empty comment cannot be submitted - the field requires at least one char and then the "Save" button becomes enabled.

Actual result:
A "saving" state. 

Note:
This issue is reproducible on dev with FF69(Win10). 

![issues2](https://user-images.githubusercontent.com/33448286/66318352-d1882b00-e923-11e9-9ee9-4b1f4a2d5b9d.png)

Please note that I can create with Postman using the [API](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#drafting-comments) an empty comment.
![API response](https://user-images.githubusercontent.com/33448286/66317860-fa5bf080-e922-11e9-9d48-fce118e4c894.png)

**Comment by kumar303** [comment]
The cause of this is `Error: Either cannedResponseId or comment must be specified` which results in an unhandled promise rejection, coming from this:

https://github.com/mozilla/addons-code-manager/blob/980d88413d4457f0b545d2dd413d9195934da6b4/src/api/index.tsx#L411

The error is thrown from the [`manageComment`](https://github.com/mozilla/addons-code-manager/blob/980d88413d4457f0b545d2dd413d9195934da6b4/src/reducers/comments.tsx#L364) thunk.

**Comment by kumar303** [comment]
I filed https://github.com/mozilla/addons-code-manager/issues/1239 to make this unexpected error more visible.

**Comment by ioanarusiczki** [comment]
@kumar303 Verified on dev with FF70(Win10). 
- an empty comment can be saved until the fix of https://github.com/mozilla/addons-server/issues/12865

![empty comment](https://user-images.githubusercontent.com/33448286/68941431-8973e800-07ae-11ea-9c01-11a6c39be16b.gif)
