### ISSUE TITLE
[Reviewer comments] A long unbroken string breaks the layout of the page 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1108]
Followup for https://github.com/mozilla/addons-code-manager/issues/1082

STR:
1. Add a long unbroken string as comment using the "+" button for a code line in a file such as for https://code.addons-dev.allizom.org/en-US/browse/617545/versions/1688861/
2. Save and observe the layout of the page

Expected result:
No layout issues.

Actual result:
The text looks cut, when other comments are available those will no longer fit the screen either. 

Notes:
Reproducible on dev - FF69(Win10). 
There's a scroll bar that can be used to see the whole comment. 

For a better understanding please look at the gif below: 

![unbroken string scenario](https://user-images.githubusercontent.com/33448286/66320100-e31f0200-e926-11e9-9513-4159218f616f.gif)

**Comment by kumar303** [comment]
Thanks. This is similar to https://github.com/mozilla/addons-code-manager/issues/997 but will need to be solved in a different way.

**Comment by ioanarusiczki** [comment]
@kumar303 This is no longer reproducible on dev with FF70(Win10). 

![fixed](https://user-images.githubusercontent.com/33448286/68679867-57257900-0569-11ea-8aaf-358921c37c4b.png)
