### ISSUE TITLE
View diff between two versions

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#111]
User story:

> As a code reviewer, I want to be able to view the source code diff between any two versions of an add-on I’m reviewing.

Here's an example of looking at the diff between version 1.69.0 and 1.69.1 of LastPass. URL: https://reviewers.addons-dev.allizom.org/en-US/firefox/files/compare/93833...93882/

<img width="1518" alt="screenshot 2019-02-01 15 31 09" src="https://user-images.githubusercontent.com/55398/52150767-95832480-2636-11e9-85c6-81a8cbb1e3ab.png">

**Comment by EnTeQuAk** [comment]
Not necessarily blocked by, but the version-chooser component needs https://github.com/mozilla/addons-server/issues/10432 to be done first. (working on it).
