### ISSUE TITLE
Comment on a specific line of a file

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#112]
User story:

> As a code reviewer, I want to be able to enter custom comments for specific code lines in the file and diff viewer.

When viewing a file (https://github.com/mozilla/addons-code-manager/issues/108), the reviewer can enter a comment on a specific line.

The suggested UI flow per [meeting notes](https://docs.google.com/document/d/1y4crrHxhGejb3eZ6HpjtBdDqONJakfwtfjaOqwq-qZo/edit) is roughly this:
- click on a line of a file to begin entering a comment
- ~~when presented with a list of canned responses, click *other*~~ (this will be added in https://github.com/mozilla/addons-code-manager/issues/780)
- begin entering text
- press save

**For QA**: note that refreshing the page won't show the comment yet (see https://github.com/mozilla/addons-code-manager/issues/713)

**Comment by EnTeQuAk** [comment]
API-depencency: https://github.com/mozilla/addons-server/issues/11277

**Comment by kumar303** [comment]
It looks like we still need a POST endpoint https://github.com/mozilla/addons-server/issues/11378

**Comment by EnTeQuAk** [comment]
With mozilla/addons-server#11378 being fixed, I'm going to remove the `needs: api` label for now. Let me know if you need anything specific on top of that.

**Comment by kumar303** [comment]
I still need to add an env var for this on the hosted dev site

**Comment by kumar303** [comment]
Commenting is enabled on dev 🎉 It is disabled in stage and prod.
