### ISSUE TITLE
Error: Cannot create key "fileName:null;line:21" because fileName is empty (while loading comments)

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1126]
As a followup for https://github.com/mozilla/addons-code-manager/issues/713#issuecomment-541076423

STR:
1. Load https://code.addons-dev.allizom.org/en-US/browse/491860/versions/1528357/?path=popup.html
2. Open the Web Console and check for the following error `Error: Cannot create key "fileName:null;line:21" because fileName is empty`. In case it is not shown just refresh the page -> it will be displayed

Note:
This error is shown for this particular add-on for all files I verified with - it is not related to making a comment. 
I could not reproduce this issue with another add-on.
The version of the add-on is approved.
After refreshing a page where I added reviewer comments - they disappear. 

![error in the console](https://user-images.githubusercontent.com/33448286/66736324-89ac5b00-ee71-11e9-939b-bad72ebded12.gif)

**Comment by kumar303** [comment]
I can't reproduce this. Had you maybe used Postman to enter a comment on this version directly with the API? The page only loads comments created by the currently signed in user which is probably why I can't reproduce it.

**Comment by kumar303** [comment]
@ioanarusiczki could you trigger this error again? I just landed a debugging helper (https://github.com/mozilla/addons-code-manager/issues/1123) which will give me more information about it.

**Comment by ioanarusiczki** [comment]
@kumar303 I reproduced the issue again - reloading popup.html and manifest.json. 
I see 26 comments made for this addon and version with 
https://addons-dev.allizom.org/api/v4/reviewers/addon/491860/versions/1528357/draft_comments/
I'm pretty sure I used Postman too for a part of these while testing.

**Comment by kumar303** [comment]
Huh. The most recent error I found on dev was from just before I left [this comment](https://github.com/mozilla/addons-code-manager/issues/1126#issuecomment-541886755) so it doesn't include the added debugging. Could you try it once more at https://code.addons-dev.allizom.org/en-US/browse/491860/versions/1528357/?path=popup.html ?

**Comment by kumar303** [comment]
Aha! Nevermind about retrying it once more. I had a theory on how to reproduce the error and it worked 🎉 It's an API bug that I will file.

**Comment by kumar303** [comment]
Here is the API bug: https://github.com/mozilla/addons-server/issues/12635

Once a fix for that lands, I can delete all comments on the dev server to make the errors go away.

**Comment by ioanarusiczki** [comment]
@kumar303 Aha. I send a request 
 "comment":"text now",
	"filename":null,
	"lineno":5
and it was created. 
Nice catch! :)

**Comment by bobsilverberg** [comment]
This is fine to close because https://github.com/mozilla/addons-server/issues/12635 has landed.
