### ISSUE TITLE
Always show the top NavBar

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1139]
For the UI of https://github.com/mozilla/addons-code-manager/issues/114 I was considering adding some actions to the NavBar. Through this process I noticed that the NavBar is hidden when the page first loads and this creates jumpiness. Let's always show the NavBar.

For QA: check for regressions in the top NavBar shown on the home page, browse, compare.

**Comment by ioanarusiczki** [comment]
@kumar303 I don't see issues. It works as before (compared with stage). 
The header is loaded with the sign out and  `displayname` next to it. On the left side the name of the add-on loads with a small delay (it's the same on stage). 
Reloading the page works the same way. 
`Log out` is active while the content loads (for the rest of the page). 

![Header is fine](https://user-images.githubusercontent.com/33448286/67090731-8687d680-f1b3-11e9-91d6-4d5c96059fdc.gif)
