### ISSUE TITLE
Prepare to send review comments to a developer

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#114]
User story:

> As a code reviewer, I want my code comments to be copied to my review message to the developer.

Reviewers already use a screen like this to enter a review: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/remote-script-coinhive

The new file viewer (hosted in this repo) will allow them to prepare a review response by commenting directly on the files (https://github.com/mozilla/addons-code-manager/issues/112, https://github.com/mozilla/addons-code-manager/issues/113). The reviewer needs to finalize their review which should either send directly to the developer or save a draft that they can complete on the reviewer tools page.

Step 2 of [these meeting notes](https://docs.google.com/document/d/1y4crrHxhGejb3eZ6HpjtBdDqONJakfwtfjaOqwq-qZo/edit) suggest a flow for submitting comments to a developer.

**Comment by ioanarusiczki** [comment]
@kumar303 I checked this on dev with FF69(Win10):

**Test results**

Functionality:
- the `Comment Summary` button can be opened and the content is displayed as[ here](https://user-images.githubusercontent.com/55398/67706756-5399cb80-f987-11e9-911e-fe3d9e60faed.png) 
- I could close it using `Close` button, `esc` key or clicking outside the box or another action such as clicking on a code line from the code overview or collapsing the side panels. 
- the number of comments is displayed between the add-ons name and `Comment Summary` button. If I delete or add a comment the number is updated correctly. 

The UI:
-  the font type for `Comment Summary` blue button looks a bit different and better in the screenshot https://user-images.githubusercontent.com/55398/67706756-5399cb80-f987-11e9-911e-fe3d9e60faed.png. Perhaps it's just the size different but both ways, that could be adjusted. 

![the button](https://user-images.githubusercontent.com/33448286/67783948-af418300-fa73-11e9-81bb-61e135c40438.png)

- The [screenshot]( https://user-images.githubusercontent.com/55398/67706756-5399cb80-f987-11e9-911e-fe3d9e60faed.png) displays a blue border that I did not see present on [dev](https://code.addons-dev.allizom.org/en-US/browse/390151/versions/1688302/?messageUid=0f2fa4cbd8354a6fb1020f5f7ec2369e&path=mozilla-recommendation.json), it would look nicer that way.

![no blue border](https://user-images.githubusercontent.com/33448286/67784032-cf714200-fa73-11e9-95e1-ef7299f9b6b3.png)

- perhaps the paths for the files could be dark blue ?
- perhaps the font size of the comments made could be increased a little bit.

**Comment by kumar303** [comment]
> * the font type for Comment Summary blue button looks a bit different and better in the screenshot
> * The screenshot displays a blue border that I did not see present on dev
> * perhaps the font size of the comments made could be increased a little bit.

Huh. I can confirm that these are all Windows specific issues. Can you file bugs?

**Comment by ioanarusiczki** [comment]
@kumar303 Done https://github.com/mozilla/addons-code-manager/issues/1187
