### ISSUE TITLE
A comment is visible only for the reviewer who made it 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1143]
STR:
1. Load a Browse page and leave a comment such as 
https://code.addons-dev.allizom.org/en-US/browse/495710/versions/1541609/?path=src%2Faction%2Findex.html
2. Log out 
3. Log in back with another user with code manager rights (admin or add-on reviewer)

Expected result:
The comment left by the first reviewer is visible but cannot be edited/deleted.

Actual result:
The comment is not displayed for the  authenticated user.

Notes:
Reproducible on dev with FF69(Win10). 
If I try to delete a comment which wasn't created by the current authenticated user, the [API](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#canned-responses) responds with a 404 (which is expected). 

![another reviewer](https://user-images.githubusercontent.com/33448286/67213151-306e9980-f426-11e9-9bf8-99633e4ba378.gif)

**Comment by kumar303** [comment]
> Actual result:
> The comment is not displayed for the authenticated user.

This is expected to me. When a reviewer is in the process of reviewing, the comments should only be visible to that reviewer.

However, when the reviewer *submits* their comments to the developer, maybe we should show historic comments to other reviewers but I'm not sure. I think it's fine to figure that out later, after we implement https://github.com/mozilla/addons-server/issues/12660 and https://github.com/mozilla/addons-code-manager/issues/717

**Comment by ioanarusiczki** [comment]
@kumar303 I understand. I thought that perhaps an admin could see what an add-on reviewer left as a comment but without any edit rights.
