### ISSUE TITLE
Adjust comments reducer for finalizing a review

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1144]
The UI in https://github.com/mozilla/addons-code-manager/issues/114 deals with finalizing a review so that a reviewer can prepare to send comments to the developer. The reducer needs to support a few things:

* Allow `Navbar` to select a list of comments so it can render a summary about comments saved so far.
* Support toggling an overlay that will contain a summary of all comments.

**Comment by ioanarusiczki** [comment]
@kumar303 When first time a file is loaded (or at page reload) the comments appear with a small delay compared with the rest of the content.
It's the same behavior as before, it is not a regression.

Please take a look:

![loading](https://user-images.githubusercontent.com/33448286/67552726-475a0800-f714-11e9-84af-ad3278e43280.gif)

**Comment by kumar303** [comment]
Yeah, I've noticed this, too. I'm not sure if there's anything we can do about it. Typically, I'd like to see a skeleton screen (while loading) for something like this but that wouldn't make sense here as not all files will have comments and we can't guess where they would appear in the file. We could maybe add a loading indicator after some `NavBar` UI for https://github.com/mozilla/addons-code-manager/issues/114 lands.

**Comment by ioanarusiczki** [comment]
@kumar303 A loading indicator could improve the UI. Great idea. 
Meanwhile, I'll mark this issue verified on dev with FF70.
