### ISSUE TITLE
Mark files / code that can be skipped during review

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#115]
User story:

> As a code reviewer, I want the file and diff viewer to mark files or code fragments that can be skipped during review, like known library and framework code.

The validator data (https://github.com/mozilla/addons-code-manager/issues/41) will provide info about files that can be skipped during review. The UX for this should not completely hide the files that can be skipped. They should be grayed out or something like that.

**Comment by wagnerand** [comment]
Example of what it looks like in the current file viewer:

<img width="230" alt="screenshot 2019-03-06 at 19 32 52" src="https://user-images.githubusercontent.com/873258/53904637-d8298980-4046-11e9-9a3a-291a2022f54d.png">

**Comment by wagnerand** [comment]
Hovering over the blue icon:

<img width="363" alt="screenshot 2019-03-06 at 19 35 49" src="https://user-images.githubusercontent.com/873258/53904818-41a99800-4047-11e9-90c8-5173aff7631a.png">

**Comment by willdurand** [comment]
We could build this feature on-top of #401:

![Screen Shot 2019-03-19 at 15 36 52](https://user-images.githubusercontent.com/217628/54614568-ede27a00-4a5c-11e9-8d87-bb5c44b37eba.png)
