### ISSUE TITLE
Compare is not available in Contents review 

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-code-manager#1159]
Often happens when a previously reviewed version is disabled. Under these circumstances, the "Compare" option/link is not displayed.

However, in the old review window, it is possible to set a compare manually by selecting the desired version. In other words, change from 'Contents' to 'Compare' review.

In the new Code Manger review, I did not see such option. If it is there, then please let me know and close this issue.

![Screenshot_2019-10-25 File Viewer Reviewer tools](https://user-images.githubusercontent.com/6458876/67544931-30abb500-f704-11e9-9ea8-d589a866ed85.png)

Here is an example of user who always deletes previously reviewed version when uploading a new version, thus making 'Compare' unavailable directly:
`https://reviewers.addons.mozilla.org/reviewers/review/989342/`

**Comment by kumar303** [comment]
Thanks, I didn't know about this behavior. We should definitely show a comparison selector to help out with this case.

This also led me to file a few related issues:
* https://github.com/mozilla/addons-code-manager/issues/1162
* https://github.com/mozilla/addons-code-manager/issues/1163

**Comment by kumar303** [comment]
We do have https://github.com/mozilla/addons-code-manager/issues/758 on file about always showing the compare selector but I want to keep this one open to illustrate the specific case of when developers delete historic versions.

**Comment by kumar303** [comment]
We'll address this in https://github.com/mozilla/addons-code-manager/issues/758 and we can refer back to this for the use case.
