### ISSUE TITLE
Compare a non-deleted version to a deleted version

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1163]
### Describe the problem and steps to reproduce it:

If a developer deletes historic versions, it should still be possible to view a comparison of the new version compared to the old deleted one. This will help the reviewer look for changes in the new version.

See https://github.com/mozilla/addons-code-manager/issues/1159

### What happened?

Viewing a comparison like this leads to the API returning a 404 and Code Manger cannot display a comparison.

### What did you expect to happen?

Code Manager should display the comparison.

### Anything else we should know?

This needs an API fix: https://github.com/mozilla/addons-server/issues/12726

**Comment by AlexandraMoga** [comment]
I've re-verified this on -dev and the issue can no longer be reproduced. 
I've tested both with an admin user and an add-on reviewer that also has `Addons:ViewDeleted` permissions and I was able to compare a deleted version with a non-deleted version.
Examples:
https://code.addons-dev.allizom.org/en-US/compare/618827/versions/1690268...1690270/
https://code.addons-dev.allizom.org/en-US/compare/618821/versions/1690254...1690255/
