### ISSUE TITLE
Indicate when a file or folder has comments

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1174]
### Describe the problem and steps to reproduce it:

* Add a lot of comments in multiple files
* Begin finishing your review (https://github.com/mozilla/addons-code-manager/issues/114)

### What happened?

If you want to revisit / delete / edit some comments, it's hard to know which files and folders have comments.

### What did you expect to happen?

Just like for linter messages, the file tree should provide some icons as clues. Example:

<img width="551" alt="Screenshot 2019-10-29 15 30 55" src="https://user-images.githubusercontent.com/55398/67806780-8dd79b80-fa61-11e9-8a89-90577c109321.png">

**Comment by ioanarusiczki** [comment]
@kumar303 
Looks good to me. The only UI thing which would be that the message icon is a bit unaligned next to a linter warning but it doesn't bother me.

![a bit unaligned](https://user-images.githubusercontent.com/33448286/68127245-28caec80-ff1e-11e9-8035-cbdfcda8d1c3.png)

as functionality:
- it is available when a message is available for a file. When all messages for a particular file are deleted the message icon disappears.
- clicking on a directory message icon will open/close the files below.
- the tooltip when hovering over the icon for a directory is "This directory contains files with comments".  For a file: "This file has comments". 

Verified on dev with FF70(Win10).

**Comment by kumar303** [comment]
> ... The only UI thing would be that the message icon is a bit unaligned next to a linter warning but it doesn't bother me.

Hmm, yeah. I noticed this, too. The icons are indeed perfectly center-aligned but because the comment icon is a box with a triangle at the bottom, the box appears off center.
