### ISSUE TITLE
Add a selector / reducer to know if a file path has comments or not

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1175]
When rendering comment icons in a file tree (https://github.com/mozilla/addons-code-manager/issues/1174), we need better app state to know if a file path has comments or not. With the current app state, it would take `O(numberOfFilePaths * numberOfComments)` complexity to display icons.

**Comment by ioanarusiczki** [comment]
@kumar303 Let me know if there's anything else that I should verify that was not done for https://github.com/mozilla/addons-code-manager/issues/1174

**Comment by kumar303** [comment]
Ah, whoops, this was meant to be `qa: not needed` since, yeah, QA for it happened in https://github.com/mozilla/addons-code-manager/issues/1174
