### ISSUE TITLE
Toggle a pretty / formatted version of a file

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#118]
User story:

> As a reviewer, I want to toggle on a pretty / formatted version of the current JavaScript file

When viewing a JavaScript file (https://github.com/mozilla/addons-code-manager/issues/108), a button should allow the reviewer to temporarily view a formatted version. It's not clear how commenting would work in this view.

**Comment by bobsilverberg** [comment]
@wagnerand I think this is a duplicate of #1345, do you agree?

**Comment by wagnerand** [comment]
@bobsilverberg Agreed.
