### ISSUE TITLE
De-obfuscate a file

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#119]
User story:

> As a reviewer, I want to de-obfuscate obfuscated code in the current file

Some add-on code is obfuscated. This would allow the reviewer to try and make sense of the code. It will be an enhancement of the simpler code formatter button (https://github.com/mozilla/addons-code-manager/issues/118).

**Comment by kewisch** [comment]
Note we are disallowing obfuscation June 10th, so simply a code beautifier to format the code is sufficient.
