### ISSUE TITLE
Add helper for creating an error response

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1193]
Some API code deals with an [`ErrorResponseObject`](https://github.com/mozilla/addons-code-manager/blob/master/src/api/index.tsx#L120). Here's how we write tests to simulate this:

```js
const errorResponse = { 
  error: new Error('API Error') 
};
const getSomethingFromApi = jest.fn()
  .mockResolvedValue(errorResponse);
```

We should replace this with a helper similar to [`createFakeApiPage()`](https://github.com/mozilla/addons-code-manager/blob/ceb6e9158b68d2dec1e667a99f6ea0ae25148804/src/test-helpers.tsx#L943). Maybe something like:

```js
const errorResponse = createErrorResponse({ 
  error: new Error('API Error') 
});
```

This will help us evolve the `ErrorResponseObject` in the future if we need to. Currently, it would be hard to evolve this type because any time `jest.fn()` is used, it returns the type `unknown` which stops TypeScript from type checking anything further.

**Comment by ragnarokatz** [comment]
@kumar303 hello, I would like to work on this issue please.

**Comment by ragnarokatz** [comment]
@kumar303 a question for clarification, due to the aforementioned behaviour of `jest.fn()`, do you want the entire lines of
```
const getSomethingFromApi = jest.fn()
  .mockResolvedValue(errorResponse);
```
to be replaced with something else?

**Comment by kumar303** [comment]
@ragnarokatz hello, thanks for working on this issue. Yes, it would look like this:

```js
// A definition of createErrorResponse() needs to be added here:
import { createErrorResponse } from '../test-helpers';

const getSomethingFromApi = jest.fn()
  .mockResolvedValue(createErrorResponse({ 
    error: new Error('API Error') 
  }));
```

**Comment by ragnarokatz** [comment]
@kumar303 PR is ready for review. Quite a few changes here and there. Please take a look when you have time.

**Comment by kumar303** [comment]
@ragnarokatz thanks again!

This was fixed in https://github.com/mozilla/addons-code-manager/pull/1255
