### ISSUE TITLE
Write review comments in Markdown

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#120]
User story:

> As a reviewer, I want to be able to format my review message using a simple markup like Markdown.

This is an enhancement of writing a review comment on a specific line of a file (https://github.com/mozilla/addons-code-manager/issues/112).

**Comment by EnTeQuAk** [comment]
This most certainly needs some discussion as I wonder if we should convert this to HTML on the server-side when sending mails and how that'll be handled for plain-text versions of them.
