### ISSUE TITLE
Enable commenting in production

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1202]
We have completed enough [commenting issues](https://github.com/orgs/mozilla/projects/66) to ship the feature! It will be rough around the edges but it should allow reviewers to perform a basic review. This issue is to flip the config flag on in production so we can get some feedback from reviewers.

**Comment by ioanarusiczki** [comment]
@kumar303 Indeed, that's a good idea to get the reviewer's feedback on what has been done so far. 

- the feature is now available on AMO stage. I verified with FF70(Win10). 
- the reviewers can add and delete reviews on code lines clicking the `+` (`add a comment` is available while hovering next to the code line numbers) on the Browse pages. 
- the reviewers can open the `Comment Summary` and see the comments left in chronological order.
- the `Comment Summary` can be closed.
- the number of comments left is updated by `Comments`.
