### ISSUE TITLE
Long unbroken lines of code break comment forms

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1207]
### Describe the problem and steps to reproduce it:

* Browse a file that has long unbroken lines of code, such as minified JS
* Try to comment on one of the long lines

<details>
<summary>Example</summary>

![image](https://user-images.githubusercontent.com/55398/68313254-e3233680-0079-11ea-854a-746cd051f84b.png)

</details>

### What happened?

The comment box scrolls off the screen making it hard to type a comment.

### What did you expect to happen?

The comment box should fit the viewport width

**Comment by ioanarusiczki** [comment]
@kumar303 I could not reproduce this issue on dev with FF70(Win10). 

![js fix](https://user-images.githubusercontent.com/33448286/68745788-f9903b80-05ff-11ea-9d8f-4d925d39781f.gif)
