### ISSUE TITLE
Commenting Cancel/Close button

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-code-manager#1219]
After clicking and opening the comments box, The only option is to **Save**. There is no **Cancel** or **Close**.

**Comment by kumar303** [comment]
Thanks for filing an issue! This was already being tracked in https://github.com/mozilla/addons-code-manager/issues/1101 and a patch for it is currently under review.

**Comment by kumar303** [comment]
In the meantime, you can refresh the page to close a comment box.
