### ISSUE TITLE
See all images on one page

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#122]
User story:

> As a code reviewer, I want to be able to see all image assets on one page for quicker review.

**Comment by jvillalobos** [comment]
The use case @kewisch had in mind is when an extension has a folder full of images, where it would be nice to see a tiled view of all images at once, to look for any inappropriate content in them without having to click through each one.

I don't think media-heavy extensions are _that_ common, so I would consider this a low priority nice to have feature.

**Comment by wagnerand** [comment]
I agree with Jorge.
