### ISSUE TITLE
Add comments story for discard / confirm UI states

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1227]
Add a [story](https://github.com/mozilla/addons-code-manager#storybook) for the discard / confirm UI states related to cancelling a comment (https://github.com/mozilla/addons-code-manager/issues/1101).

**Comment by kumar303** [comment]
@mirefly could you work on this as a follow up to https://github.com/mozilla/addons-code-manager/pull/1213 ? We usually include stories as part of any UI patch but I forgot to ask for it when reviewing. Be sure to update master as some changes to the comments story just landed.

**Comment by mirefly** [comment]
Sure. I will work on this.
