### ISSUE TITLE
Show a summary of all diff comments

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1231]
### Describe the problem and steps to reproduce it:

* Add multiple comments on file diffs in compare mode (this depends on https://github.com/mozilla/addons-code-manager/issues/989)
* Click *Comment Summary* to view the text output of all comments.

### What happened?

I'm not sure. Does it work?

### What did you expect to happen?

The diff comments should be correctly attributed to the exact file and line number of the newer version (from the comparison).

**Comment by bobsilverberg** [comment]
This is also partially fixed via https://github.com/mozilla/addons-code-manager/commit/76fdcaeb0d1ae06c87f996ba28e96ad425f7bb25, but I am seeing some extra comments. For example, at https://code.addons-dev.allizom.org/en-US/compare/502955/versions/1541794...1541798/ I am seeing two comments in the summary at the top for lines that don't even appear to exist in `manifest.json`.

I will investigate.

**Comment by bobsilverberg** [comment]
This does appear to be also fixed via https://github.com/mozilla/addons-code-manager/commit/76fdcaeb0d1ae06c87f996ba28e96ad425f7bb25. The oddity I mentioned in https://github.com/mozilla/addons-code-manager/issues/1231#issuecomment-561262928 seems to be based on invalid data in the database, not any problems with the Comment Summary in code manager. So I think we can close this. Do you agree @kumar303?

**Comment by kumar303** [comment]
Yes, it seems to be working. Awesome. I mainly wanted to track it for validation purposes.

**Comment by ioanarusiczki** [comment]
@kumar303 I see the comments made in the diff following the path given by the Comment Summary content.
I've also verified this for https://github.com/mozilla/addons-code-manager/issues/989#issuecomment-561201893 in order to understand the presence of a comment on browse and compare pages. 
Verified on dev with FF70(Win10).
