### ISSUE TITLE
Make 'n' and 'p' keyboard shortcuts work in browse mode

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-code-manager#1232]
In browse mode (vs compare mode), the `n` and `p` shortcuts are disabled, because obviously there is no next "change" to jump to. 

It would be great if in this case there would be a fallback to jump to the next file, basically mapping `n` to `j` and `p` to `k`.

**Comment by ioanarusiczki** [comment]
@mirefly I verified this on dev with FF72(Win10):
- for a Browse page: I could navigate to the next or previous file using: `j` or `n` and `k` or `p`. 
- for a Compare page: same behavior as before. `n` and `p` show the next/previous change.
