### ISSUE TITLE
Make the VersionChooser independent from URL data

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1235]
**For QA**: please check for regressions in the version chooser / dropdown on the compare page.

In order to move the version chooser to the navbar so that it can be available on all pages (see https://github.com/mozilla/addons-code-manager/issues/758), we need it to not depend on the URL for its data.

**Comment by ioanarusiczki** [comment]
@kumar303 Checking on dev I found some issues but I should further investigate this. I could not reproduce the issue on stage with another add-on.
Dev - first example https://code.addons-dev.allizom.org/en-US/compare/616909/versions/1688345...1688399/ After I've chosen Old version `7` and New version `10.2.3` if I click another file from the file tree viewer I received an error. 

![compare616909](https://user-images.githubusercontent.com/33448286/69337012-86726f00-0c68-11ea-9526-0d03036721dc.gif)

The same error is displayed when I choose for https://code.addons-dev.allizom.org/en-US/compare/7560/versions/1252898...1510628/ old version `3.3.6` and new version is `5.1.6`

![compare7560](https://user-images.githubusercontent.com/33448286/69337214-0698d480-0c69-11ea-9efa-7339a8c81c95.gif)

I could not reproduce this on stage with https://code.addons.allizom.org/en-US/compare/1002795/versions/2474822...2474841/

**Comment by kumar303** [comment]
> @kumar303 Checking on dev I found some issues but I should further investigate this. 

Interesting. I was able to verify locally that these bugs existed *before* the patch for https://github.com/mozilla/addons-code-manager/issues/1235 landed. I guess we just never noticed them.

> first example https://code.addons-dev.allizom.org/en-US/compare/616909/versions/1688345...1688399/

This one seems related to how the `Img` folder was deleted in version `7`. I'm not sure what the cause is but the file tree may need to take `comparedToVersionId` into consideration.

Please file a new issue so we can fix it.
