### ISSUE TITLE
Selecting a file in the navigation scrolls to line of previous file

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-code-manager#1247]
### Describe the problem and steps to reproduce it:

I noticed that selecting a file in the navigation scrolls to the same line of the previous file.

1. Open a file
2. Scroll down
3. Click on a different file in the navigation

### What happened?

The window is scrolling to the same line as before.

### What did you expect to happen?

Stay at the top of the file.

**Comment by kumar303** [comment]
Hmm. I think maybe it always behaved like this but pre-loading makes it happen all the time now. To confirm, this only applies to navigating to a pre-loaded file, like the next in list, right?

**Comment by wagnerand** [comment]
> To confirm, this only applies to navigating to a pre-loaded file, like the next in list, right?

Yes, I can confirm that.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev both for the browse and compare view.

When another file is selected from the file tree (also applies to keyboard navigation), the top of the file is being displayed:

![2019-11-21_13-20-16](https://user-images.githubusercontent.com/31961530/69333920-50ca8780-0c62-11ea-9641-7a4b8b22d9bc.gif)
