### ISSUE TITLE
Change FileTree to use expandedPaths not tied to a version

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1248]
As a step towards https://github.com/mozilla/addons-code-manager/issues/1094, `FileTree` should use a standalone `expandedPaths` state prop, not tied to `version`.

**For QA**: Please check for any regressions in expanding and collapsing file paths.

**Comment by AlexandraMoga** [comment]
I've verified both the browse and the compare view and couldn't find any regressions with folder expansion/collapsing. 

The folders are also expanding when using keyboard navigation to browse files.
