### ISSUE TITLE
Extract overlay / popover from comment summary

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1249]
I'd like to extract and re-use the comment summary overlay for putting compare-version controls in the nav bar (https://github.com/mozilla/addons-code-manager/issues/758).

**For QA**: Please check for regressions in the comment summary button and overlay

**Comment by ioanarusiczki** [comment]
@kumar303 Checking withhttps://code.addons-dev.allizom.org/en-US/browse/502724/versions/1541510/?allowSlowPages=true&messageUid=c94a6ffe04da45bfac4a17ebf1dc3557&path=content_scripts%2Fcheck-inventory.js I did not see anything unusual. 
Verified on dev with FF70(Win10).
