### ISSUE TITLE
Expand capabilities of PopoverButton

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1256]
The version comparison screen needed for https://github.com/mozilla/addons-code-manager/issues/758 will benefit from a popover since it will be accessible via NavBar.

The goal of this issue is:

* Expand the capabilities of `PopoverButton` so that it can be used for showing a version comparison popover
* Move sharable logic from `CommentSummaryButton` into `PopoverButton`

**For QA**: Please check for regressions in the *Comment Summary* button and its popover content (summary of comments, close button, etc).

**Comment by ioanarusiczki** [comment]
@kumar303 Moving it to the next milestone because there will be no push this week.

**Comment by ioanarusiczki** [comment]
@kumar303 No issues found. 
Verified on dev with FF70(Win10).
