### ISSUE TITLE
Show version comparison range in header

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1263]
### Describe the problem and steps to reproduce it:

* Log in
* Load any version comparison page

### What happened?

The navbar header displays the add-on name

### What did you expect to happen?

It should also display the version comparison range

### Anything else we should know?

The version select boxes *currently* show an indication of the version comparison range but those are going away after https://github.com/mozilla/addons-code-manager/issues/757 (i.e. they will move into a hidden popover menu).

This is a necessary step towards implementing https://github.com/mozilla/addons-code-manager/issues/757

**Comment by ioanarusiczki** [comment]
@kumar303 
I verified on dev and the version number is available now in the header.

Browse
 
![Browse](https://user-images.githubusercontent.com/33448286/69873151-61838a80-126c-11ea-9b2a-0e07d69df2a1.png)

Compare 

![Compare](https://user-images.githubusercontent.com/33448286/69873186-76f8b480-126c-11ea-9659-8c2c54edf984.png)
