### ISSUE TITLE
Do not fetch a version if a fetch is in progress

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1266]
When the compare menu moves into the navbar (https://github.com/mozilla/addons-code-manager/issues/757) it will be possible for the first time to navigate from the browse page to a compare page without reloading the window.

This will reveal a long standing bug where `fetchVersion()` does not check for a fetch in progress before beginning a new fetch.

Let's fix that.

**For QA**: please check for regressions on the browse and compare pages.

**Comment by ioanarusiczki** [comment]
Nothing unusual while testing on dev this week. 
Verified with FF70(Win10).

**Comment by ioanarusiczki** [comment]
@kumar303 There might be an issue though for compare pages. 
I filed it here https://github.com/mozilla/addons-code-manager/issues/1311
