### ISSUE TITLE
Adjust CommentSummaryButton config

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1272]
The UI for https://github.com/mozilla/addons-code-manager/issues/757 will be sharing the new `PopoverButton` component. A few changes to `CommentSummaryButton` are needed for this.

**For QA**: please check for regressions in the *Comment Summary* button and its popover.

**Comment by ioanarusiczki** [comment]
@kumar303 I verified this on dev on Browse and Compare views - looks good to me.
Verified with FF70(Win10).
