### ISSUE TITLE
Browse a version from the compare popover

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1278]
### Describe the problem and steps to reproduce it:

* Log in
* Load any version comparison page

### What happened?

There is no way to switch to browse mode for either of the versions.

### What did you expect to happen?

It should be easy to browse either one of the versions that are being compared.

**Comment by ioanarusiczki** [comment]
@kumar303 
- the `Browse button` is available next to `Old version` and `New version` on the compare pages. Once clicked it will open the browse page of the selected versions in the same tab.
- if I want to see those pages into a different tab I could use the middle mouse button which works for the two `Browse` buttons. 

![the browse pages ](https://user-images.githubusercontent.com/33448286/70132462-f0d5d700-168c-11ea-9116-966f8a5cb938.gif)

- one thing I am not sure about is how the versions should look like once I land to a Browse page.
examples: 
for https://code.addons-dev.allizom.org/en-US/compare/618459/versions/1689854...1689855/?path=manifest.json I choose the old version to be "5.1.4-signed-left-fixed" and new version "5.1.5-signed-right-fixed" which are the latest. 
If I choose to open the browse page for  "5.1.4-signed-left-fixed" and then I check the Compare Versions I'll have 5.1.1 as `old version` and 5.1.4 as the `new one`. 

![versions shown1](https://user-images.githubusercontent.com/33448286/70134582-12d15880-1691-11ea-80c1-a01baddc96c1.gif)

If I choose to open the Browse page for the New version which is "5.1.5-signed-right-fixed" and click again the Compare Versions the old version is no longer "5.1.4-signed-left-fixed". It's 5.1.1 instead. 

![versions shown2](https://user-images.githubusercontent.com/33448286/70134879-92f7be00-1691-11ea-894f-95e1e01a6f15.gif)

**Comment by kumar303** [comment]
>  one thing I am not sure about is how the versions should look like once I land to a Browse page.
>       examples:
>       for https://code.addons-dev.allizom.org/en-US/compare/618459/versions/1689854...1689855/?path=manifest.json I choose the old version to be "5.1.4-signed-left-fixed" and new version "5.1.5-signed-right-fixed" which are the latest.
>       If I choose to open the browse page for  "5.1.4-signed-left-fixed" and then I check the Compare Versions I'll have 5.1.1 as `old version` and 5.1.4 as the `new one`.

I can reproduce this and it is a bit surprising. Can you file an issue? Thanks.

**Comment by kumar303** [comment]
> I can reproduce this and it is a bit surprising. Can you file an issue? Thanks.

Actually, I filed https://github.com/mozilla/addons-code-manager/issues/1306 for it because I have a fix now. Thanks for catching this.

**Comment by ioanarusiczki** [comment]
@kumar303 Alright, then this issue is verified on AMO dev - FF70(Win10).
