### ISSUE TITLE
ENOSPC error: system limit for number of file watchers.

### ISSUE THREAD

**Issue by Kartikeya99** [mozilla/addons-code-manager#128]
### Describe the problem and steps to reproduce it:
Running `yarn dev` the first time, results in tests failing with ENOSPC error: system limit for number of file watchers.

### What did you expect to happen?
The repository to run properly without any tests failing.

### Would you like to solve the problem? 
Yes.

**Comment by Kartikeya99** [comment]
Oh ok got it :+1:

**Comment by willdurand** [comment]
On this basis, I am closing this comment :)
