### ISSUE TITLE
Slow loading indicator isn't accurate when browsing code

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1280]
### Describe the problem and steps to reproduce it:

* Browse a file with 508 lines of code, such as https://code.addons.mozilla.org/en-US/browse/1479936/versions/3176697/?allowSlowPages=true&path=js%2Fbackground.js

### What happened?

The page warns about the file loading slowly

### What did you expect to happen?

The page should not warn about the file loading slowly because it loads quickly

**Comment by ioanarusiczki** [comment]
@kumar303 
For this file with 1187 lines I can still see the warning at the top of the file "This file has been shortened to load faster. View the original file."

https://code.addons-dev.allizom.org/en-US/browse/502724/versions/1541510/?allowSlowPages=false&messageUid=c94a6ffe04da45bfac4a17ebf1dc3557&path=lib%2Fbrowser-polyfill.js

![load faster](https://user-images.githubusercontent.com/33448286/69876054-7b749b80-1273-11ea-94eb-8c74d4e4d717.png)

I could not see your [example](https://github.com/mozilla/addons-code-manager/issues/1280#issue-529431860) for the 508 lines of code. I tried to find it using the add-ons ID on prod but I get a 404 for https://addons.mozilla.org/en-US/firefox/addon/1479936/

**Comment by ioanarusiczki** [comment]
@kumar303 I managed to upload using admin override an add-on with 683 lines of code 
https://code.addons-dev.allizom.org/en-US/browse/618459/versions/1689846/?path=vulcanized-polymer.js#I683
I don't see the message in Browse or Compare View. 
So I'm marking this verified on dev with FF70(Win10).
