### ISSUE TITLE
Long unbroken line of minified code stretches panel too wide

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1284]
### Describe the problem and steps to reproduce it:

Browse this minified diff: https://code.addons-dev.allizom.org/en-US/browse/502868/versions/1688187/?path=src/js/Grammarly-signin.js

### What happened?

The code stretches the panel too wide, which adds horizontal scrollbars. This will obscure linter messages and will break the commenting form (see https://github.com/mozilla/addons-code-manager/issues/997).

Notice the horizontal scrollbar:

<details>
<summary>Example</summary>

<img width="1229" alt="Screenshot 2019-11-27 11 59 20" src="https://user-images.githubusercontent.com/55398/69748624-6500ff80-110e-11ea-8978-b0e381a9d7f0.png">

</details>

### What did you expect to happen?

There should be no horizontal scrollbar. The code should not break the panel width.

### Anything else we should know?

Most cases of this were fixed in https://github.com/mozilla/addons-code-manager/issues/1207 and I can confirm by loading https://code.addons-dev.allizom.org/en-US/browse/503001/versions/1541851/?path=js%2Fcontent-script-combo.js that the fix *did not* regress. There is just something different about the diff linked up above and I'm not sure what it is.

I verified that the layout is broken in Firefox Release, Nightly, and Chrome.

This bug is surprising because `white-space: pre-wrap` should prevent it. It's also surprising because the same diff in Compare mode does not appear broken. I tried matching that layout more precisely and it still didn't fix the bug.

**Comment by ioanarusiczki** [comment]
@mirefly For this particular file, the text is wrapped - the scroll bar is no longer displayed. 
Verified on dev with FF71(Win10). 

![looks good](https://user-images.githubusercontent.com/33448286/71988713-111f2580-3239-11ea-9c88-8c812c855d6b.gif)
