### ISSUE TITLE
Remove prop readOnly in Comment component

### ISSUE THREAD

**Issue by mirefly** [mozilla/addons-code-manager#1286]
`readyOnly` prop in `Comment` needs to be removed, so that the mode of comment only relies on state. https://github.com/mozilla/addons-code-manager/pull/1241#discussion_r348145105

**For QA**: Please check for regressions in the commenting features.

**Comment by ioanarusiczki** [comment]
@mirefly I've been testing on dev with FF71(Win10). - No regressions found. 
- I could add, edit, delete comments on code lines on Browse and Compare pages.
- I've been testing around the feature using the [API](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#drafting-comments) - POST, PATCH, DEL or GET requests work as before.
