### ISSUE TITLE
Rename the `version` property to `versionString`

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1290]
This came up in a recent review, and I wanted to file a follow-up for it. We currently have a [`version`](https://github.com/mozilla/addons-code-manager/blob/master/src/reducers/versions.tsx#L204) property in our `Version` type, which can be a bit confusing. To remove the ambiguity, we should rename the property that contains the "name" of the version (e.g., 1.0.2) from `version` to something else, such as `versionString`.

For QA:

This should not have any observable effect on the app, but we should check for regressions, especially around areas that deal with these version strings. These include:
- The version number(s) displayed in the navbar beside the add-on name.
- The version number(s) that appear in the HTML title of the page.
- The version numbers in the "Compare Versions" pop up.
- The "Version" listed in the "Information" panel.

**Comment by kumar303** [comment]
I suggest adding instructions to QA for regression testing the version string features

**Comment by bobsilverberg** [comment]
I'm going to be doing some work on the `versions` reducer for https://github.com/mozilla/addons-code-manager/issues/1599, and this is a bit annoying, so I'm going to fix this one first.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on dev and I did not find problems with the version numbers.
