### ISSUE TITLE
Deal with `insert-eofnl` and `delete-eofnl` change types

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1291]
This is a follow-up from https://github.com/mozilla/addons-code-manager/issues/989#issuecomment-560448350.

Information that we receive about a diff from the API can include changes with change types of `insert-eofnl` and `delete-eofnl`. We should ensure we are dealing with those appropriately.

At a minimum, we need to update [ChangeType](https://github.com/mozilla/addons-code-manager/blob/2e1316294c5a855e7e8fdbe4f783504f3f58b84f/src/%40types/react-diff-view/index.d.ts#L4) to include these types. We should also disallow commenting on these two types for now, as we don't have a means of differentiating comments on these from comments on other changes which share the same line number.

I also think we should consider excluding these from the diff view entirely. To that end, we should consider the question:
- What value does including these in the diff add?

See https://code.addons-dev.allizom.org/en-US/compare/495710/versions/1541609...1688333/?path=manifest.json for an example of a diff that shows both types of changes.

@wagnerand @kumar303 What are your opinions on excluding these changes from the diff view?

For QA:

When this fix lands it should no longer be possible to comment on the lines that explain changes having to do with newlines at end of file. These appear in the diff view as a two-line comment with an empty line followed by the content "\ No newline at end of file". An example can be found at https://code.addons-dev.allizom.org/en-US/compare/495710/versions/1688329...1688333/?path=manifest.json

**Comment by kumar303** [comment]
Please add steps for how QA can check for regressions after a patch for this issue lands.

As discussed on IRC, I don't think we should hide these changes from the diff view.

**Comment by EnTeQuAk** [comment]
> @wagnerand @kumar303 What are your opinions on excluding these changes from the diff view?

Personal opinion: I think it makes sense to show them but certainly disallow commenting as they don't really add anything valuable to the diff for the reviewer. It may be relevant for the reviewer when files are weirdly shown locally because of newline related problems though (don't ask me for a specific STR here…)

I don't think it hurts to show them though, should be not too frequent I suppose?

**Comment by bobsilverberg** [comment]
> > @wagnerand @kumar303 What are your opinions on excluding these changes from the diff view?
> 
> Personal opinion: I think it makes sense to show them but certainly disallow commenting as they don't really add anything valuable to the diff for the reviewer. It may be relevant for the reviewer when files are weirdly shown locally because of newline related problems though (don't ask me for a specific STR here…)
> 
> I don't think it hurts to show them though, should be not too frequent I suppose?

Thanks Chris. The consensus is to show them. I am going to prevent commenting on them for now (and possibly forever!).

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
I verified on dev and I can no longer comment on the old lines for the [examples](https://github.com/mozilla/addons-code-manager/issues/989#issuecomment-559830210) found.
