### ISSUE TITLE
Ensure `sha256` can be `null`

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-code-manager#1297]
This issue is a follow-up from our discussion in https://github.com/mozilla/addons-server/issues/12920#issuecomment-559821333

This is to track the work needed (and ideally do it) to make sure `sha256` can be `null` in the file-tree.

That essentially means the following from an API point of view (which is WIP):

* `file.entries[].sha256` in [Browse](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-) can be `null` for any file that you're not currently viewing
  * In [Compare](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#get--api-v4-reviewers-addon-(int-addon_id)-versions-(int-version_id)-compare_to-(int-version_id)-) it can already be `null`, e.g when comparing to a deleted file (as stated in the docs)
* For the file you're actively viewing (when requested via `?file=` parameter) the `sha256` hash is *always* set to a correct value

For QA:

Check for regressions on the Browse and Compare page, and in particular with the default file (i.e., when you load Browse or Compare without selecting a file in the file tree). Also check the "Information" panel and ensure that a "SHA256 hash" is displayed in all cases.

**Comment by bobsilverberg** [comment]
Thanks for filing this @EnTeQuAk. I don't think there's anything currently in the app that will be affected by this, but it would be nice to keep the types in sync, so I'll look into addressing this issue ASAP.

**Comment by EnTeQuAk** [comment]
Thanks, I wasn't sure if there are actual changes needed - but at the very least we should make sure it works - and that's what this issue is about.

Thanks!

**Comment by ioanarusiczki** [comment]
@EnTeQuAk @bobsilverberg 
I don't see issues here. SHA256 hash is displayed on all files I've checked on. 
verified on dev with FF70(Win10).
