### ISSUE TITLE
Double check code for line number and commenting on diffs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1299]
This is a follow-up to https://github.com/mozilla/addons-code-manager/issues/989. The code that determines the line number for a change uses [`change.lineNumber`](https://github.com/mozilla/addons-code-manager/blob/76e1e8e28135d30832fd5e312b57da32e356f005/src/components/DiffView/index.tsx#L200), but that is a bit opaque, as changes actually have `old_line_number` and `new_line_number`. This issue is about investigating the value of `change.lineNumber` for both normal and insert changes and verifying that the value used is what we need it to be.

Note also that part of the impetus for this audit is the issue reported at https://github.com/mozilla/addons-server/issues/13024. We want to make sure that the code currently in place will not send invalid data to the API.

**Comment by bobsilverberg** [comment]
The data that is returned from the API for a diff includes the following:
- for a `normal` change, `old_line_number` and `new_line_number` are the same.
- for a `delete`, `old_line_number` is the line number of the line that was deleted, and `new_line_number` is `-1`.
- for an `insert`, `old_line_number` is `-1` and `new_line_number` is the line number of the line that was inserted.

Based on that, if we want to choose a particular value to use for `lineNumber` for a change:
- for a `normal` change, we can use either `old_line_number` or `new_line_number`.
- for a `delete`, we should use `old_line_number`.
- for an `insert`, we should use `new_line_number`.

And that is exactly what we are doing. This translation between data from the API (which is in the form of an [`ExternalChange`](https://github.com/mozilla/addons-code-manager/blob/2019.12.05/src/reducers/versions.tsx#L108-L113)) and our internal format (which is in the form of a [`ChangeInfo`](https://github.com/mozilla/addons-code-manager/blob/2019.12.05/src/%40types/react-diff-view/index.d.ts#L6-L15)), is done via [`createInternalChangeInfo`](https://github.com/mozilla/addons-code-manager/blob/2019.12.05/src/reducers/versions.tsx#L886-L902), and it uses the exact logic mentioned above.

Therefore, I think we can close this in confidence that we are doing the right thing.

**Comment by kumar303** [comment]
Great, thanks for looking into it. I put it back in next week's milestone just to track it as a "thing you spent time on," which is helpful for visibility.

**Comment by bobsilverberg** [comment]
After doing all that research, I still somehow got it wrong. It turns out that `normal` changes do not always have the same value for `old_line_number` and `new_line_number`. If, for example, a line is added to the top of a file, line 2, which is unchanged and therefore `normal`, will have an `old_line_number` of `1` and a `new_line_number` of `2`. But we are actually using `old_line_number` for `normal` changes. I believe this is the cause of https://github.com/mozilla/addons-code-manager/issues/877.

I will be addressing this in a patch for #877
