### ISSUE TITLE
Add pino as logging library

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#13]
We want to reuse [Pino](https://getpino.io/) as logging layer since we have it in addons-frontend and we can reuse [pino-mozlog](https://github.com/mozilla/pino-mozlog) to format logs as per Mozlog v2.

**Comment by bobsilverberg** [comment]
Taking this as it's a higher priority than the other issues I assigned to myself.

**Comment by bobsilverberg** [comment]
Because we won't need a server, I don't think we need Pino either. Closing this, but feel free to re-open it if I got that wrong.

**Comment by willdurand** [comment]
that's correct, thanks for closing this bug
