### ISSUE TITLE
Version chooser does not preserve choices after browsing

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1306]
### Describe the problem and steps to reproduce it:

- Go to https://code.addons-dev.allizom.org/en-US/compare/618459/versions/1689854...1689855/
- Open the *Compare Versions* popover
- Note the values for *Old version* and *New version*
- Click *Browse* next to `5.1.4-signed-left-fixed`
- Open the *Compare Versions* popover again

### What happened?

The values for *Old version* and *New version* were reset.

### What did you expect to happen?

These values should remain just as they were before clicking *Browse*

### Anything else we should know?

follow up to https://github.com/mozilla/addons-code-manager/issues/1278

**Comment by ioanarusiczki** [comment]
@kumar303 This issue is fixed. 
Verified on dev with FF70(Win10). 

![the versions are mentained](https://user-images.githubusercontent.com/33448286/70310378-2955ec00-1818-11ea-82f0-f82fc4d53910.gif)
