### ISSUE TITLE
Development proxy should respond to any incoming request

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#131]
In development mode, the server does not inject the auth token when the URL is anything but `/`. We should change this behavior (in production mode, the behavior is correct).

We should always serve `index.html` with the auth token injected, no matter which URL is used (it is a SPA so we send all URLs to the same page).

**Comment by kumar303** [comment]
> in production mode, the behavior is correct

This is because the prod handler already responds to requests for [all paths](https://github.com/mozilla/addons-code-manager/blob/2962560cb6569d5aaa0982ecd8ceaadcc68d5ee0/src/server/index.tsx#L105).
