### ISSUE TITLE
Error message is received when clicking below the code lines from the code overview 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1311]
STR:
1. Load a compare page https://code.addons-dev.allizom.org/en-US/compare/495710/versions/1541610...1688369/?path=mozilla-recommendation.json
2. Click in the code overview displayed on the right side of the screen in the area where there's no code lines (below the code lines)
3. Observe the screen

Expected result:
Nothing happens.

Actual result:
Oops, something went wrong.

Notes:
Workaround: refreshing page will reload the page correctly. 
It is not reproducible with Browse pages. 

![error message](https://user-images.githubusercontent.com/33448286/70218671-17a71280-174c-11ea-99b4-4605096368df.gif)

**Comment by ioanarusiczki** [comment]
This was observed before https://github.com/mozilla/addons-code-manager/issues/896#issuecomment-512727219
Meaning it is not a regression caused by https://github.com/mozilla/addons-code-manager/issues/1266 as I initially thought.

**Comment by willdurand** [comment]
I think this sentry issue is related: [ADDONS-CODE-MANAGER-STAGE-Z](https://sentry.prod.mozaws.net/operations/addons-code-manager-stage/issues/6799745/)

**Comment by willdurand** [comment]
This one too (I think): [ADDONS-CODE-MANAGER-STAGE-10](https://sentry.prod.mozaws.net/operations/addons-code-manager-stage/issues/6799746/)

**Comment by kumar303** [comment]
This is something we should fix (it might be a quick fix, too) but I think a reviewer would only click on the blank part of the overview by mistake so it's probably not such a critical bug.

**Comment by ioanarusiczki** [comment]
@willdurand This issue is no longer reproducible on AMO dev with FF71(Win10). 

![no error2](https://user-images.githubusercontent.com/33448286/71360915-0c504580-259a-11ea-8da3-936d0c296479.gif)
