### ISSUE TITLE
File paths are not preserved when changing version comparisons

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#1313]
### Describe the problem and steps to reproduce it:

1. Go to a Compare page like https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1688183...1688187/
2. Click on `src/css/modal.css` which loads https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1688183...1688187/?path=src%2Fcss%2Fmodal.css
3. Click *Compare Versions*, change the old version to `8.842.2007` and click *Compare*

### What happened?

When the comparison loads, the file path is `manifest.json`.

### What did you expect to happen?

The file path should be `modal.css`

### Anything else we should know?

This is a regression of https://github.com/mozilla/addons-code-manager/issues/777 and git bisect says it was introduced in https://github.com/mozilla/addons-code-manager/commit/87d1f9df6767ad1640c41727bfd29ced474149a4

**Comment by kumar303** [comment]
Hi @mirefly. I stumbled on this when I was reviewing https://github.com/mozilla/addons-code-manager/pull/1310 -- sorry I didn't catch it when reviewing https://github.com/mozilla/addons-code-manager/pull/1259 . This issue probably isn't high priority but could you take a look at some point, maybe after other high priority issues?

**Comment by mirefly** [comment]
The `selectedPath` is reset when [dispatching `loadVersionInfo` for a base version.](https://github.com/mozilla/addons-code-manager/blob/30fd73af64151170c8828caa24ff34550f7e9c0b/src/reducers/versions.tsx#L817)  I created a PR #1317.

**Comment by ioanarusiczki** [comment]
@mirefly I verified on dev with FF71(Win10) and I could not reproduce this scenario or when I change the new version or both: old and new version.
I didn't find it reproducible on stage either. 


![not reproducible](https://user-images.githubusercontent.com/33448286/70906355-d5fd4e00-200e-11ea-8d74-92390faef358.gif)
