### ISSUE TITLE
Consider making ChangeType an enum

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1322]
This is a follow-up to https://github.com/mozilla/addons-code-manager/pull/1294#discussion_r354973025.

Because it is used in a number of places, and we are hardcoding its values as strings, it might be nicer to turn [`ChangeType`](https://github.com/mozilla/addons-code-manager/blob/49eed2c2f5b635b28bc69991d545514a0f1771e7/src/%40types/react-diff-view/index.d.ts#L4) into an [`enum`](https://www.typescriptlang.org/docs/handbook/enums.html).

**Comment by ioanarusiczki** [comment]
@bobsilverberg @mirefly 
I verified the compare pages with FF72(Win10). 
I did not notice issues but I must ask about these behaviors reproducible for both Browse and Compare pages. Please let me know if these are expected: 

I load in a tab  a file with the diff shortened and then I click on `Show the original diff`. If I close the tab and reload the page in a new tab I will see the `Shorten the diff` red message at the top of the page. It's the same if a simply open a new tab and load the file. So, until I don't click back `shorten the diff` the file will load the original diff (or files).

![view the shortened file](https://user-images.githubusercontent.com/33448286/72736534-8e865680-3ba6-11ea-846a-bff0e6dba5e7.gif)


Navigating through the file tree I've noticed that when the original diff of a file is opened all the other files with 3000+ chars will also load the original versions. 

![the original diffs](https://user-images.githubusercontent.com/33448286/72735635-e02de180-3ba4-11ea-94b5-4d513315103e.gif)

**Comment by bobsilverberg** [comment]
@ioanarusiczki I'm not sure if this addresses your question or not, but here's how the shortening of diffs works:

There's a URL variable called `allowSlowPages` which controls whether long diffs will be shortened or not. 

So when you open a new tab and paste in a URL, if the URL contains that parameter then it will be carried over to the new tab. If it does not then the value will be reset. By default for the compare page, `allowSlowPages` is `true`. 

This value is also carried from file to file, so in answer to your second question, yes, once you set this value for one file, it will be used for every file until you change its value.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Thanks for the information. 

It created some confusion for me while testing, because Browse and Compare views don't have the same default values for `allowSlowPages`. 

If I load a file in Browse view - the default for `allowSlowPages` is false: this is why I will see the files truncated. 

From a Browse view using the Compare Versions I went to a diff for the same file and in Compare view because the default for `allowSlowPages` is true I will see the content of the entire page and have the `shorten the diff` option.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I filed an issue which is reproducible agai - https://github.com/mozilla/addons-code-manager/issues/1405 but I can't tell if it's a regression.
