### ISSUE TITLE
Diff is not loading for removed files

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1327]
STR:
1. Load https://code.addons-dev.allizom.org/en-US/compare/7560/versions/1252898...1510628/ for
 old version `3.3.6` and new version is `5.1.6`
2. Observe the page 

Expected result:
The Diff loads without errors.

Actual result:
An error is displayed. 

![69337214-0698d480-0c69-11ea-9efa-7339a8c81c95](https://user-images.githubusercontent.com/33448286/70519674-fb88e400-1b44-11ea-9333-33aefda55b62.gif)

It's reproducible on dev with FF70(Win10).

**Comment by mirefly** [comment]
The app throws an error at 
https://github.com/mozilla/addons-code-manager/blob/71ef832f2d8a6644b5bedfb1e5ef8c467b8aef28/src/reducers/fileTree.tsx#L115

The file.entries returned from API is not a complete file tree as expected. I guess it might be better to fix this issue in addons-server. I filed https://github.com/mozilla/addons-server/issues/13092

**Comment by bobsilverberg** [comment]
@ioanarusiczki We think this is now fixed. Could you please verify?

**Comment by ioanarusiczki** [comment]
@bobsilverberg I've been looking at this add-on and I see this has some history. Lots of legacy versions and they're really old so as far as I know for these add-ons some files won't be displayed with the new file viewer because of the git extraction.
To avoid that, I uploaded 3 old legacy versions : 3.3.6, 3.3.7 (which is 3.3.6 only the version number is modified) and 4.2.2 (which is legacy but differs from the other two meaning it has  added files and removed files compared to 3.3.6 or 3.3.7) 
Version 5.1.6 is an extension with manifest.json.

This is the add-on 
https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/webmail-ad-blocker12

Comparing 3.3.6 with 5.1.6 - removed files for the new version won't load. The case I initially files the [issue](https://github.com/mozilla/addons-code-manager/issues/1327#issue-535621803) for is no longer reproducible.

Same when comparing 3.3.6 or 3.3.7 with 4.2.2 - the removed files are not loading. 

![will not load](https://user-images.githubusercontent.com/33448286/79851240-b6679f00-83cd-11ea-8d8c-fd2a3415a014.gif)

**Comment by ioanarusiczki** [comment]
@bobsilverberg I changed the name of the issue because it did not reflect the problem. 

The diff is not loading for files which have been removed in the current version. 

https://code.addons-dev.allizom.org/en-US/compare/7560/versions/1519488...1691150/?path=harness-options.json

**Comment by bobsilverberg** [comment]
I'm pretty sure this will be fixed as a side effect of fixing https://github.com/mozilla/addons-code-manager/issues/1599, but there's also a pretty simple fix for this right now. Rather than landing a patch that just fixes this for now, I'm going to keep working on https://github.com/mozilla/addons-code-manager/issues/1599, which I've been working on for quite some time, as it's quite large.

**Comment by bobsilverberg** [comment]
FWIW, here's a patch that will fix this, but I'd rather not spend the time updating tests for this patch as it will become obsolete with the landing of #1599.

```diff
diff --git a/src/pages/Compare/index.tsx b/src/pages/Compare/index.tsx
index e0defd7..a67e333 100644
--- a/src/pages/Compare/index.tsx
+++ b/src/pages/Compare/index.tsx
@@ -286,10 +286,13 @@ export class CompareBase extends React.Component<Props> {
           onSelectFile={this.viewVersionFile}
           version={version}
         >
-          {version && versionFile && compareInfo ? (
+          {version &&
+          entryStatusMap &&
+          (versionFile || entryStatusMap[version.selectedPath] === 'D') &&
+          compareInfo ? (
             <DiffView
               diff={compareInfo.diff}
-              isMinified={versionFile.isMinified}
+              isMinified={Boolean(versionFile && versionFile.isMinified)}
               // This key resets scrollbars between files
               key={`${version.id}:${path}`}
               mimeType={compareInfo.mimeType}
```

**Comment by ioanarusiczki** [comment]
@bobsilverberg Ok, I'll take a look at this when 1599 lands on dev.

**Comment by ioanarusiczki** [comment]
@bobsilverberg The issue is no longer reproducible on code.addons-dev.allizom.org - FF78(Win10).
