### ISSUE TITLE
Do not highlight code in a truncated file

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1328]
This came up in discussions around #1086.

It seems like there is little value in highlighting code in a file that is also being truncated. This would lead to the conclusion that any time we are truncating a file we should also not highlight the code. That might give us a bit of a quick win in terms of performance in those cases where we are currently truncating and also highlighting.

@wagnerand Do you agree with that approach?

For QA:

After this change lands, any screen that truncates a file (both the Browse and Compare pages) should also disable syntax highlighting. Currently a file that has been truncated does not disable syntax highlighting on the Browse page, and only a file with 3000+ lines, or with a line with a length greater than 700, will disable syntax highlighting on the Compare page.

**Comment by wagnerand** [comment]
Yes, let's try this and see if:
* reviewers can live with it
* it gives us a high enough performance gain

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on dev , I tried for files which have less than 3000 code lines and then for 3000+. In both cases the syntax is not highlighted until I load the original file (for browse and compare pages). 

The shortened files won't be highlighted.

![not highlighted](https://user-images.githubusercontent.com/33448286/70812308-0d31ec00-1dd0-11ea-9d65-05de13d043e6.gif)
