### ISSUE TITLE
Show the linter messages instead of the top of the code line

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1332]
Followup for https://github.com/mozilla/addons-code-manager/issues/877

STR:
1. Example 1 : from https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1541685...1688183/?messageUid=3ca54c0b56d4499492c2450023bdc44b&path=src%2Fjs%2FGrammarly-popup.js press `a` scroll down the page then press `a` again

2. Example 2: https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1541685...1688183/?messageUid=c58e78979dc4490f9d77a78b6b6a18be&path=src%2Fjs%2Feditor-popup.js#N2
and press `z`  scroll to the linter message then press `z` again and observe the screen

Expected result: 
The linter warning is displayed.

Actual result:
The code line is available. 

Notes:
I don't know if the second scenario can be fixed , I've noticed that it is reproducible when I click on the code overview too - the orange lines which contain the linter messages. 

![messages](https://user-images.githubusercontent.com/33448286/70610398-2e49df80-1c0c-11ea-8c3e-203ca77d1345.gif)

**Comment by bobsilverberg** [comment]
It looks like this is only an issue with really long lines of code, which are generally non-reviewable, so marking this as WONTFIX.
