### ISSUE TITLE
Wait until we load the linter messages to render the code in `CodeView`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#1334]
I know this sounds counter-productive but when profiling [a browse page with a large file](https://code.addons-dev.allizom.org/en-US/browse/494431/versions/1532144/?allowSlowPages=true&path=lib%2Fadblockplus.js), we can clearly see that we render `CodeView` twice:

1. when we get the version data
2. when we get the linter messages

The problem is that rendering `CodeView` takes time (~8s per render in my case).

If we render the actual code only when we have all the data we need, then we will render the `CodeView` only once and that speeds up the page load.

Sketch of patch:

```diff
diff --git a/src/components/CodeView/index.tsx b/src/components/CodeView/index.tsx
index b39d3a8..6ccb11a 100644
--- a/src/components/CodeView/index.tsx
+++ b/src/components/CodeView/index.tsx
@@ -83,7 +83,7 @@ export class CodeViewBase extends React.Component<Props> {
     enableCommenting: process.env.REACT_APP_ENABLE_COMMENTING === 'true',
   };
 
-  renderWithLinterInfo = ({ selectedMessageMap }: LinterProviderInfo) => {
+  renderWithLinterInfo = ({ messageMap, selectedMessageMap }: LinterProviderInfo) => {
     const {
       _scrollToSelectedLine,
       _slowLoadingLineCount,
@@ -94,6 +94,10 @@ export class CodeViewBase extends React.Component<Props> {
       version,
     } = this.props;
 
+    if (!messageMap) {
+      return (<p>still loading</p>);
+    }
+
     const language = getLanguageFromMimeType(mimeType);
     let codeLines = getLines(content);
     let codeWasTrimmed = false;
```

**Comment by bobsilverberg** [comment]
This seems like a good idea. I guess one question is whether, with a smaller file, it seems like performance is worse because it takes longer to see the code (because we are waiting for the messages too). Do you think that is likely to happen, @willdurand?

**Comment by willdurand** [comment]
> This seems like a good idea. I guess one question is whether, with a smaller file, it seems like performance is worse because it takes longer to see the code (because we are waiting for the messages too). Do you think that is likely to happen, @willdurand?

Indeed, I have the same concern. Given that we would have the version content, we could likely decide whether to render the code or not depending on how big the content is, maybe? (assuming that not rendering the code without linter messages feels slow for small files).

**Comment by willdurand** [comment]
@bobsilverberg I looked at the code again. We have the logic for the slow alert in `CodeView` so we can only wait for linter messages when we detect a large file.

**Comment by willdurand** [comment]
According to my local experiments, doing this speeds up a browse page a lot. In -dev, a [slow page](https://code.addons-dev.allizom.org/en-US/browse/494431/versions/1532144/?allowSlowPages=true&path=lib%2Fadblockplus.js) takes above 8s to load for me (usually between 8 and 11s).

With a simple patch, a local dev production build loads the page in less than 5s all the time.

**Comment by willdurand** [comment]
I don't think we should try to optimize for the small file scenario though. It will be simpler if everything follows the same path. Loading a small file won't by any slower, we'll simply see the "loading linter info" message before getting the code.
