### ISSUE TITLE
Disable highlighting in both Compare and Browse mode

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1337]
This is meant to address the issue described in #1086 

We currently disable highlighting both for long files, and also for files with long lines, in Compare mode. Files with long lines are also slow to load in Browse mode, and some quick and unscientific testing revealed that disabling highlighting helped greatly with this issue.

Therefore we should take the code we have for detecting files which should not be highlighted and share it between both Browse and Compare.

For QA:

When this change lands, files with long line lengths (greater than 500 chars) should not be highlighted either in Browse or Compare mode.

**Comment by ioanarusiczki** [comment]
@bobsilverberg A code line with a length greater than 500 chars won't be highlighted anymore. 
I tested for a line with a length of 501 chars - Browse and Compare pages:

https://code.addons-dev.allizom.org/en-US/browse/618525/versions/1689955/?path=src%2Faction%2Findex.html
https://code.addons-dev.allizom.org/en-US/compare/618525/versions/1689955...1689956/?path=src%2Faction%2Findex.html

how 500 chars look like

![500](https://user-images.githubusercontent.com/33448286/71520538-50f31e00-28c5-11ea-8b97-42525017bf31.png)

and 501 chars 

![501](https://user-images.githubusercontent.com/33448286/71520560-68320b80-28c5-11ea-9860-ef578e659005.png)
