### ISSUE TITLE
`fetchVersionFile()` should early return when a file is already being loaded

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#1338]
See the discussion in https://github.com/mozilla/addons-code-manager/issues/1320

---

When `fetchVersion()` loads the version info, a re-render happens and the `Browse` component executes `fetchVersionFile()` because there is no `file` yet. That is because the thunk loads the version info in the state first, and then it loads the file. The re-render happens between these two steps.

We should check the value of `versionFilesLoading` in `fetchVersionFile()` to avoid this problem.

Expected result: instead of making two API calls for the same version (see the blue rectangles in the screenshot below), we will fetch the version only once.

<img width="1986" alt="70338792-2e646c80-1813-11ea-833c-062a5b7c51c9" src="https://user-images.githubusercontent.com/217628/70806330-5cb9ed00-1dbb-11ea-871b-52516ca6d3ad.png">

**For QA:** we should only make one API request to fetch a version with the current file.

**Comment by ioanarusiczki** [comment]
@willdurand I verified on dev with FF71(Win10) and I see only one API request for the current file. 

![only once](https://user-images.githubusercontent.com/33448286/71408451-f8165200-2646-11ea-8fa4-f4b3c3c220c5.png)
