### ISSUE TITLE
Ability to search through all add-on files

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1343]
This is based on feedback from the meeting we had today to discuss the code manager.

There was a desire expressed to be able to search for a word across all files in an add-on. An example would be a function that is defined in one file, but called in a different file. Exactly how this would work, and what the UX would be like was not discussed.

More discussion about this feature is needed.

**Comment by bobsilverberg** [comment]
We discussed this a bit and it sounds like it would require an API that the client could call and the server would complete the search. That sounds like it could be quite complicated.

@diox Can you share any thoughts you might have about this?

**Comment by bobsilverberg** [comment]
One approach could be to use Git for this, as opposed to using an index of the contents of the version.

**Comment by diox** [comment]
Looked into what `pygit` provides briefly and it does expose `git blame` info, which may be useful once you found something to figure out which version added it, but it doesn't help us find patterns in files in the repos. We'll have to implement it ourselves (maybe leveraging `yara` ?)
