### ISSUE TITLE
TypeError: _codeCanBeHighlighted is not a function

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#1351]
### Describe the problem and steps to reproduce it:

1. Open https://code.addons-dev.allizom.org/en-US/compare/502955/versions/1541798...1541798/?path=popup%2Fpopup.js

### What happened?

```
Oops, something went wrong.
```

In local dev, the error is:

```
TypeError: _codeCanBeHighlighted is not a function
```

### What did you expect to happen?

No error.

### Anything else we should know?

It looks like a compilation error (webpack related) because the source code seems correct. The patch that introduced this "issue" is: https://github.com/mozilla/addons-code-manager/pull/1339

**Comment by ioanarusiczki** [comment]
@willdurand I could not reproduce this issue on dev with FF71(Win10). 

![no error](https://user-images.githubusercontent.com/33448286/71360034-1d4b8780-2597-11ea-8a12-b04d403f553a.gif)
