### ISSUE TITLE
Disable `@typescript-eslint/camelcase` ESLint rule

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#1353]
Let's disable `@typescript-eslint/camelcase`, it adds very little value and it is annoying because we always have to disable it anyway.

**Comment by bobsilverberg** [comment]
I agree it seems annoying, and we do end up disabling it when needed, but will we be happy if non-camelcase vars start sneaking into the code? Does it mean we'll have to look out for that in code reviews? Those are probably not things we really need to worry about, but I think we should ask ourselves these questions before disabling a rule that we actually do want enforced 99% of the time.

**Comment by willdurand** [comment]
Will this rule prevent errors?

When we disable this rule, we end up disabling it for the entire file usually because having inline comments everywhere is madness, so I dunno. I think this rule is not helpful.

To me, the worse case scenario is: a new contributor submits a patch and one of us misses a newly added variable containing an underscore during a code review.

**Comment by bobsilverberg** [comment]
> Will this rule prevent errors?
> 
> When we disable this rule, we end up disabling it for the entire file usually because having inline comments everywhere is madness, so I dunno. I think this rule is not helpful.
> 
> To me, the worse case scenario is: a new contributor submits a patch and one of us misses a newly added variable containing an underscore during a code review.

I agree, that's the danger we face with this change. I also agree that the risk does not outweigh the benefit of disabling the rule. I wasn't trying to say we shouldn't do it, just raising some questions, which I believe have been addressed.

**Comment by bobsilverberg** [comment]
@willdurand Were you going to propose a patch for this? I'm about to land something that would need the comment, so patching it first would save adding that comment.

**Comment by willdurand** [comment]
> @willdurand Were you going to propose a patch for this? I'm about to land something that would need the comment, so patching it first would save adding that comment.

ha, I haven't started yet :/ Do not wait for me then, I'll propose a patch that remove existing comments.

**Comment by bobsilverberg** [comment]
I can take this on if you want @willdurand. Would we be changing this for just code manager, or should this be an update to eslint-config-amo?

**Comment by willdurand** [comment]
Updating the shared config sounds good to me

**Comment by bobsilverberg** [comment]
Moved to https://github.com/mozilla/eslint-config-amo/issues/220
