### ISSUE TITLE
Truncate file content based on number of characters in the Compare View

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1366]
This is being tackled for the Browse view via #1347, but we also have performance issues for large files in the Compare view. For example, #402 describes a situation in which loading a compare view of a minified diff is very slow. It is expected that the same solution being implemented for #1347 should work for the compare view as well, so we should apply similar changes to the `DiffView` component.

Those changes are that, rather than basing file truncation on number of lines in the file, it should be based on a total number of characters, and if a file is being truncated, the contents should include an indication that the file was truncated (e.g., a comment added by code-manager), and a button should be available to view the whole file. The latter part is already implemented via `SlowPageAlert`.

The suggested limit for number of characters is 3000. If any file is larger than that then only the first 2000 characters of the file will be shown.

Note also that this change will remove the code that disables syntax highlighting if the file has already been trimmed. It is believed that after trimming files will no longer need to have syntax highlighting disabled.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I've noticed the following for the compare view:
- the first 2000 chars are not visible - there's the `diff truncated by code-manager` message available.  Should those be visible (as it is for the Browse view). 
- the highlighting is still disabled in compare view. - perhaps this is not expected right now? I find it alright - it will display the file without delays. 

![compare view](https://user-images.githubusercontent.com/33448286/72269172-ced85880-362b-11ea-86df-491657e40627.gif)

**Comment by bobsilverberg** [comment]
@ioanarusiczki Hmm, I see now that if there is only one line in the file, that the entire line will be replaced with the `/* diff truncated by code-manager */` message. That is because the code is accumulating changes until it hits the limit of 3000 characters, at which point it throws away the last change and replaces it with one that reads `/* diff truncated by code-manager */`. Therefore, if there is only one change, it replaces it with that message and nothing from the original diff is displayed to the user. 

This is potentially okay, as a truncated diff will generally provide little useful information anyway, but we may want to change the logic so that we show just the first 2000 characters of the single line if only one line exists in the diff.

This will complicate the code, but might be worthwhile.

So this behaviour is expected, but also possibly not optimal. Could you please open a new issue for this behaviour?

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
- I filed the issue discussed above here https://github.com/mozilla/addons-code-manager/issues/1391

I did some more testing and noticed that:
- for pages with more than one code line and one of the lines is  also pretty long, the page is truncated and chars are available but not the same way as in the Browse view which follows the 2000 char rule. 

Examples:
https://code.addons-dev.allizom.org/en-US/compare/618525/versions/1689955...1689956/?allowSlowPages=true&path=src%2Fcontribute%2Fcontribute.bundle.js -> 537 chars visible
https://code.addons-dev.allizom.org/en-US/compare/618541/versions/1689973...1689975/?allowSlowPages=false&path=src%2Fcss%2FGrammarly-popup.styles.css -> 82 chars visible

- where one long code line is available the highlighting is still disabled (looks like the compare pages still have this property kept when the line is longer than 500 chars). 

An example - the original diff will show the lines not being highlighted
https://code.addons-dev.allizom.org/en-US/compare/618541/versions/1689973...1689975/?allowSlowPages=false&path=src%2Fcss%2FGrammarly-popup.styles.css
https://code.addons-dev.allizom.org/en-US/compare/618525/versions/1689954...1689955/?allowSlowPages=false&path=src%2Fbackground%2Fbackground.bundle.js

- the pages with many code lines are truncated the same way as in the browse pages (truncate after ~2000 chars). Also in these cases the highlighting is enabled.

Examples:
https://code.addons-dev.allizom.org/en-US/compare/618525/versions/1689955...1689956/?allowSlowPages=false&path=src%2Fcontribute%2Fstyle.bundle.css
https://code.addons-dev.allizom.org/en-US/compare/618541/versions/1689973...1689975/?allowSlowPages=false&path=src%2Fcss%2FGrammarly-signin.styles.css

**Comment by bobsilverberg** [comment]
> @bobsilverberg
> 
> * I filed the issue discussed above here #1391
> 

Thank you.

> 
> I did some more testing and noticed that:
> 
> * for pages with more than one code line and one of the lines is  also pretty long, the page is truncated and chars are available but not the same way as in the Browse view which follows the 2000 char rule.
> 
> Examples:
> [code.addons-dev.allizom.org/en-US/compare/618525/versions/1689955...1689956/?allowSlowPages=true&path=src%2Fcontribute%2Fcontribute.bundle.js](https://code.addons-dev.allizom.org/en-US/compare/618525/versions/1689955...1689956/?allowSlowPages=true&path=src%2Fcontribute%2Fcontribute.bundle.js) -> 537 chars visible
> [code.addons-dev.allizom.org/en-US/compare/618541/versions/1689973...1689975/?allowSlowPages=false&path=src%2Fcss%2FGrammarly-popup.styles.css](https://code.addons-dev.allizom.org/en-US/compare/618541/versions/1689973...1689975/?allowSlowPages=false&path=src%2Fcss%2FGrammarly-popup.styles.css) -> 82 chars visible
> 

This is expected. The logic for how the code is truncated is different between the Browse and Compare pages. As discussed at https://github.com/mozilla/addons-code-manager/issues/1366#issuecomment-573732368, for the Compare page we take all of the changes (i.e., individual lines), until we have encountered 2000 characters of content (i.e., the total length of all the lines). Once we hit that, we throw away the last change/line, and replace it with a line that reads `/* diff truncated by code-manager */`. So, depending on how long the line that we throw away is, the total content could be significantly less than 2000 characters.

> * where one long code line is available the highlighting is still disabled (looks like the compare pages still have this property kept when the line is longer than 500 chars). 
> 
> An example - the original diff will show the lines not being highlighted
> [code.addons-dev.allizom.org/en-US/compare/618541/versions/1689973...1689975/?allowSlowPages=false&path=src%2Fcss%2FGrammarly-popup.styles.css](https://code.addons-dev.allizom.org/en-US/compare/618541/versions/1689973...1689975/?allowSlowPages=false&path=src%2Fcss%2FGrammarly-popup.styles.css)
> [code.addons-dev.allizom.org/en-US/compare/618525/versions/1689954...1689955/?allowSlowPages=false&path=src%2Fbackground%2Fbackground.bundle.js](https://code.addons-dev.allizom.org/en-US/compare/618525/versions/1689954...1689955/?allowSlowPages=false&path=src%2Fbackground%2Fbackground.bundle.js)
> 

Yes, we kept this logic, for now. We may or may not turn that off.

> * the pages with many code lines are truncated the same way as in the browse pages (truncate after ~2000 chars). Also in these cases the highlighting is enabled.
> 
> Examples:
> [code.addons-dev.allizom.org/en-US/compare/618525/versions/1689955...1689956/?allowSlowPages=false&path=src%2Fcontribute%2Fstyle.bundle.css](https://code.addons-dev.allizom.org/en-US/compare/618525/versions/1689955...1689956/?allowSlowPages=false&path=src%2Fcontribute%2Fstyle.bundle.css)
> [code.addons-dev.allizom.org/en-US/compare/618541/versions/1689973...1689975/?allowSlowPages=false&path=src%2Fcss%2FGrammarly-signin.styles.css](https://code.addons-dev.allizom.org/en-US/compare/618541/versions/1689973...1689975/?allowSlowPages=false&path=src%2Fcss%2FGrammarly-signin.styles.css)

That is expected.
