### ISSUE TITLE
stmux does not seem to kill all the child processes anymore

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#1367]
### Describe the problem and steps to reproduce it:

1. Run `yarn dev`
2. Press <kbd>ctrl + a</kbd> <kbd>k</kbd>

### What happened?

Child processes are not killed. If you try to re-run `yarn dev`, the server will complain about the `port` being in use.

### What did you expect to happen?

Child processes are killed. No error.

**Comment by mirefly** [comment]
I could not reproduce this in the latest version 99c00f4  (in Debian 9).

**Comment by willdurand** [comment]
> I could not reproduce this in the latest version [99c00f4](https://github.com/mozilla/addons-code-manager/commit/99c00f4395e2e1176457b94b227e9471ab0ad8f5) (in Debian 9).

ha, that's interesting. thanks for the feedback!

**Comment by muffinresearch** [comment]
@willdurand can you still repro?

**Comment by bobsilverberg** [comment]
I can still reproduce this. It would be nice to fix it if we can.
