### ISSUE TITLE
Long lines of code do not wrap in Browse

### ISSUE THREAD

**Issue by mirefly** [mozilla/addons-code-manager#1375]
This looks like a regression of #1207. After some investigation, I think it is caused by CSS selectors having the equal specificity. 190615a exposed this bug.
STR: https://code.addons-dev.allizom.org/en-US/browse/494431/versions/1532144/?path=jquery-ui%2Fjs%2Fjquery-1.7.1.min.js
![image](https://user-images.githubusercontent.com/4984681/71549636-f10c7e00-297d-11ea-84f4-8d96edc1c6be.png)

Expected: The long lines are wrapped and the comment box fit the viewport.

**Comment by ioanarusiczki** [comment]
@mirefly I verified this issue on dev and it is no longer reproducible. - FF71(Win10). 

![wrapped ](https://user-images.githubusercontent.com/33448286/71893708-1440e580-3155-11ea-876b-d5002a3b70d8.gif)
