### ISSUE TITLE
The side panels are not updated when navigating back to a previously opened file in the compare view

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#1377]
Follow up for #932 

### Describe the problem and steps to reproduce it:
1. Open a compare page - see https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1541685...1688187/?path=manifest.json
2. Select another file from the file tree and wait for it to be loaded
3. Using the browser back button, navigate to the previously opened file
4. Observe the file highlighted in the file tree

### What happened?
The file selected at Step 2 remains highlighted

### What did you expect to happen?
The file tree should highlight the file being loaded
### Anything else we should know?
- the Code Overview is not updated either in this scenario which means this issue is affecting both side panels 
- reproduced on -dev and stage

![2020-01-03_14-16-43](https://user-images.githubusercontent.com/31961530/71723047-db8ecc80-2e33-11ea-8b3e-bc66b04dcf6f.gif)

**Comment by bobsilverberg** [comment]
@mirefly This looks similar to https://github.com/mozilla/addons-code-manager/issues/932, which you recently fixed. Do you want to take a look at this and see if a similar fix would work here?

**Comment by mirefly** [comment]
@bobsilverberg Yes, a similar fix probably works. Let me prepare a PR for this issue.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![2020-01-10_17-25-34](https://user-images.githubusercontent.com/31961530/72164414-51fc7300-33ce-11ea-9643-e9c42e0f8734.gif)
