### ISSUE TITLE
Code lines with more than 500 chars are highlighted in Browse view

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1389]
@bobsilverberg  

This looks like a regression because I did not find it reproducible on stage. 
The issue https://github.com/mozilla/addons-code-manager/issues/1337 introduced the disable of highlighting in Browse and Compare views for code lines with a greater length than 500 chars. 

STR:
1. Load https://code.addons-dev.allizom.org/en-US/browse/618525/versions/1689955/?path=src%2Faction%2Findex.html and observe the lines
2. Look at the same example on stage https://code.addons.allizom.org/en-US/browse/1003958/versions/2476781/?path=src%2Faction%2Findex.html

Expected result:
On dev - the highlighting should be disabled. 

3. Another example: https://code.addons-dev.allizom.org/en-US/browse/502868/versions/1541685/?allowSlowPages=false&path=src%2Fjs%2FGrammarly-signin.js is a truncated file after https://github.com/mozilla/addons-code-manager/issues/1347 landed. 

Expected result:
Highlighting should also be disabled because it contains 2000 chars. 

Notes:
This is only reproducible on dev for the Browse view with FF72(Win10). It is not reproducible for the Compare view.

**Comment by bobsilverberg** [comment]
My apologies for not being more explicit in my description of #1347. That patch actually undid the change that causes truncated files to not be highlighted, so this is expected behaviour. As of the landing of #1347, truncated files have gone back to being highlighted.

**Comment by ioanarusiczki** [comment]
Example nr.3 is not a bug - the highlighting was enabled for truncated files.
See https://github.com/mozilla/addons-code-manager/issues/1347#issue-538678944

**Comment by ioanarusiczki** [comment]
@bobsilverberg Yes, I read the issues and realized it later. 
The first example is a code line of 501 chars - not truncated. It is applicable in that case too?

**Comment by bobsilverberg** [comment]
> @bobsilverberg Yes, I read the issues and realized it later.
> The first example is a code line of 501 chars - not truncated. It is applicable in that case too?

We removed all logic for disabling highlighting in browse mode, as we now believe it will not be necessary. As long as files over 3000 characters are truncated, it is believed that will address the performance concerns. So yes, the first example is also now the expected behaviour.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Ok, then I'm going to close this. Thanks for the answers.
