### ISSUE TITLE
The first 2000 chars are not visible for compare pages with only one long code line

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1391]
Followup for https://github.com/mozilla/addons-code-manager/issues/1366#issuecomment-573732368

STR:
1. Load a compare page which has a long code line with more than 3000 chars 
Examples: 
https://code.addons-dev.allizom.org/en-US/compare/618525/versions/1689954...1689955/?allowSlowPages=false&path=src%2Fbackground%2Fbackground.bundle.js
https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1541685...1688187/?allowSlowPages=false&path=src%2Fjs%2FGrammarly-signin.js
2. Observe the layout

Expected result:
The first 2000 chars from the line are visible. 

Actual result:
Only  /* diff truncated by code-manager */ is displayed next to `1`. 

Notes:
This issue is reproducible on dev with FF72(Win10). 

![A diff shortened](https://user-images.githubusercontent.com/33448286/72340299-a22a4c80-36d0-11ea-918a-51de3a8794e1.png)

**Comment by bobsilverberg** [comment]
To solve this issue, if a trimmed diff would only end up with a single change, we will trim the contents of that change to the maximum length (which is currently 2000 characters), and then output a second change with the ` /* diff truncated by code-manager */` message.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Verified on dev with FF73(Win10). 

![the first 2000chars](https://user-images.githubusercontent.com/33448286/74537227-5b837880-4f42-11ea-8082-9badf88432c7.png)
