### ISSUE TITLE
Write common API layer

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#14]
The common API layer should be the base of all API calls, i.e. the so-called `callApi` in addons-frontend. We can probably reuse its interface/design/code (fixing a few annoying things along the way).

This layer will talk to the Django HTTP API and we'll have to setup authentication for that too (with base62 tokens IIRC).

**Comment by willdurand** [comment]
This could be of interest: https://github.com/themouette/react-resource

**Comment by kumar303** [comment]
> This could be of interest: https://github.com/themouette/react-resource

I'd like to look in more detail but I dislike how the API request is tied to a Redux action. I wouldn't want to replay an action using the time travel debugger and have it trigger a real API request.

**Comment by kumar303** [comment]
I looked more into [axios](https://github.com/axios/axios) and I think it's too heavyweight. All we need is a wrapper around `fetch()`, period. This was the point of `callApi()` so maybe that's all we need.

**Comment by willdurand** [comment]
> I'd like to look in more detail but I dislike how the API request is tied to a Redux action. I wouldn't want to replay an action using the time travel debugger and have it trigger a real API request.

I believe there is some testing tools (knowing the previous iteration of this lib). In the test suite, there won't be any real HTTP calls.

As for the action replayed triggering an API request, if that action implies an HTTP call, I would expect the HTTP call to be sent 🤔 That's what we have in addons-frontend, replaying `fetchXXX` does trigger the saga, which calls the API layer, which sends the request.

**Comment by willdurand** [comment]
> I looked more into [axios](https://github.com/axios/axios) and I think it's too heavyweight. All we need is a wrapper around `fetch()`, period. This was the point of `callApi()` so maybe that's all we need.

Agreed! We could reuse `callApi`, removing the `node-fetch` dependency too and simplifying the interface.

**Comment by willdurand** [comment]
> > I'd like to look in more detail but I dislike how the API request is tied to a Redux action. I wouldn't want to replay an action using the time travel debugger and have it trigger a real API request.
> 
> I believe there is some testing tools (knowing the previous iteration of this lib). In the test suite, there won't be any real HTTP calls.
> 
> As for the action replayed triggering an API request, if that action implies an HTTP call, I would expect the HTTP call to be sent 🤔 That's what we have in addons-frontend, replaying `fetchXXX` does trigger the saga, which calls the API layer, which sends the request.

Also, I believe this is slightly out of this issue's scope but I did not know where to put this lib. I was thinking about all the code we have to write to make API calls in addons-frontend, and that would be a way to reduce the amount of code to write (with this lib or another, similar one).

**Comment by kumar303** [comment]
> I was thinking about all the code we have to write to make API calls in addons-frontend

Yeah, that's true. It would be nice to reduce that.

> As for the action replayed triggering an API request, if that action implies an HTTP call, I would expect the HTTP call to be sent 🤔 That's what we have in addons-frontend, replaying fetchXXX does trigger the saga, which calls the API layer, which sends the request.

Yes, replaying an addons-frontend fetch action in the Redux developer tool re-runs the saga which triggers API requests. This makes it impossible to step through one state change at a time so I think it's a drawback of action side effects. 

I have seen issues in the saga repo saying that it sagas should be disabled in the Redux developer tool so I had the impression that other things like thunk side effects are already disabled. I need to confirm that but, in general, I think we need to seriously re-evaluate how we rely on action side effects. I am hesitant to add more side effect-y libraries.

**Comment by kumar303** [comment]
[redux-loop](https://github.com/redux-loop/redux-loop) sounds like what I want:

> All of the behavior of your application can be traced through one place, and that behavior can be easily broken apart and composed back together.

**Comment by EnTeQuAk** [comment]
Regarding authentication, as discussed yesterday with @diox and @willdurand on IRC ``addons-code-manager`` will be primarily initialized via a link from the reviewer tools that links either to the browse or compare view (at least that's what's currently happening).

From there it will have to read the `frontend_auth_token` cookie which contains the auth token that's required to authenticate against the API (the token is a salted hmac containing among others the unique auth id of the user).

With that ``addons-code-manager` can authenticate via the known ``Authorization: Bearer eyJhbGciOiAiSFMyNTYiLCAid...`` header.

All that should be (partially) identical to how addons-frontend works afaik.
