### ISSUE TITLE
404 status for cose-manifest file is displayed on the top of the compare page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#1405]
As a followup for https://github.com/mozilla/addons-code-manager/issues/1322 ( not sure if it's a regression)

STR:
1. I uploaded a new version for an add-on (did not change anything in the code structure for any file)
2. I go to the compare page https://code.addons-dev.allizom.org/en-US/compare/325576/versions/1688306...1690075/

Expected result:
No API error

Actual result:
404 for https://addons-dev.allizom.org/api/v5/reviewers/addon/325576/versions/1690075/?file=META-INF%2Fcose.manifest&lang=en-US

Notes:
This issue is reproducible on dev with FF72(Win10). 

![404](https://user-images.githubusercontent.com/33448286/72818169-ad9eea00-3c73-11ea-9d68-fe2edd3a454a.png)

**Comment by mirefly** [comment]
This is caused by attempting to fetch a deleted file. I can work on this.

**Comment by bobsilverberg** [comment]
> This is caused by attempting to fetch a deleted file. I can work on this.

That was my first thought as well, but @ioanarusiczki said that she did not change anything about the file structure, which suggests she did not delete any files, so why would there be a delete file between these two versions?

**Comment by mirefly** [comment]
> she did not change anything about the file structure, which suggests she did not delete any files, so why would there be a delete file between these two versions?

I am not sure, and a bit confused about the first step in STR. I just opened the link in this issue (https://code.addons-dev.allizom.org/en-US/compare/325576/versions/1688306...1690075/) and did see the deleted file in the file tree. BTW, the error occurred when preloading the next diff file (which was deleted).
![image](https://user-images.githubusercontent.com/4984681/72834348-d7411c80-3c45-11ea-8eb4-a866ab0a0eed.png)

**Comment by bobsilverberg** [comment]
@mirefly Thanks, yes, I see that now too. I know we have a number of issues open to address the fact that we don't have API support currently for deleted files, and I am guessing that one of those might address this. Are your thoughts that we should at least not show an error message for the time being, until the API issues are resolved?

**Comment by mirefly** [comment]
I found a few issued about deleted *version*, like https://github.com/mozilla/addons-code-manager/issues/1130  https://github.com/mozilla/addons-server/issues/12726   https://github.com/mozilla/addons-server/issues/12725, but did not find issues about supporting delete *files*.

The current [Browse API](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#browse) returns 404 if the path does not exist in the current version, no matter if it exists in previous versions. I think it makes sense and no needs to change. My thought was to add a check before fetching a version file to make sure the entry status is not 'D' (probably only in Compare page).

**Comment by mirefly** [comment]
I think though the compare page without the selected version file loaded (which has been deleted in the new version), and found two problems:
1. We have no file information, like file size, sha256, download link, to display in accordion menu.
2. The code overview would be blank.

I have no idea what information/overview we should show for the deleted files. Fetching version file using the old version number could help us get file information, but may introduce quiet a bit complications since we have to deal with deleted file as a special case.

Anyway, I feel it would be nice to prevent the API call to fetch a deleted file as the first step to properly show deleted files in compare mode. With regard to Browse API support for deleted files, it would require the server to check if the path exists in all previous versions (?), so I believe it would be better to fix this issue in the front end. @bobsilverberg  How do you think about it?

**Comment by ioanarusiczki** [comment]
@mirefly @bobsilverberg To explain why I said that I did not delete or modified add-on files : I deleted the META-INF folder before uploading the next version because as far as I know the signature folder is auto-generated when the addon is uploaded. 
Sorry for creating confusion.

**Comment by bobsilverberg** [comment]
> I think though the compare page without the selected version file loaded (which has been deleted in the new version), and found two problems:
> 
>     1. We have no file information, like file size, sha256, download link, to display in accordion menu.
> 
>     2. The code overview would be blank.
> 
> 
> I have no idea what information/overview we should show for the deleted files. Fetching version file using the old version number could help us get file information, but may introduce quiet a bit complications since we have to deal with deleted file as a special case.
> 
> Anyway, I feel it would be nice to prevent the API call to fetch a deleted file as the first step to properly show deleted files in compare mode. With regard to Browse API support for deleted files, it would require the server to check if the path exists in all previous versions (?), so I believe it would be better to fix this issue in the front end. @bobsilverberg How do you think about it?

I agree, @mirefly, that a good first step would be to not issue the API call if the file has been deleted. Do you want to work on that?

**Comment by mirefly** [comment]
> Do you want to work on that?
Yes.

**Comment by ioanarusiczki** [comment]
I verfied on dev with FF72(Win10) and the issue I described above is not reproducible anymore.

@mirefly  @bobsilverberg Going from compare pages to browse pages there are two things I've noticed while testing:

- for the case when the new version does not contain files because they've been deleted, if I change the view (going from the compare file to the new version's Browse page, I will see the 404 shown - because the file is no longer available for the new version. 

Would it be alright that instead of a continuous loading state and the actual api error to display a message with a link "the file has been deleted on version 2.0 , click here to return to the previous [page](https://code.addons-dev.allizom.org/en-US/compare/7560/versions/1252898...1688305/?path=chrome.manifest)" ?

I used as an example this page https://code.addons-dev.allizom.org/en-US/compare/7560/versions/1252898...1688305/?path=chrome.manifest 

![this one](https://user-images.githubusercontent.com/33448286/73360089-dc881200-42aa-11ea-901f-c30a8b397c26.gif)

- for the case where I have added files (the old version did not have them) when I go to the Browse page of the old version I receive a 500 server error. 

Could it be replaced by a message with a link so that the reviewer can return to the compare view ?

The page in the example below is https://code.addons-dev.allizom.org/en-US/compare/7560/versions/1252898...1688305/?path=mozilla-recommendation.json

![that one](https://user-images.githubusercontent.com/33448286/73360762-52d94400-42ac-11ea-9622-2a2b1271aa59.gif)

Let me know your thoughts about this.

**Comment by mirefly** [comment]
@ioanarusiczki  Thanks for testing all these cases.

> Would it be alright that instead of a continuous loading state and the actual api error to display a message with a link "the file has been deleted on version 2.0 , click here to return to the previous page" ?

I guess we should let the selected path fall back to the initial path (manifest.json) when the file does not exist in the new version. That should fix all these errors.

**Comment by mirefly** [comment]
[500 error ](https://github.com/mozilla/addons-server/issues/13374) in fetching `validation.json` is because the file is too old (https://github.com/mozilla/addons-server/issues/13374#issuecomment-579785782). Probably we do not need to support it, do we?

**Comment by ioanarusiczki** [comment]
@mirefly Thanks for filing the issues. I will check on them and close this one. - verified on dev with FF72(Win10).

**Comment by ioanarusiczki** [comment]
@mirefly  I filed https://github.com/mozilla/addons-code-manager/issues/1418 (I initially thought https://github.com/mozilla/addons-code-manager/issues/1410 is about the errors discussed above)
