### ISSUE TITLE
File information is in loading state for deleted files in compare mode

### ISSUE THREAD

**Issue by mirefly** [mozilla/addons-code-manager#1410]
### Describe the problem and steps to reproduce it:
1. Go to https://code.addons-dev.allizom.org/en-US/compare/325576/versions/1688306...1690075/?path=META-INF%2Fmozilla.sf
2. In the left panel (accordion menu), open 'information'

### What happened?
It shows text "Loading file"

### What did you expect to happen?
At least, not be in the loading state. But I am not sure if we should show any  information (Version, Size, SHA256 hash, MIME type, Download link) of the deleted files which is only in old version, while show other file information from the new version.

**Comment by bobsilverberg** [comment]
Thanks for filing this @mirefly! I agree we shouldn't show the "Loading" indicator, and also that the fields are irrelevant for a deleted file. Perhaps we can just show a message saying that the file has been deleted?

**Comment by mirefly** [comment]
> Perhaps we can just show a message saying that the file has been deleted?
That would be an easy fix. I like it and will create a PR for this.

**Comment by ioanarusiczki** [comment]
@mirefly I verified on dev with FF72(Win10) - it looks like the information is no longer available for the deleted files - compare pages

![deleted files information](https://user-images.githubusercontent.com/33448286/73452523-bd54b780-4372-11ea-9d7c-7ef6085c183a.png)

**Comment by mirefly** [comment]
Thanks for verifying it.

> it looks like the information is no longer available for the deleted files - compare pages

Yes, it is expected since the file has been removed in the new version.
