### ISSUE TITLE
File list contains files that have been deleted in Browse

### ISSUE THREAD

**Issue by mirefly** [mozilla/addons-code-manager#1421]
From: https://github.com/mozilla/addons-code-manager/issues/1418#issuecomment-582085009
STR:
1.   Load https://code.addons-dev.allizom.org/en-US/compare/7560/versions/1252898...1688305/?path=chrome.manifest
2. Go to the new version's Browse page by clicking the "Compare Versions" button
3. Observe the page

Actual result: The file list does not change
Expected result: The file list should be updated. The deleted folders/files like 'chrome' 'defaults' are not supposed to be there.

**For QA:**

When the patch lands, the file list should be updated when 
1. Switching between Browse and Compare mode or
2. Selecting a new version in Browse/Compare

It is expected to see error messages (404) on the top (and loading spinner, https://github.com/mozilla/addons-code-manager/issues/1418#issuecomment-582085009)  when the selected path does not exist in the new version. The file list should always be shown, and allow the user to select another file.

**Comment by ioanarusiczki** [comment]
@mirefly 
- After the 404 is displayed on the new version I could navigate away from it by clicking another file from the file tree and go back to the compare page.
- I could select another new version too.
- I see the file list updated accordingly: the deleted files are not available in the file list (chrome, defaults, chrome.manifest or install.rdf folders) - Browse view.
