### ISSUE TITLE
Investigate using GA User Timings for performance tracking

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1424]
This is a spin-off from #1423. Discussions in Slack indicate that trying to collect client-side performance measures and loading them into InfluxDB might be quite challenging, and could also be of questionable value, if we can get the info we need in an easier way.

This issue is about investigating [Google Analytics' User Timings](https://developers.google.com/analytics/devguides/collection/analyticsjs/user-timings) to see if it might give us the info we need and the ability to analyze that data.

**Comment by bobsilverberg** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1613724 to add Google Analytics to code manager.

**Comment by bobsilverberg** [comment]
@wagnerand @jvillalobos We're going to try using Google Analytics to record and report performance metrics for the code manager front end. Should we also add page tracking at this time? It's a pretty simple thing to do, so I don't think it would cost much in terms of time. I'm just not sure what value we'd derive from the data. It might let us know how widely/often the new code manager is being used, and could possible show us usage patterns.

What do you think?

**Comment by wagnerand** [comment]
@bobsilverberg I would lean towards deferring this to later to allow us to evaluate how useful/needed having that data would be.

**Comment by bobsilverberg** [comment]
Thanks @wagnerand. It's certainly simpler *not* to do it.

**Comment by jvillalobos** [comment]
I agree with Andreas.

**Comment by bobsilverberg** [comment]
I think this issue can be marked as closed after the landing of https://github.com/mozilla/addons-code-manager/pull/1502.
