### ISSUE TITLE
Storybook build is failing on CI

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1430]
The task to build and deploy Storybook is failing on Travis. See https://travis-ci.com/mozilla/addons-code-manager/jobs/285952503

It seems that the problem is a result of the [upgrade to react-scripts 3.3.1](https://github.com/mozilla/addons-code-manager/pull/1419).

Let's back that out to see if it fixes the problem, and then investigate whether this is a known issue and/or if there are any fixes for it.

**Comment by bobsilverberg** [comment]
Looks like this did indeed fix the issue: https://travis-ci.com/mozilla/addons-code-manager/builds/148443985

I am investigating what the issue with 3.3.1 might have been to see if we can make some changes and then upgrade.

**Comment by bobsilverberg** [comment]
We needed to update `react-scripts` to `3.4.0` to deal with #1443, but that has re-introduced this build error, so I am re-opening this. Storybook runs fine locally, it's the build step that times out on CI. Here's a recent failure: https://travis-ci.com/mozilla/addons-code-manager/builds/149496260

**Comment by bobsilverberg** [comment]
I tried reverting back to `3.3.0` of `react-scripts` on top of all the other dependency updates that landed, but that brings back the error reported at #1443, so I'm not sure what we can do at this point. We should probably report the issue to `create-react-app`. My attempts to reproduce the problem locally resulted in some pretty serious issues on my local environment which caused me to lose nearly a day struggling with it, so I am loath to try again. If anyone else is brave enough to attempt it, and can generate a meaningful error message that would be much appreciated.

**Comment by mirefly** [comment]
I tried `yarn storybook-build` locally (react-scripts 3.4.0) and see
```
info=> Compiling preview..
70% building 78/114 modules 36 active .../babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/toConsumableArray.jsERR! => Failed to build the preview
ERR! No module factory available for dependency type: CssDependency
/home/sf/addons-code-manager/node_modules/neo-async/async.js:16
    throw new Error('Callback was already called.');
```
Then found https://github.com/storybookjs/storybook/issues/9777. It seems some one found workaround, but I am not sure.

**Comment by bobsilverberg** [comment]
Thanks @mirefly! That does look like the problem we are having, and some said that downgrading `react-scripts` to 3.3.0 fixed it, but I don't think we have that option. The other workaround they discuss with webpack might not be possible with `create-react-app`. I guess we should keep an eye on that issue and see if a proper resolution is achieved.
