### ISSUE TITLE
FullscreenGrid story layout is broken

### ISSUE THREAD

**Issue by mirefly** [mozilla/addons-code-manager#1435]
https://mozilla.github.io/addons-code-manager/?path=/story/fullscreengrid--default
The toggle buttons are expected at the bottom of the side panels.
![image](https://user-images.githubusercontent.com/4984681/74461140-47108480-4e4b-11ea-9160-3b1860ffdce8.png)

**Comment by MikeM711** [comment]
Hi

https://github.com/mozilla/addons-code-manager/blob/27e57a8f426ebb666b34ad5198e532f78d190415/stories/setup/styles.scss#L62-L68

In the above scss, I changed `display: flex;` to `display: inline-grid;`

Is this correct?

<img width="1678" alt="Screen Shot 2020-05-22 at 8 00 21 PM" src="https://user-images.githubusercontent.com/38841182/82716757-26847180-9c67-11ea-826b-589575c8f096.png">
