### ISSUE TITLE
Provide link to old file viewer for browse view

### ISSUE THREAD

**Issue by diox** [mozilla/addons-code-manager#1471]
In https://github.com/mozilla/addons-server/issues/13634 we're discussing replacing all links to the old file viewer in AMO by links to the code manager. 

We need to add a way to fall back to the old file viewer if things go wrong in code-manager. Later when we sunset the old file viewer we'll then remove that link.

**Comment by bobsilverberg** [comment]
We currently have a link in Code Manager that points back to Reviewer Tools, but it points to the review page. E.g., https://code.addons.mozilla.org/en-US/browse/2273944/versions/4970869/ has a link that points back to https://reviewers.addons.mozilla.org/reviewers/review/dark-theme-enhanced. 

I believe this is about adding an additional link to Code Manager that points directly to the legacy file viewer, is that correct? 

So https://code.addons.mozilla.org/en-US/browse/2273944/versions/4970869/ would it point to https://reviewers.addons.mozilla.org/files/browse/3023603/, and https://code.addons.mozilla.org/en-US/compare/1478066/versions/3168788...4442524/ would point to https://reviewers.addons.mozilla.org/files/compare/1713167...2986902/.

It looks like the numbers used for the legacy file viewer are the `id` of each `file`, so we do seem to have that info in Code Manager.

**Comment by bobsilverberg** [comment]
We also need to decide where these links should be in the Code Manager.

**Comment by bobsilverberg** [comment]
Looking at the API response to the `compare` endpoint, it looks like we get a `file.id` for the newer version, but not for the older version, so I don't think we have the data we need to build the URL for the legacy file viewer for the compare view. Does this sound like an accurate assessment @EnTeQuAk?

**Comment by EnTeQuAk** [comment]
> Does this sound like an accurate assessment @EnTeQuAk?

That is correct, we currently only expose the `file.id` for the current version. It should be fairly easy to also expose the parent file id.

**Comment by bobsilverberg** [comment]
Note that because of https://github.com/mozilla/addons-server/issues/13650, this issue is now just going to cover the browse page, and the compare page will be dealt with via https://github.com/mozilla/addons-code-manager/issues/1472.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified the browse pages on dev with FF73(Win10):
- the link redirects the user to the old viewer - the same file is shown in the old viewer in a new tab. 
- the link is a bit invisible having the same color as the username. On the other had the old viewer will be removed. If you want me to file an issue let me know. 

![same font](https://user-images.githubusercontent.com/33448286/76226661-da5c9000-6226-11ea-8450-9f2a48b257c6.png)
