### ISSUE TITLE
Update PartialExternalVersion type after API changes land

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1476]
https://github.com/mozilla/addons-server/issues/13651 is removing some fields from the API response for reviewers APIs. We should update our types accordingly, after the changes land.

It looks like the only type affected is [PartialExternalVersion](https://github.com/mozilla/addons-code-manager/blob/master/src/reducers/versions.tsx#L93), but whoever works on this should verify that.

**Comment by ioanarusiczki** [comment]
@bobsilverberg https://github.com/mozilla/addons-server/issues/13651 has been verified. The information removed from the endpoints was not used by code manager. Let me know what to verify in code manager or is this a qa not needed ?

**Comment by willdurand** [comment]
> @bobsilverberg [mozilla/addons-server#13651](https://github.com/mozilla/addons-server/issues/13651) has been verified. The information removed from the endpoints was not used by code manager. Let me know what to verify in code manager or is this a qa not needed ?

I think if there is no obvious problem then it can be marked as verified.

**Comment by ioanarusiczki** [comment]
@willdurand Looks good to me. 
Verified on dev with FF73(Win10).
