### ISSUE TITLE
Add uses_unknown_minified_code to the versions reducer

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1495]
This is a spin off from #1462, as the patch for that looks like it's going to be fairly large.

This is just about taking the data provided by the API for `uses_unknown_minified_code` and adding that data to the file data that is stored by the `versions` reducer.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Looks good to me. I verified browse and compare pages - layout, file navigation, keyboard navigation, draft comments, code overview.
Verified on dev with FF74(win10).
