### ISSUE TITLE
Create React App does not lint TypeScript

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#152]
For some reason, linting is broken. I cannot get `yarn react-scripts-start` to show lint output.

Here's an example of how it should work. I followed these steps:

* `npx create-react-app lint`
*  `cd lint`
* `yarn start`
* I added `const unsuedVar = 2` to the top of `render()` in `App.js`

Now I see this in the console:

<img width="527" alt="screenshot 2019-02-06 10 31 10" src="https://user-images.githubusercontent.com/55398/52356856-a0ed9b80-29fa-11e9-82af-d285294c0714.png">

If I try to trigger the same lint error in `addons-code-manager`, I do not see the lint error. Instead I see `Compiled successfully`.

**Comment by bobsilverberg** [comment]
Is this because we're using ESLint instead of TSLint?

**Comment by bobsilverberg** [comment]
Scratch that - this is an ESLint error.

**Comment by kumar303** [comment]
Ah, ok, linting was never supported for TypeScript. I illustrated the problem here: https://github.com/facebook/create-react-app/issues/5641#issuecomment-461117408

**Comment by willdurand** [comment]
This will be fixed by https://github.com/mozilla/addons-code-manager/pull/633

<img width="721" alt="Screen Shot 2019-04-24 at 10 50 34" src="https://user-images.githubusercontent.com/217628/56646214-6c938e00-667f-11e9-97ea-99bf93da63bb.png">

**Comment by willdurand** [comment]
Fixed.
