### ISSUE TITLE
Send the URL along with the performance timings

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1543]
I had originally assumed that the URL of the page that the user was on when a performance timing was sent would have somehow been recorded by GA, but that seems to not be the case. It would be good, for investigative purposes, if we could see the URL for instances in which there was a performance issue, so this issue is about making sure we send the URL along with the performance measures.

**Comment by ioanarusiczki** [comment]
@bobsilverberg If I'm looking in the Console I can see a GA event which is sending time for the URLs.
If I click the URL from the Console it will redirect to the same page that I am viewing. 

![URL sent](https://user-images.githubusercontent.com/33448286/79979275-ed12e780-84a9-11ea-97a8-44a499399d0d.png)

This is happening on all pages I checked on - browse and compare views.

If there is anything else I should look for please let me know.

**Comment by bobsilverberg** [comment]
> @bobsilverberg If I'm looking in the Console I can see a GA event which is sending time for the URLs.
> If I click the URL from the Console it will redirect to the same page that I am viewing.
> 
> ![URL sent](https://user-images.githubusercontent.com/33448286/79979275-ed12e780-84a9-11ea-97a8-44a499399d0d.png)
> 
> This is happening on all pages I checked on - browse and compare views.
> 
> If there is anything else I should look for please let me know.

No, that's good enough. Thanks!
