### ISSUE TITLE
File size is reported incorrectly in the Information panel

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1548]
### Describe the problem and steps to reproduce it:

1. Load any file for a version, observe the `Size` in the Information panel.
2. Load a different file for the same version, observe the `Size` in the Information panel.

### What happened?

The two files are reported as having the exact same size, which is very likley not the correct size for either of them.

### What did you expect to happen?

Each file would have the correct size for that file reported.

### Anything else we should know?

I discovered this while working on the code for the reviewers API. The `size` returned for the `file` from the reviewers API is always the size of the file for the add-on (i.e., the size of the xpi file), whereas code manager was assuming it would be the size of the *selected* file.

This could be fixed in code manager using the file entry, but it would be better to fix on the server side, and I am currently working on an issue that will address it.

**Comment by ioanarusiczki** [comment]
@bobsilverberg While checking the [API](https://github.com/mozilla/addons-server/issues/14026) issue on this matter I took a look on the values returned by "size". 
- The values indicated by the Browse or Compare API are shown in code manager for each file (the size of the .xpi file is no longer displayed everywhere).

- I used this tool https://www.gbmb.org/bytes-to-kb and I've realized that codemanager provides the size in binary (not in decimal). 

I'll give an example:
https://code.addons-dev.allizom.org/en-US/browse/616886/versions/1688268/?path=dial.html

Codemanager size: 32.88 KiB in binary
In the API "size": 33674 

Please let me know if that's alright then I can mark this issue verified. 
Thanks!

**Comment by bobsilverberg** [comment]
> * I used this tool [gbmb.org/bytes-to-kb](https://www.gbmb.org/bytes-to-kb) and I've realized that codemanager provides the size in binary (not in decimal).
> 
> 
> I'll give an example:
> [code.addons-dev.allizom.org/en-US/browse/616886/versions/1688268/?path=dial.html](https://code.addons-dev.allizom.org/en-US/browse/616886/versions/1688268/?path=dial.html)
> 
> Codemanager size: 32.88 KiB in binary
> In the API "size": 33674
> 
> Please let me know if that's alright then I can mark this issue verified.
> Thanks!

Yes, that is expected.
