### ISSUE TITLE
Change logic for truncation of files

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1552]
I am repurposing this issue to be about implementing the changes we discussed today via Zoom.  Here is what we decided:

1. *All* minified files will be truncated, regardless of their length.
2. Non-minified files will be truncated if they contain more than 5000 lines.
3. All truncation, for both file types, will be done based on number of characters. We will display only the first 300 characters of any files that have been truncated.

@willdurand @wagnerand Please confirm if I accurately captured the requirements we discussed.

**Comment by ioanarusiczki** [comment]
@bobsilverberg
 
- except for the situation filed for the compared view for minified files - https://github.com/mozilla/addons-code-manager/issues/1567 I did not see other problems.  

- Minified files other than the .js such as json, css or html will not look trimmed. But this is being tracked under mozilla/addons-linter#3103

- example of truncation for more than 5000 lines of code:

  Default for Browse view is "View the original file" and the first 300 chars are displayed

   https://code.addons-dev.allizom.org/en-US/browse/619691/versions/1691184/?path=inject%2Findex.js
  https://code.addons-dev.allizom.org/en-US/browse/619691/versions/1691184/?path=_locales%2Far%2Fmessages.json

  Default for Compare view is "Shorten the diff" and if it's shortened the first 300 chars are displayed

   https://code.addons-dev.allizom.org/en-US/compare/619691/versions/1691091...1691184/?path=inject%2Findex.js
  https://code.addons-dev.allizom.org/en-US/compare/619691/versions/1691091...1691184/?path=_locales%2Far%2Fmessages.json
