### ISSUE TITLE
Adjust logic for the versions reducer to reflect API changes

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1559]
Depends on https://github.com/mozilla/addons-server/pull/14043

Changes are landing in https://github.com/mozilla/addons-server/pull/14043 which will move where some data can be found in the responses for the browse and compare APIs. Specifically, code manager currently looks for `sha256` and `mimetype` in the `entries` for a file, but after the above mentioned patch lands, those properties will be found with the `file` itself, not in the `entity` for the file.

As well, `size` will no longer exist for an `entity`, nor will `modified`. Code manager does not currently use either of those, but we should still update our types to reflect this new reality.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
 - I verified this issue on dev with Postman and I can confirm that `size`, `mimetype`, and `sha256` were moved from `entries` into `file`.
 
- I did not find `modified` anywhere in the API.  If that's not ok please let me know. 

I verified this issue for both - Browse and Compare APIs.

**Comment by ioanarusiczki** [comment]
@bobsilverberg By mistake I posted the comment for the [server issue](https://github.com/mozilla/addons-server/issues/14042) here but I also verified codemanager about `sha256`, `mimetype` and `size` and I can confirm that the information from the APIs is reflected correctly by Information for each file. 
For the compare view - the information provided is from the basefile (the older version). 

If there's anything else I should check on please let me know.

**Comment by bobsilverberg** [comment]
> @bobsilverberg By mistake I posted the comment for the [server issue](https://github.com/mozilla/addons-server/issues/14042) here but I also verified codemanager about `sha256`, `mimetype` and `size` and I can confirm that the information from the APIs is reflected correctly by Information for each file.
> For the compare view - the information provided is from the basefile (the older version).

Hmm, that doesn't sound quite right. I think it should be from the new file. Can you post an example from dev?

**Comment by ioanarusiczki** [comment]
@bobsilverberg I stand corrected, I verified again on dev today and I can confirm that the information is provided from the new file for the compare view. 

Example:
https://code.addons.allizom.org/en-US/compare/1004477/versions/2477464...2477465/?allowSlowPages=true&path=_locales%2Far%2Fmessages.json

Old file 
https://code.addons-dev.allizom.org/en-US/browse/619691/versions/1691091/?path=_locales%2Far%2Fmessages.json

New file
https://code.addons-dev.allizom.org/en-US/browse/619691/versions/1691184/?path=_locales%2Far%2Fmessages.json
