### ISSUE TITLE
Adjust logic for the versions reducer to reflect further API changes 

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1566]
More changes to the response from the reviewers APIs are going to land in https://github.com/mozilla/addons-server/pull/14105. This will remove a number of properties of the `file` object returned. None of these are currently used anywhere in the logic or UI, but one of them is currently referenced in our `InternalVersionFile` object, so that definitely needs to be updated. The rest of the changes will just be to the external types.

The properties being removed are:
-  created (this is the one that is currently in `InternalVersionFile`)
-  hash
-  is_mozilla_signed_extension
-  is_restart_required
-  is_webextension
-  permissions
-  platform
-  status
-  url

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on dev and stage some Browse and Compare pages and tested the main functionalities. The removal of the API [properties ](https://github.com/mozilla/addons-code-manager/issues/1566#issue-609169380) don't seem to affect code manager  - FF75(Win10).
