### ISSUE TITLE
Turn off debug mode for Google Analytics

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1569]
When we first implemented GA for Code Manager, debug mode was enabled for local development by default. This provides a lot of information that can be useful when working directly with GA, but the amount of info it adds is actually quite annoying when you don't really care about GA.

This issue is about changing the default to be `debug: false`, but allowing it to be changed locally via `.env.common-local`.

For QA:
There will not be any observable differences from this change on any of the hosted environments, but please check that the existing code that sends pings to Google Analytics remains unaffected.

**Comment by AlexandraMoga** [comment]
I've checked the tracking set for Browse and Compare pages and as far as I can tell the behavior is unchanged. I took #1423 as reference.
I'm marking the issue as verified fixed.
