### ISSUE TITLE
Update Code Manager to deal with changes in Browse and Compare APIs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1587]
Depends on https://github.com/mozilla/addons-server/pull/14218.

Another change is going to land in https://github.com/mozilla/addons-server/pull/14218. It will remove `entries` from the `file` property and move them to the root of the response, in a property called `file_entries`.

We need to update code manager to deal with this.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I believe I should check on regressions on Browse and Compare pages in code-manager?

**Comment by bobsilverberg** [comment]
> @bobsilverberg I believe I should check on regressions on Browse and Compare pages in code-manager?

Correct! Thanks @ioanarusiczki!

**Comment by ioanarusiczki** [comment]
@bobsilverberg I did not find regressions on https://code.addons-dev.allizom.org/
