### ISSUE TITLE
Only retrieve file info when that's all we need, in the Browse view

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1590]
This is a spin-off from #1574 

While working on that issue I found a number of things that can/should be fixed in terms of how we're calling APIs and returning data for both the Browse and Compare views. Because this is a fairly large task, I'm breaking it down into smaller pieces.

This issue is simply about changing the logic for the Browse view so that when we only need to retrieve file information (because we already have version information), we use the new `file_only` param of the browse API to avoid returning unnecessary data.

For QA:

When looking at the API requests generated by code manager to `/api/v5/reviewers/addon/{addonId}/versions/{versionId}/`, the first API request for a version will *not* have the `file_only` param specified, and the response will be a complete `version` object, including a `file_entries` property and an embedded complete `file` object. For each subsequent request to the API for a different file (there will be a `file=` param on the URL), bur for the same version, the `file_only=true` param should be specified, and the response will contain just an `id` and a `file` object.

**Comment by ioanarusiczki** [comment]
@bobsilverberg When going to a new file for the same version the API is showing the `id` and `file` object with `file` and `file_only` parameters being present. 

![only the file object](https://user-images.githubusercontent.com/33448286/83029524-6f5b7200-a03b-11ea-87b1-cb4a839f8529.gif)
