### ISSUE TITLE
Update Code Manager to address changes in the draft_comments API

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1594]
Depends on https://github.com/mozilla/addons-server/pull/14361

When https://github.com/mozilla/addons-server/pull/14361 lands, the `draft_comments` API will no longer return a full `version` object, but rather will return just a `version_id`. Code manager is not currently using returned the `version` object for anything, but code does exist to load it into the redux state, so that code is going to need to change when https://github.com/mozilla/addons-server/pull/14361 lands.

For QA:

No changes in behaviour should be observed. Please check the comments features for regressions.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

On both dev and stage:

- the client side has problems. If I try to write "test test test" it will only show up "tst tst tst".
- if I hurry to write more text it will cause strange errors, comment cannot be saved, the page I was on is not displayed and another one is available instead.
- if I use `h` in the text it will open and close the side panels. 

![code manager](https://user-images.githubusercontent.com/33448286/83741096-6c2a3c80-a660-11ea-9075-47bfa1f37a2d.gif)

- posting comments through the API is working.

**Comment by bobsilverberg** [comment]
> @bobsilverberg
> 
> On both dev and stage:
> 

Thanks @ioanarusiczki. What about on prod? I'm surprised that this change would have resulted in this and am wondering if this is a problem that existed before.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I filed a different issue https://github.com/mozilla/addons-code-manager/issues/1607
I'm going to re-check the draft comment side once that is fixed.
