### ISSUE TITLE
Remove all comments that disable the @typescript-eslint/camelcase rule

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1595]
Depends on https://github.com/mozilla/addons-code-manager/pull/1596

After we are able to update to version 3.0 of [`typescript-eslint`](https://github.com/typescript-eslint/typescript-eslint), we can remove any comments that are in place which explicitly disable the @typescript-eslint/camelcase rule, because it has been removed from `typescript-eslint`.

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @willdurand

**Comment by ariain** [comment]
@caitmuenster can i work on this issue??

**Comment by caitmuenster** [comment]
Go for it, @ariain! We'll assign it to you once you open a PR. :) If you have any questions, feel free to tag @willdurand in a comment.

**Comment by ariain** [comment]
@caitmuenster @willdurand I checked for 
`/* eslint-disable @typescript-eslint/class-name-casing */`
`/* eslint-disable @typescript-eslint/camelcase */`
and all the rules in .eslintrc config...
I think you can close this issue as no modifications are needed...

**Comment by willdurand** [comment]
That's true, mmm. Not sure when that happened.
