### ISSUE TITLE
Only retrieve file info when that's all we need, in the Compare view

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1599]
Similar to https://github.com/mozilla/addons-code-manager/issues/1590, this issue is about adjusting the code for the Compare view to use the new `file_only` param to make sure that we only request file information if we already have version information for the current version.

This ended up requiring a huge refactoring (with 1,344 additions and 1,390 deletions) so I'm going to try to break that up into smaller patches, where possible, and I'll create issues for them referencing this issue.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on dev:
- the call to `reviewers/addon/{addonId}/versions/{versionId}/?file=filename` is not present in the network for Compare pages.
- only the `file_only:true` parameter is available when loading a new file for 2 particular versions in compare view. This is also applicable for the Browse view.
