### ISSUE TITLE
Code coverage reporting appears to be broken

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-code-manager#1609]
See also https://codecov.io/gh/mozilla/addons-code-manager 

<img width="1440" alt="Commits_⋅_mozilla_addons-code-manager_-_Codecov" src="https://user-images.githubusercontent.com/1514/83891060-88070e80-a744-11ea-88be-898617fae26c.png">

**Comment by bobsilverberg** [comment]
I don't see any info in their UI other than the generic message "There was an error processing coverage reports." I have sent an email to their support address to see if they can help.

**Comment by bobsilverberg** [comment]
I think I found a fix. PR opened.
