### ISSUE TITLE
Allow CodeOverview to render the content of diffs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1623]
Currently, in Compare mode, the `CodeOverview` component will render its content based on the content of the current version of the file being viewed, rather than based on the content of the diff being viewed. This is not ideal, as the CodeOverview doesn't show an accurate representation of the file being viewed onscreen, and it also causes some other issues including:
- We have to retrieve both the diff and the current version of the file for every Compare page
- It complicates things for the big refactoring that I am doing that will allow for retrieving only the diff (and not the whole version) when loading a new file in Compare mode

This issue is about changing the CodeOverview so that it will render its content based on the content of the diff.

Note that there may be minor issues with anchors from the CodeOverview back to the main CodeView when a line appears twice in a diff (e.g., line 3 appears as inserted *and* deleted), but this seems like a minor issue considering the fact that the anchors for diffs are already quite likely to be completely wrong due to the fact that the CodeOverview isn't based on the diff at all.

**Comment by AlexandraMoga** [comment]
@bobsilverberg I think this issue might have broken both the code overview and the diffs in compare pages. File contents are not loaded in either of the pages - they're stuck on "Loading linter information...":

![image](https://user-images.githubusercontent.com/31961530/84767783-a9d18280-afdb-11ea-9b1b-9edb0055493e.png)

**Comment by bobsilverberg** [comment]
@AlexandraMoga That's odd. I tested this locally and it worked fine. Is every file broken, or just particular ones? Can you provide some links on dev that are broken?

**Comment by bobsilverberg** [comment]
@AlexandraMoga I can see the issue on dev, but I don't think it has anything to do with the patch for this issue. Can you please file a separate issue about it, and I can update it with some more details?

**Comment by AlexandraMoga** [comment]
@bobsilverberg I've filed #1626

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified if the codelines are highlighted as expected when the code overview is used and also some keyboard navigation to the next change or next linter message on the compare pages.

One thing noticed:
for a file which contains edited codelines such as [this file](https://code.addons.allizom.org/en-US/compare/1004704/versions/2477733...2477734/?messageUid=fc3aca5dedc7479bada68ddfac5dde52&path=about.css) the overview has 36 lines yet the diff shows 31 lines. If I click line 36 in the overview - there is no response. 

![overview](https://user-images.githubusercontent.com/33448286/85726384-b2723900-b6fe-11ea-903d-fa584259d55e.gif)

**Comment by bobsilverberg** [comment]
> @bobsilverberg I verified if the codelines are highlighted as expected when the code overview is used and also some keyboard navigation to the next change or next linter message on the compare pages.
> 
> One thing noticed:
> for a file which contains edited codelines such as [this file](https://code.addons.allizom.org/en-US/compare/1004704/versions/2477733...2477734/?messageUid=fc3aca5dedc7479bada68ddfac5dde52&path=about.css) the overview has 36 lines yet the diff shows 31 lines. If I click line 36 in the overview - there is no response.
> 

I knew there might be some weirdness with anchors, but it's worth looking into. Can you please file an issue specifically for this?

**Comment by ioanarusiczki** [comment]
@bobsilverberg Yes, I filed a separate issue https://github.com/mozilla/addons-code-manager/issues/1632

I verified this issue on AMO stage - FF76(win10).
