### ISSUE TITLE
Call validation endpoint the same way we call other APIs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1631]
This is a follow up from https://github.com/mozilla/addons-code-manager/pull/1628.

As per the suggestion at https://github.com/mozilla/addons-code-manager/pull/1628#pullrequestreview-436800937, in code-manager we should construct the API endpoint similar to how we call other APIs, rather than using a URL provided in another API response. Once that lands we could remove the `validation_url_json` from the response of the Browse and Compare APIs on addons-server, but maybe we want to keep it there anyway, for other potential consumers?

For QA:

Nothing should change in code manager. Please check for regressions on the Browse and Compare pages.

**Comment by ioanarusiczki** [comment]
@bobsilverberg This was verified for https://github.com/mozilla/addons-code-manager/issues/1645#issuecomment-657535210
