### ISSUE TITLE
Remove references to `oldRevision` and `newRevision` from the code

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1633]
This is part of a large refactor that is required for #1599.

Neither `oldRevision` nor `newRevision` are used anywhere in our code, so, for cleanup purposes, we should remove any references to them.

For QA:

There should be no observable changes in the app. Please check for regressions on the Compare page.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Looks good to me.
Verified on AMO dev with FF77(Win10).
