### ISSUE TITLE
Introduce different types for external files with content vs diffs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1635]
This is part of a large refactor that is required for #1599.

We're getting rid of `CompareInfo` and replacing it with version files which contain diffs, which are similar to the existing version files which contain content. This results in a lot of type churn in existing code that uses the existing version files, so it makes sense to extract these changes out into a separate patch.
For QA:

There should be no observable changes in the app. Please check for regressions on the Browse page.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Looks good to me. 
Verified on AMO dev - FF76(Win10).
