### ISSUE TITLE
Make query param handling more robust

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#164]
As a follow-up to https://github.com/mozilla/addons-code-manager/issues/157, I'd like to see some improvements that will help us scale the codebase for future work:

1. Support query string values that have spaces or special characters. This should be as easy as:

```diff
diff --git a/src/api/index.tsx b/src/api/index.tsx
index ff6c939..9b58a53 100644
--- a/src/api/index.tsx
+++ b/src/api/index.tsx
@@ -1,3 +1,4 @@
+import url from 'url';
 import log from 'loglevel';
 
 import { ApiState } from '../reducers/api';
@@ -45,11 +46,7 @@ export const callApi = async ({
   }
 
   if (Object.keys(query).length) {
-    const queryString = Object.keys(query)
-      .map((k) => `${k}=${query[k]}`)
-      .join('&');
-
-    adjustedEndpoint = `${adjustedEndpoint}?${queryString}`;
+    adjustedEndpoint = `${adjustedEndpoint}${url.format(query)}`;
   }
 
   try {
```

2. Make sure `undefined` or `null` object values do not pass empty parameters to the API, [like this](https://github.com/mozilla/addons-frontend/blob/aabbd8097c58ae1bc5bb48bc942a63bf6bfd2e12/src/core/api/index.js#L30). That has triggered Django errors in the past.

3. When testing query string parameters, we cannot rely on object key order, [as this does](https://github.com/mozilla/addons-code-manager/blob/9b93ab5627578426eafed58dde14735dd0a15ed3/src/api/index.spec.tsx#L142). It will *probably* work but it's non-deterministic and it's easy to avoid, anyway. Let's add [a helper similar to this](https://github.com/mozilla/addons-frontend/blob/aabbd8097c58ae1bc5bb48bc942a63bf6bfd2e12/tests/unit/helpers.js#L909-L931) to make query string assertions deterministic.

**Comment by AlexandraMoga** [comment]
@willdurand I understand that this issue  and issue #666 were connected. I've verified that the error identified in #666 is no longer reproducible. 

I've also verified that navigation by file path is still working in the browse and compare pages.

If you think there is more to be verified here, please let me know. Otherwise, I will mark this issue as verified fixed.

**Comment by willdurand** [comment]
> If you think there is more to be verified here, please let me know. Otherwise, I will mark this issue as verified fixed.

Looks good, thanks!
