### ISSUE TITLE
Fix logic for analyticsPath for local dev

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1640]
When I landed https://github.com/mozilla/addons-code-manager/pull/1571 to disable debug mode for GA by default, I missed one thing, which was causing the debug library to still be loaded for local development. This issue is about changing that.

For QA:

There's not need to verify this specific change, as it only relates to running the site locally, but please do check for regressions in the calls to GA.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I see the calls to GA present on Browse and Compare pages. - FF77(Win10)
I used https://github.com/mozilla/addons-code-manager/issues/1423 and https://github.com/mozilla/addons-code-manager/issues/1543 as reference.
