### ISSUE TITLE
Remove code for base_file

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1643]
We used to need the `base_file` from the API response to construct the legacy file viewer links, but we do not need that info anymore, so it can be removed. This is part of the big refactor I did for https://github.com/mozilla/addons-code-manager/issues/1599, so I figured I'd split it out into a separate issue to make the patch for that a bit smaller.

For QA:

Check for regressions on the Compare page and verify that legacy file viewer links still work.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
- Legacy viewer links redirect to the legacy viewer and I did not find issues on compare pages.

Verified on AMO dev - FF78(Win10).
