### ISSUE TITLE
Add reducer support for retrieving and storing diff files

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#1645]
This is part of a large refactor that is required for #1599.

This will add support to the `versions` reducer to retrieve and store individual diff files. This is likely the last part that can be split out of the work needed for #1599. The next patch will make use of all of the bits that have been landing for this.

For QA:

There should be no observable changes in the app. Please check for regressions on the Browse and Compare pages.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified: file navigation, keyboard shortcuts, draft comments, code overview section, buttons - on Browse and Compare view. 
Looks good to me on dev - FF78(Win10).
