### ISSUE TITLE
Lag when clicking an anchor (line number) in a compare page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#1653]
### Describe the problem and steps to reproduce it:

1. Open a compare page, it's easier to see the lag with a rather large content but it will happen with any file
2. Click somewhere in the middle of the content or even `CodeOverview`

### What happened?

We can notice a lag.

### What did you expect to happen?

No lag.

**Comment by AlexandraMoga** [comment]
See also #630

**Comment by willdurand** [comment]
> See also #630

Oh right, so this is definitely not new..
