### ISSUE TITLE
Set up code linting

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#17]
Set up our common linting rules similar to [addons-frontend](https://github.com/mozilla/addons-frontend/blob/d69965f80b615a2ba57adb777e56f33f73d97afd/.eslintrc).

We will be using TypeScript instead of Flow but TS linting can be done in a separate issue.

**Comment by willdurand** [comment]
Note: `tslint` is recommended over `eslint` when using TypeScript.

**Comment by kumar303** [comment]
As discussed in https://github.com/mozilla/addons-code-manager/pull/59/files#r250526915 let's be sure to add a lint rule to enforce arrow functions everywhere.
