### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#1728]
This issue is a _meta_ issue, not very specific. We updated lots of dependencies lately so let's capture this here and ask QA to verify that the app continues to work.

For QA: please do a sanity check to make sure there is no obvious breakage.

**Comment by ioanarusiczki** [comment]
@willdurand Looking over Browse and Compare pages, I think it's just the usual. 
Verified on AMO stage - FF81(Win10).
