### ISSUE TITLE
Do we want to aim for 100% type coverage?

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#175]
I notice that when running `yarn type-coverage`, the command passes, but we do not have 100% coverage. On current master we have 99.45%, and running `yarn type-coverage --detail` yields:

```
$ type-coverage --detail
/addons-code-manager/src/server/index.tsx:29:9: authToken
/addons-code-manager/src/server/index.tsx:36:20: authToken
/addons-code-manager/src/server/index.tsx:123:11: modifyResponse
/addons-code-manager/src/server/index.tsx:141:13: modifyResponse
/addons-code-manager/src/configureStore.tsx:32:7: middleware
/addons-code-manager/src/configureStore.tsx:34:5: middleware
/addons-code-manager/src/configureStore.tsx:37:5: middleware
/addons-code-manager/src/api/index.tsx:70:12: error
/addons-code-manager/src/api/index.tsx:71:45: error
/addons-code-manager/src/api/index.tsx:74:7: error
/addons-code-manager/src/server/index.spec.tsx:73:25: header
/addons-code-manager/src/test-helpers.spec.tsx:14:15: WrappedComponent
/addons-code-manager/src/test-helpers.spec.tsx:16:19: WrappedComponent
2344 / 2357 99.45%
type-coverage success.
```

I'm not sure if we can fix all of these, but we can fix some of them. Is this something we should do? Should we also try not to commit new code that adds anything to this list, if possible?

**Comment by bobsilverberg** [comment]
Nobody commented on this. What do you think @willdurand and @kumar303?

**Comment by willdurand** [comment]
> I'm not sure if we can fix all of these, but we can fix some of them. Is this something we should do? Should we also try not to commit new code that adds anything to this list, if possible?

We could try to fix some of them yeah. I think the travis check is reasonable, so if it does not fail, we should be good. The problem with a 100% rule is that it is not very doable in real life.

**Comment by kumar303** [comment]
I had it set to require [99% coverage](https://github.com/mozilla/addons-code-manager/blob/master/package.json#L108) just to allow some wiggle room. If it becomes a problem, we can revisit that requirement. 

Adding type coverage to the test files is interesting. There are definitely cases where we need things to be lax in the tests. I've noticed that when you use `jest.fn()`, all type safety goes out the window. It's a feature, I guess! It does seem like maybe the expected thing.

**Comment by willdurand** [comment]
So I guess we all agree that the 99% threshold makes sense because 100% seems unrealistic. Travis CI will warn us if we don't have enough coverage.
