### ISSUE TITLE
Consider permanently showing current file info panel

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-code-manager#1765]
The "Information" info panel for the current file is collapsed by default and for many monitors there is a lot of blank space in the overall left panel because lots of extensions don't have too many files or not all folders are expanded. We could use some of that space to show the "Information" panel permanently, like so:

<img width="581" alt="code-manager" src="https://user-images.githubusercontent.com/873258/97452456-0e5eff80-1935-11eb-83dd-68c57a2f14f6.png">

We can also drop the "Version" section in that panel as the version is already shown in the top bar.

This is especially handy when coming across a file that has been truncated, but you still want to take a look at it. Viewing the full file in code-manager can make the entire browser hang (and you won't know in advance whether it would), so I have been using the "Download" link regularly to open the file in a local code editor.

@kewisch Do you have an opinion on this?

**Comment by bobsilverberg** [comment]
@wagnerand Just to confirm, you are okay with having the Information panel permanently expanded (i.e., it's not possible to collapse it)? I ask because doing that is quite simple. It would take some more work to have it always expanded, but leave the ability to collapse it if desired.

**Comment by wagnerand** [comment]
@bobsilverberg I'd be ok with that, yes. Let's see if Philipp has a strong opinion.

**Comment by bobsilverberg** [comment]
I've got a patch ready to go, just waiting on feedback from @kewisch.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
I verified on dev - FF82(Win10):
- the version has been removed, I don't know if instead of "Information" should be "Current file information":

![Layout](https://user-images.githubusercontent.com/33448286/98364020-b0b76b00-2038-11eb-8b42-b625eb42937d.png)

- Information of the current file is kept with Keyboard Shortcuts too: 

![Collapse this panel](https://user-images.githubusercontent.com/33448286/98364196-055ae600-2039-11eb-9d5d-902e36a45b6a.png)

Let me know if it's alright right now and I'll mark this verified. 
Thanks!

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki! I think it can be marked as verified. @wagnerand What do you think of changing the section's title from "Information" to "Current file information" or something similar?

**Comment by wagnerand** [comment]
> @wagnerand What do you think of changing the section's title from "Information" to "Current file information" or something similar?

Sounds good to me.

**Comment by bobsilverberg** [comment]
> > @wagnerand What do you think of changing the section's title from "Information" to "Current file information" or something similar?
> 
> Sounds good to me.

Do you mind filing an issue for it?

**Comment by ioanarusiczki** [comment]
@bobsilverberg Done https://github.com/mozilla/addons-code-manager/issues/1786
