### ISSUE TITLE
Code Manager prevent Notice on deleted lines in compare

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-code-manager#1777]
Example:
`https://code.addons.mozilla.org/en-US/compare/1009097/versions/5079240...5083154/?path=inject.js`

IMHO, the notice for the deleted line is not necessary and removing it would make the page tidier and require less processing.

![image](https://user-images.githubusercontent.com/6458876/90441618-836cb800-e0ee-11ea-90c8-b98c3f6b838b.png)

**Comment by bobsilverberg** [comment]
@wagnerand It would be helpful to have something on dev that I can use to test this. Would you know of a review on dev that has a message on a deleted line? If not, would it be possible to upload this same add-on from this review on dev so I can use it as an example? Or perhaps something much simpler, but that would have a message on a deleted line?

**Comment by bobsilverberg** [comment]
@wagnerand Nevermind, I found one!

**Comment by bobsilverberg** [comment]
Do we only want to hide the message on a deleted line if there is a corresponding new line with the same message, as in the example above? I.e., in the example above, the same message is displayed for deleted line 321 and inserted line 321. There are cases where we only have a deleted line, and no corresponding insertion. Should we still hide the message for the deleted line in that case?

**Comment by wagnerand** [comment]
@bobsilverberg I think it's fine to hide validation messages for any deleted lines, regardless of validation messages in added lines.

**Comment by willdurand** [comment]
> @bobsilverberg I think it's fine to hide validation messages for any deleted lines, regardless of validation messages in added lines.

Say some code with validation messages has been moved, sometimes it creates deleted/added code. Will we get the validation messages anyway? Not showing validation messages seems to be a risk to me.

**Comment by wagnerand** [comment]
> Say some code with validation messages has been moved, sometimes it creates deleted/added code. Will we get the validation messages anyway? Not showing validation messages seems to be a risk to me.

If the code is moved to a different place then I would expect that place to show the validation message, no?

**Comment by bobsilverberg** [comment]
You guys understand the way these messages are generated better than me, but what @wagnerand is saying makes sense to me. If code that generates a message has been moved, the message should show up on that new line. If the code has been removed entirely, then is the message relevant anymore?

**Comment by erosman** [comment]
IMHO,  in comparison, the deleted code shouldn't be parsed for errors/messages at all. Only the current code should be checked.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this issue on AMO dev with FF82(Win10):

- in case the lines are deleted - the linter messages are no longer displayed.

https://code.addons-dev.allizom.org/en-US/compare/620304/versions/1692308...1692309/?path=inject.js#D258
https://code.addons-dev.allizom.org/en-US/compare/620304/versions/1692308...1692309/?path=inject.js#N298

- an example of modified code line too:

https://code.addons-dev.allizom.org/en-US/compare/620305/versions/1692310...1692311/?path=inject.js#D326
