### ISSUE TITLE
Add information for contributors

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#18]
Add information for contributors, similar to all add-ons projects. See https://github.com/mozilla/addons-frontend/

**Comment by bobsilverberg** [comment]
@kumar303 Do you mean this: https://github.com/mozilla/addons-frontend/blob/master/CONTRIBUTING.md, or something else? We already have a README.md that documents some of what a contributor needs to know.

**Comment by kumar303** [comment]
Yes, the readme already includes instructions for how to develop new features for `addons-code-manager`. And, yes, similar to the guide you linked to, this issue is about adding a `CONTRIBUTING.md` file (which github links to in important places) with maybe things like this:

* How to find issues to work on
* What issues *not* to work on
* What a PR should include (like the frontend guide)
