### ISSUE TITLE
Handle user-entered urls in the API being an object containing both wrapped and raw urls in api/v5?

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-code-manager#1802]
The changes in the fix for mozilla/addons-server#11206 are breaking in api/v5 and may require some changes to the API.  

At a first glance I don't think this repo will be affected - the /addons, /blocklist, /collections, and /hero endpoints have changed slightly.  I assume of those only /addons could used by addons-code-manager and the actual properties (`contributions`, `homepage`, `support_url`) are used.

This issue can be closed if, after investigation, no work is required.

**Comment by eviljeff** [comment]
I've taken a quick look via a search and can't see any of the affected properties are used.  @bobsilverberg can you confirm and close if correct.

**Comment by bobsilverberg** [comment]
> I've taken a quick look via a search and can't see any of the affected properties are used. @bobsilverberg can you confirm and close if correct.

It looks like the only APIs used are those residing under `reviewers/addon/...`, plus a couple under `accounts`, specifically `accounts/session` and `/accounts/profile/`. I notice that `/accounts/profile/` does have a `homepage` property which is a URL, as well as a `picture_url` which is also a URL, but it doesn't look like those have been touched by the patch for https://github.com/mozilla/addons-server/issues/11206.

Given all of that, I believe this can be closed. Is it accurate that we never outgoingify those properties of an account?

**Comment by eviljeff** [comment]
We don't wrap the account profile homepage for some reason ([noted](https://github.com/mozilla/addons-frontend/issues/9911#issuecomment-741790074)) but something to be aware of if it's changed in the future.  `picture_url` is always an AMO url.
