### ISSUE TITLE
Node 14

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#1984]
With Node 16 already available, we can switch from Node 12 to Node 14 in the coming weeks. This issue is about doing it.

**Comment by willdurand** [comment]
cc @bqbn

**Comment by ioanarusiczki** [comment]
@willdurand I'm going to test this on AMO stage, at release testing.

**Comment by ioanarusiczki** [comment]
@willdurand 
Verified on AMO stage - FF90(Win10).
