### ISSUE TITLE
Provide an outline image of the code of a file including where linter warnings appear

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#200]
This is a vertical bar that appears to the left of the code of a file, when viewing a file, and includes colouring to indicate where in the fil linter warnings exist. It could also potentially be used to show where in the file comments exist (with a different colour), once we implement inline comments.

Here's an example from the current reviewer tools:

<img width="981" alt="screenshot 2019-02-13 11 44 05" src="https://user-images.githubusercontent.com/142755/52728115-b0359180-2f84-11e9-9a6a-c612f19f6467.png">

**Comment by bobsilverberg** [comment]
I don't recall if we decided to include this in the current MVP or not.

**Comment by kumar303** [comment]
We do need to somehow indicate that a line of a file has a notice so I'll mark it as mvp. It might be easier just to show the notice inline rather than use a marker but we'd then need a button to hide the notice, too.

**Comment by willdurand** [comment]
> We do need to somehow indicate that a line of a file has a notice so I'll mark it as mvp. It might be easier just to show the notice inline rather than use a marker but we'd then need a button to hide the notice, too.

Maybe we could inline the notices in a way that is similar to how we'll inline comments?

**Comment by kumar303** [comment]
Yeah, we can experiment with it and get some feedback from reviewers once we have a screen. The old approach of hiding notices behind a marker seems like it would encourage reviewers to ignore notices but I'm not sure.

**Comment by willdurand** [comment]
Quick prototype based on #285 and #290:

![screen shot 2019-02-27 at 18 20 34](https://user-images.githubusercontent.com/217628/53509602-64becf80-3abc-11e9-92b4-efd92a6d7e3b.png)

**Comment by kumar303** [comment]
Yeah, I was thinking inline like that, too. We just need to make sure we are addressing the right user story for how reviewers want to see validation errors.

**Comment by kumar303** [comment]
This issue was originally filed with the assumption that reviewers wanted to retain the current tool's feature of hiding inline linter messages by default. In the current code manager, inline linter messages are not hidden by default. Let's get some feedback on that from real world usage before implementing the old style.

In the meantime, I'm closing this issue. Once we get user feedback we can open new issues as needed.

The description of this issue suggests that we need a better way to navigate inline linter messages. I'm moving that to: https://github.com/mozilla/addons-code-manager/issues/523

**Comment by wagnerand** [comment]
I do think some kind of visual outline/map of annotations makes sense. When we add reviewer (and eventually developer) annotations, that would be helpful to see as well, not just for linter annotations.

**Comment by kumar303** [comment]
> When we add reviewer (and eventually developer) annotations...

Yeah, I think we will need to add an entirely new UX for this when we get there. IMO the best way to address it is first with user stories and next with prototypes and quick iterations based on feedback. If you have ideas for new user stories that aren't filed yet, please file them.

**Comment by kumar303** [comment]
> I do think some kind of visual outline/map of annotations makes sense.

After IRC discussion, I realized I'd had missed how the current tool attempted a file overview UI! It is buggy but I updated https://github.com/mozilla/addons-code-manager/issues/523 to explain the intent of the feature.
