### ISSUE TITLE
Set up continuous integration for testing

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#21]
TravisCI was working for addons-frontend so let's use that

**Comment by willdurand** [comment]
We probably need a GitHub admin to enable the Travis service.

**Comment by willdurand** [comment]
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1520461

**Comment by kumar303** [comment]
We should run two versions of Node in CI: active LTS and upcoming LTS
