### ISSUE TITLE
Deploy Storybook on gh-pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#215]
Let's deploy our Storybook on `gh-pages`.

**Comment by willdurand** [comment]
@muffinresearch could you please add a new GitHub personal access token in Travis CI: https://travis-ci.org/mozilla/addons-code-manager/settings (as an Environment Variable named `GH_TOKEN`)?

**Comment by muffinresearch** [comment]
> @muffinresearch could you please add a new GitHub personal access token in Travis CI: https://travis-ci.com/mozilla/addons-code-manager/settings (as an Environment Variable named `GH_TOKEN`)?

@willdurand done.
