### ISSUE TITLE
Support addons-server SessionIDAuthentication

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-code-manager#2156]
https://github.com/mozilla/addons-server/pull/18475 adds a new internal authentication method, that would be specified in the authorization header as Session xxxx (rather than Bearer xxxx). addons-fronted made the change in https://github.com/mozilla/addons-frontend/issues/11110.  The value is stored in the sessionID cookie - it's the django session ID. We need to change addons-code-manager too so it uses this cookie rather than frontend_auth_token and specifies the value in the authorization header.

note: The cookie/auth token is no longer a JWT, it's just a session id.

**Comment by eviljeff** [comment]
QA: the changes here were the same as frontend - I wouldn't worry about the refresh and access tokens expiring, just focus on normal login and api requests.

**Comment by ioanarusiczki** [comment]
@eviljeff I tried on -dev and -stage to login to a code manager page -> If I access "Content" from an addon review page I must login to code manager but after I enter credentials I still won't have access. 

I think this issue caused the regression: 

![code manager login fails](https://user-images.githubusercontent.com/33448286/155290112-ae47efcc-13c7-4c05-ad27-dceebaf55d72.gif)

**Comment by eviljeff** [comment]
@ioanarusiczki it's hopefully working now on dev

**Comment by ioanarusiczki** [comment]
@eviljeff Works on -dev , not yet on -stage.

**Comment by eviljeff** [comment]
@ioanarusiczki thanks for the confirmation about -dev.  I've just cherry-picked the commit to stage now.

**Comment by ioanarusiczki** [comment]
@eviljeff 
- Login works on AMO stage too
- I could browse on code manager pages using keyboard navigation or the code overview , leave comments, download a file and so on. 

I think it should be alright.
