### ISSUE TITLE
Remove sentry

### ISSUE THREAD

**Issue by diox** [mozilla/addons-code-manager#2165]
Similar to https://github.com/mozilla/addons-frontend/issues/10028 sentry isn't really useful for addons-code-manager. There has been 0 issues in the past few months on dev/stage/prod, [the PR to upgrade the client](https://github.com/mozilla/addons-code-manager/pull/2093) has been sitting around for a while with no progress, let's remove it entirely instead.

**Comment by ioanarusiczki** [comment]
@diox I'll take a look code-manager - browse/compare views + it's features

**Comment by ioanarusiczki** [comment]
@diox Ups, sorry , now I saw the label.

**Comment by diox** [comment]
You can verify that code-manager still works, that should be enough. (that's why I marked it as qa-, I figured anything would be caught in the normal sanity checks)

**Comment by ioanarusiczki** [comment]
@diox Looks good to me. I verified it on AMO stage FF98(Win10).
