### ISSUE TITLE
Stop deploying storybook to gh-pages ; build it when needed instead

### ISSUE THREAD

**Issue by diox** [mozilla/addons-code-manager#2169]
We're currently building and deploying storybook on each commit to `master`, through `addons-robot`, which has write access to the repo.

I'd like to remove that permission from addons-robot for safety. I propose we do something similar to [what was done in the linter](https://github.com/mozilla/addons-linter/issues/3853): build it ourselves when needed, and commit the result. CI will still build it to check that it hasn't changed, and fail the build if it did, forcing you to build and commit the result if it changed.

The drawback with this method is that sometimes the diff will be unnecessary large, especially as storybooks come with a lot of JavaScript we don't necessarily care about. I think it's an acceptable trade-off in the name of increased security, but please discuss if you disagree.

**Comment by bobsilverberg** [comment]
If it's a security concern, then I think it's ok to do this. We should test to make sure that building it locally works, as I recall an issue with that at some point.

**Comment by diox** [comment]
To simplify the setup I'll disable storybook auto-deploy now anyway. We can generate it manually if we make changes to components, which hasn't happened in a while - the diff would be bad, but this should be a rare occurrence given the state of the project.

**Comment by diox** [comment]
On top of the commit in #2188 I've rotated the token and removed write access from `addons-robot`.
