### ISSUE TITLE
Remove code relating to canned responses

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#2206]
We are removing the code for canned responses from `addons-server`. `addons-code-manager` had intended to make use of canned responses, but that feature was never implemented. There exists some code in code manager that references canned responses that was added in anticipation of this feature. In order to keep code manager accurate, and probably also to avoid exceptions in some cases, we should remove the code that references canned responses. Here is what needs to be addressed:

- [ ] Remove references to canned responses in api code ([here](https://github.com/mozilla/addons-code-manager/blob/master/src/api/index.tsx#L423) and [here](https://github.com/mozilla/addons-code-manager/blob/master/src/api/index.tsx#L429).
- [ ] Remove references to canned responses in the comments reducer ([here](https://github.com/mozilla/addons-code-manager/blob/master/src/reducers/comments.tsx#L22-L30) and [here](https://github.com/mozilla/addons-code-manager/blob/master/src/reducers/comments.tsx#L331)).
- [ ] Remove reference to canned responses in the [Comment component](https://github.com/mozilla/addons-code-manager/blob/master/src/components/Comment/index.tsx#L163).
- [ ] Update [test helper](https://github.com/mozilla/addons-code-manager/blob/master/src/test-helpers.tsx#L881).
- [ ] Update tests for the code changed above.

**Comment by diox** [comment]
I agree, this plan and https://github.com/mozilla/addons-server/issues/20353#issuecomment-1433084750 sound good to me.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I tried leaving/editing/deleting comments on browse/compare pages and it works as expected. 

Verified on AMO stage.
