### ISSUE TITLE
Move loadCurrentUser in App to a thunk

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#237]
As of https://github.com/mozilla/addons-code-manager/issues/12 we can move the async logic in `App.componentDidUpdate` to a thunk. This will make testing easier.

https://github.com/mozilla/addons-code-manager/blob/8da316284e1dfd9790300402db8499b2dfc9983d/src/components/App/index.tsx#L54-L67

**Comment by willdurand** [comment]
Sorry but this is done in #218.

**Comment by kumar303** [comment]
No need to apologize. Thanks for doing that 😎 

Let's consider this a dupe of https://github.com/mozilla/addons-code-manager/issues/181
