### ISSUE TITLE
Dispatch an actual loading state in fetchCurrentUserProfile

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#239]
The approach in https://github.com/mozilla/addons-code-manager/pull/143 inferred a loading state from missing parameters. Now that we have a thunk in https://github.com/mozilla/addons-code-manager/pull/218 we can dispatch an actual loading state from `fetchCurrentUserProfile` while the user profile gets fetched.

This will make the loading state more robust and predictable. For example, you currently see a loading state after logging out which was not intended.

**Comment by willdurand** [comment]
Note: the loader should be displayed as early as possible so that there is no visual glitch when the page loads, i.e. it should not be enabled before fetching the current user profile, it should be enabled by default and turned off when our code starts doing something.

**Comment by kumar303** [comment]
I don't fully understand your comment but let me know if the patch in https://github.com/mozilla/addons-code-manager/pull/252 is missing something related to this.

**Comment by willdurand** [comment]
> I don't fully understand your comment but let me know if the patch in #252 is missing something related to this.

ah well, me neither. What I meant is that, on page refresh, we should not have this flow:

```
content --> loading page --> content
```

It should be:

```
loading page --> content
```

No matter the authentication state.

Looks like this is covered by your patch, though.
