### ISSUE TITLE
Deploy dev, stage, prod

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#25]
This may require separate issues for ops. We want to deploy the app to dev, stage, and prod similar to how we do for https://github.com/mozilla/addons-frontend/

Something like:
- Dev: `code.addons-dev.allizom.org`
- Stage: `code.addons.allizom.org`
- Prod: `code.addons.mozilla.org`

Or maybe at the nginx level:
- Dev: `addons-dev.allizom.org/en-US/code/`
- Stage: `addons.allizom.org/en-US/code/`
- Prod: `addons.mozilla.org/en-US/code/`

**Comment by willdurand** [comment]
-dev has been deployed! 🎉

**Comment by willdurand** [comment]
I filed https://github.com/mozilla/addons-code-manager/issues/512 for stage.

**Comment by willdurand** [comment]
I filed https://github.com/mozilla/addons-code-manager/issues/513 for prod.

We can close this issue now.
