### ISSUE TITLE
Link to a URL for viewing a single file (browse page)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#286]
### Describe the problem and steps to reproduce it:

- Go to a version such as http://localhost:3000/en-US/browse/502955/versions/1541798/
- Click on a file, such as `background.js` to review it
- Share the link with another reviewer

### What happened?

The URL does not point to the `background.js` file so you can't share a direct link

### What did you expect to happen?

The URL should point directly to `background.js` so you can share it.

This is a follow-up to https://github.com/mozilla/addons-code-manager/issues/108

**Comment by willdurand** [comment]
> The URL should point directly to `manifest.json` so you can share it.

I don't think this is really relevant here because this is the default file, so sharing the default url should always load the default file. I'll update the issue description to reflect that.

**Comment by willdurand** [comment]
I also changed the title of this issue to target the browse page only. I'll file a similar issue for the compare page.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with FF66, WIn10x64

When selecting a specific file in the file tree (by clicking on it or by keyboard navigation) the `path` to the file location is added to the URL => link to a specific file can be shared 

Examples:

1. https://code.addons-dev.allizom.org/en-US/browse/8542/versions/1655535/?path=content-script%2Fviews%2Fbasic-auth%2Fbasic-auth.html
2. https://code.addons-dev.allizom.org/en-US/browse/616653/versions/1655542/?path=options.js

![2019-04-16_13-36-07](https://user-images.githubusercontent.com/31961530/56203586-3ab27400-604e-11e9-94b8-d0cb11ecf71f.gif)
