### ISSUE TITLE
Create a `VersionChooser` component for the compare page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#293]
In order to ship #111, we need a version chooser that relies on this API patch: https://github.com/mozilla/addons-server/issues/10432.

See screenshot below:

![](https://user-images.githubusercontent.com/55398/52150767-95832480-2636-11e9-85c6-81a8cbb1e3ab.png)

**Comment by kumar303** [comment]
This also gives us an opportunity to talk with reviewers and figure out their wishes for how to select versions. The old dropboxes were confusing (to me, anyway) so I don't think we should replicate them as is.

**Comment by willdurand** [comment]
> This also gives us an opportunity to talk with reviewers and figure out their wishes for how to select versions. The old dropboxes were confusing (to me, anyway) so I don't think we should replicate them as is.

/cc @mozilla/add-on-admin-reviewers

**Comment by wagnerand** [comment]
The thing most confusing about selecting versions was that the newer one has to be selected in the left dropdown. But after a while, I got used to the flow. Maybe just flipping the two is enough?

I am open to other approaches. I'd be interested to hear what was confusing for you @kumar303.

**Comment by kumar303** [comment]
> The thing that's most confusing about selecting versions was that the newer one has to be selected in the left dropdown.

Yeah, I agree

> I'd be interested to hear what was confusing for you

For someone new to the UI, it doesn't make a lot of sense. For example:
- What does the *Go* button do?
- What is the meaning of the left dropdown? What's the meaning of the right?
- What does it mean to select a high version on the left and a lower version on the right or vice versa?
- Why is the right version grayed out sometimes?

I know the answer to some of these questions but I think the UI could be a lot more intuitive while still keeping it simple and concise.

**Comment by willdurand** [comment]
Could it be similar to the GitHub compare page?

![](https://help.github.com/assets/images/help/branch/comparing_branches.png)

**Comment by wagnerand** [comment]
>     * Why is the right version grayed out sometimes?

Hah, I don't definitely know the answer to that one. I could guess...

All good points, thanks!

**Comment by willdurand** [comment]
Very first prototype:

![screen shot 2019-02-28 at 16 45 04](https://user-images.githubusercontent.com/217628/53578584-38688900-3b78-11e9-9c31-6a47d1e83212.png)
