### ISSUE TITLE
Add more direct coverage to map* functions in CodeView/utils.tsx

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#299]
Some map functions in `CodeView/utils.tsx` don't have test cases. These functions are covered only because they are used in the `CodeView` component.

**Comment by kumar303** [comment]
At a glance, some extra things that need testing:
- recursion across a few levels, just for sanity
- creating child elements with properties and class names
- creating child elements without a tag name. I guess those are text nodes?
