### ISSUE TITLE
Implement footer for file viewer

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#326]
This is an issue that was discussed in our review of the current reviewer tools and I neglected to file.

The file viewer should contain a footer which should include at least the file hash and a ~~download link~~ (this will be added in https://github.com/mozilla/addons-code-manager/issues/353) for the file.

We should add a screenshot of the current footer to this issue.

**Comment by bobsilverberg** [comment]
Here's an screenshot from the current reviewer tools showing the footer. It currently includes:
- a download link
- the version "number"
- the file size
- the SHA256 hash
- the mime type

<img width="981" alt="screenshot 2019-02-13 11 44 05" src="https://user-images.githubusercontent.com/142755/52728115-b0359180-2f84-11e9-9a6a-c612f19f6467.png">

@EnTeQuAk I noticed in the chat from the meeting yesterday that you confirmed that the download link was missing from the API response. Have you opened an issue to add that to the response?

**Comment by bobsilverberg** [comment]
Note that in the compare view, the footer is shown for both versions, for example:

![screenshot 2019-03-07 08 14 25](https://user-images.githubusercontent.com/142755/53959225-0f348500-40b1-11e9-864f-1f4a63b836d7.png)

**Comment by willdurand** [comment]
> @EnTeQuAk I noticed in the chat from the meeting yesterday that you confirmed that the download link was missing from the API response. Have you opened an issue to add that to the response?

We actually double-checked and the link is present. It is not documented though (but there is an `url` field in the response).

**Comment by bobsilverberg** [comment]
> We actually double-checked and the link is present. It is not documented though (but there is an url field in the response).

I checked as well, and the `url` field contains a link to the xpi file for the extension, not to the file that was requested. Perhaps there is a way to construct the download link using the contents of the `url` and the `path` of the entry, but I haven't been able to make that work.

@willdurand have you been able to generate a link to download an individual file from within the extension?

**Comment by willdurand** [comment]
Oh, sorry, I didn't check the content of the link.. :/ Could you file an issue on addons-server?

**Comment by bobsilverberg** [comment]
There was an issue filed to update the documentation, but that assumed the link was already available, which it is not. I updated that issue to request the download link in the response.

https://github.com/mozilla/addons-server/issues/10877

**Comment by willdurand** [comment]
This issue does not need an API. we have other issues to add missing information in the `FileMetadata` component.
