### ISSUE TITLE
Make linter message links open externally

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#328]
The LinterMessage component was added in https://github.com/mozilla/addons-code-manager/issues/295

Sometimes a message contains a URL. Let's make those links open in a new tab with `target=_blank`

Example:

<img width="772" alt="screenshot 2019-03-06 12 42 07" src="https://user-images.githubusercontent.com/55398/53905103-4c473b80-400d-11e9-9bb3-718ba823327d.png">

**Comment by eviljeff** [comment]
mentor @willdurand 
- can you add a few more details to explain what needs to be done (seems pretty straightforward)

**Comment by muffinresearch** [comment]
Note: this also needs adding `rel="noreferrer noopener"`  as well as the target attribute, see https://mathiasbynens.github.io/rel-noopener/

**Comment by diox** [comment]
Fixed by https://github.com/Tintinator, thanks!
