### ISSUE TITLE
Setup Analytics?

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#344]
Questions: do we want to setup G. Analytics on this project? Do we have Analytics on the existing old tool we are about to replace? Does it make sense to have Analytics for such a project? (I'd say no, but that's my opinion)

**Comment by muffinresearch** [comment]
I'm inclined to agree that it's probably not needed. 

@jvillalobos @wagnerand what do you think?

**Comment by jvillalobos** [comment]
We don't have analytics on the existing reviewer tools. While I can see some value in tracking stuff like the queues and main review pages (future project, maybe), I don't think we need to track anything under the file or diff viewer.

**Comment by willdurand** [comment]
Ok, then we don't add any Analytics 🥇
