### ISSUE TITLE
Create FileMetadata component

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#345]
This is a step towards #326. As this will need to be used in both the browse and compare views, it makes sense to make it a separate component.

Here's an screenshot from the current reviewer tools showing the footer. It currently includes:
- ~~a download link~~ (this is being deferred to #353)
- the version "number"
- the file size (Note that this currently just displays a number which represents the size of the file in bytes. I opened #355 as a follow-up to address this)
- the SHA256 hash
- the mime type

<img width="981" alt="screenshot 2019-02-13 11 44 05" src="https://user-images.githubusercontent.com/142755/52728115-b0359180-2f84-11e9-9a6a-c612f19f6467.png">

**Comment by willdurand** [comment]
Note: we might have a chance to rethink this component, i.e. it does not have to be a footer. It could be on the left side, or somewhere else for example.

**Comment by bobsilverberg** [comment]
> Note: we might have a chance to rethink this component, i.e. it does not have to be a footer. It could be on the left side, or somewhere else for example.

That's a good point, thanks @willdurand. I guess that's all the more reason to put it into a component, which could then be styled and/or positioned anywhere. I think it's still worthwhile to build it now to output the data we need. Do you agree?

**Comment by kumar303** [comment]
> I think it's still worthwhile to build it now to output the data we need.

Yes! We can always refine the UX later.

**Comment by willdurand** [comment]
> Do you agree?

Yep, I do agree! Don't name it `FileFooter` maybe (`FileMetadata` might be more appropriate for instance).
