### ISSUE TITLE
Return data required by the file footer from getVersionFile

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#347]
This supports #345.

To render the footer, in addition to the information already in `VersionFile` we need:
- ~~download link (which is currently not available via the API response)~~ (this will be done in #348)
- filename
- version
- SHA256 hash

**Comment by willdurand** [comment]
Did you file an issue about the browse API response on addons-server? This might get a higher priority since we are about to move everything in the reducer...

**Comment by bobsilverberg** [comment]
> Did you file an issue about the browse API response on addons-server? This might get a higher priority since we are about to move everything in the reducer...

I did not. I wasn't sure if we were sure exactly what we need at this point. I thought the suggestion was to file something later, but I guess I misunderstood.

**Comment by willdurand** [comment]
ah no, I know what I want 😅
