### ISSUE TITLE
Login should continue to the initial URL

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#354]
### Describe the problem and steps to reproduce it:

* Make sure you are logged out
* Go to a URL other than the front page, like http://localhost:3000/en-US/browse/491343/versions/1527716/
* Click the log in button and continue logging in on Firefox Accounts

### What happened?

You are redirected to the home page

### What did you expect to happen?

You should be redirected to the URL you initiated the login from

**Comment by willdurand** [comment]
Is that because we don't pass the full path to FxA? I think `LoginButton` passes `to=/` in the query string.
