### ISSUE TITLE
Display a friendly file size in the FileMetadata component

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#355]
Depends on #345

Currently, the size of a file is displayed in bytes, which is the number that is returned to us by the API. The old version of reviewer tools displays this in a friendlier format (e.g., in "KiB").

We should decide if we need to do that for code-manager, and if so, include code to do the conversion/translation. There is existing code in addons-frontend that I wrote for the versions page which does this, so this can be as simple as porting that code over to code-manager.

I imagine this should be an "mvp" issue, as opposed to "mvp-polish", but we can discuss that. @wagnerand What is your opinion on that?

Note that I am formatting the sizes using [`iec` notation](https://en.wikipedia.org/wiki/Binary_prefix#IEC_prefixes), which appears to be what the current review tools use.

**Comment by bobsilverberg** [comment]
This turned out to be much simpler than what we needed for addons-frontend, as I don't think we need to bring over all the `i18n` logic that I needed to write for that. So I just went ahead and created a patch.

**Comment by wagnerand** [comment]
Great, thank you!
