### ISSUE TITLE
Do not execute thunks in tests

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#368]
### Describe the problem and steps to reproduce it:

* Set up a test for a component that dispatches a thunk on mount. For example, [`Compare`](https://github.com/mozilla/addons-code-manager/blob/da388493553b5a460889689d4d99683ca1c0a01f/src/pages/Compare/index.tsx) dispatches `_fetchVersion` on mount which executes async loading code.

### What happened?

By default (i.e. without stubbing `store.dispatch`), the thunk will be dispatched and executed

### What did you expect to happen?

The thunk should not be executed.

### Anything else we should know?

Since we use [createFakeThunk()](https://github.com/mozilla/addons-code-manager/blob/da388493553b5a460889689d4d99683ca1c0a01f/src/test-helpers.tsx#L305), we never need to execute a thunk in a component test. We *infer* its execution by asserting how / when it gets dispatched.

Executing thunks in tests might create confusing side effects, especially when we add proper error handling (https://github.com/mozilla/addons-code-manager/issues/182).

Maybe we can create a special test store with the thunk middleware removed? Or stub it by default somehow?

**Comment by bobsilverberg** [comment]
This would be good to address. I'd prefer to keep this code quality issue open.
