### ISSUE TITLE
MDN links in linter messages are not rendered

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#383]
### Describe the problem and steps to reproduce it:

View a file that has a message with an anchor link to an MDN URL. Example: http://localhost:3000/en-US/browse/494431/versions/1532144/ (`manifest.json`)

### What happened?

The link is not rendered correctly.

<img width="668" alt="Screenshot 2019-03-11 17 00 18" src="https://user-images.githubusercontent.com/55398/54161571-94f16100-4420-11e9-9c6a-96ef39664d36.png">

### What did you expect to happen?

The link should be rendered correctly.

**Comment by kumar303** [comment]
@EnTeQuAk do all outgoing links appear as complete anchor tags in linter messages, like this screenshot? I saw an older test fixture that showed links rendered as plain URLs without anchor tags.

**Comment by EnTeQuAk** [comment]
> @EnTeQuAk do all outgoing links appear as complete anchor tags in linter messages, like this screenshot? I saw an older test fixture that showed links rendered as plain URLs without anchor tags.

All new links these days should be escaped, yes.

**Comment by willdurand** [comment]
Given that we have a `sanitizeHTML()` function (in `src/utils.tsx`), we could maybe remove HTML in the linter messages completely and then the existing logic would linkify links correctly.
