### ISSUE TITLE
Implement file browsing

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-code-manager#39]
This may need to be splitted into more issues.

File-browsing consists of two parts:

* A file-tree on the (currently) left side that shows all files
* A file-content part on the (currently) right side that shows the content of the currently selected file

API: https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#browse

This requires a `version_id` that should be applied through the URL the user clicks on the reviewer tools page.

<img src="https://user-images.githubusercontent.com/139033/51308927-8cddfc00-1a43-11e9-9c5e-88516b07ee2a.png" width="240">

![screenshot from 2019-01-17 10-24-34](https://user-images.githubusercontent.com/139033/51308318-21475f00-1a42-11e9-9d60-01d005a6ffe6.png)

**Comment by kumar303** [comment]
Thanks @EnTeQuAk 🎉 ; I broke it into separate issues:
* https://github.com/mozilla/addons-code-manager/issues/107
* https://github.com/mozilla/addons-code-manager/issues/108
* https://github.com/mozilla/addons-code-manager/issues/109
