### ISSUE TITLE
Remove unnecessary PropType from createContextWithFakeRouter()

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#404]
We don't use `PropTypes` for anything so this can probably be removed in `createContextWithFakeRouter()`:

https://github.com/mozilla/addons-code-manager/blob/168645596a6343242bf9560b88c5f72921e2e39f/src/test-helpers.tsx#L327-L329

**Comment by willdurand** [comment]
Does that work without this?

`childContextTypes` used `PropTypes` to let React know about context props that had to be passed to the `children`. It was before the new-ish context API so maybe this is not useful anymore but, prior to that abd without such a `childContextTypes`/`PropTypes` definition, context props were not passed to `children`.

**Comment by willdurand** [comment]
Specifically, you get errors like:

```
Error: Uncaught [Invariant Violation: WrapperComponent.getChildContext(): key "route" is not defined in childContextTypes.]
```

**Comment by willdurand** [comment]
This function won't be useful anymore since version 4.4.0 of the `react-router` relies on the new-ish context API: https://github.com/mozilla/addons-code-manager/pull/407. This PR breaks our test suite, of course.

Diff: [v4.3.1...v4.4.0](https://github.com/ReactTraining/react-router/compare/v4.3.1...v4.4.0)

**Comment by kumar303** [comment]
OK, so, Enzyme's `mount()` validates the prop types and throws invariant errors which is surprising to me! I suppose we can address this issue once we are using the new context API everywhere.
