### ISSUE TITLE
Make createContextWithFakeRouter() more obvious

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#405]
The `createContextWithFakeRouter()` helper function is either named incorrectly or can be simplified. By name alone, you'd expect to use it like this:

```jsx
  function render() {
    return shallowUntilTarget(
      <Thing />,
      ThingBase,
      {
        shallowOptions: {
          context: {
            ...createContextWithFakeRouter(),
            store: configureStore(),
          }
        },
      },
    );
  }
```

...but that would be incorrect.

Rather than renaming it, I think we can make it behave as illustrated above after https://github.com/mozilla/addons-code-manager/issues/404

**Comment by willdurand** [comment]
As mentioned in #404, the next minor version of react-router uses React's context API and this change breaks our test suite. This is a bit similar to #58, because if we're able to change our test code to use the context API, Enzyme still does not support it :/
