### ISSUE TITLE
Show linter validation warnings/errors/notices in file viewer

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-code-manager#41]
User story:

> As a code reviewer, I want to see linter messages shown in the file viewer to speed up the review process.

Reviewers need inline access to addons-linter validation warnings, notices and errors. For reviewers though, warnings will be the primary entity. Errors usually lead to rejection so that the upload can't be submitted.

![screenshot_2019-01-17 code review and search tools prd 1](https://user-images.githubusercontent.com/139033/51310447-f6abd500-1a46-11e9-8702-c254a44e31ea.png)

The relevant data can be retrieved from `validation_url_json` from https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#browse (note https://github.com/mozilla/addons-server/pull/10433 to update the docs)

Example json object:

```javascript
{
"errors": 0, // number of fatal validation errors
"success": true, // ``true`` or ``false`` if the overall validation ends up being a success (equivalent to ``errors == 0``)
"warnings": 1, // number of warnings, warnings should be visible and can result in rejection depending on their nature and frequency
"notices": 2, // number of notices, more informal messages
"messages": [{
    "description": [
        "Something something, see https://bugzilla.mozilla.org/"],
    "column": 0,  // column where the message applies to (not all warnings/errors/notices have this set properly, most do though)
    "line": 1,  // line where the message applies to
    "file": "manifest.json", // the file this message applies to
    "tier": 2,  // can be ignored, amo-validator had layered validation, addons-linter doesn't implement that, will always be ``1`` for WebExtensions
    "message": "Some warning", // the actual message
    "type": "warning", // the type of this message, "warning", "notice" or "error"
    "id": ['validation', 'messages', 'some_message_id'], // internal message id, used for deduplication
    "uid": "bb9948b604b111e09dfdc42c0301fe38" // unique identifier for this message
}],
"metadata": { // various metadata information that is usually used for auto-aproval risk weighting
    "id": "@webextension-guid",
    "manifestVersion": 2,
    "name": "WebExtensions test",
    "type": 1,
    "version": "0.0.2",
    "totalScannedFileSize": 502,
    "emptyFiles": [],
    "jsLibs": {},
    "unknownMinifiedFiles": [
        "background.js",
        "constant.js"
    ]
}
```

That's the object that's currently used by the file-viewer, I'm happy to put this into a proper API endpoint and change formatting into whatever works best for you.

**Comment by wagnerand** [comment]
It is worth noting that linter results can have different scopes.
* global (not related to a particular file/line): This should probably be displayed at the top of the `manifest.json` file, assuming that is the default file being shown. Also open to other ideas, maybe showing it at the top for every file?
* file-related: This should be shown at the top for the file in question.
* line-related: This should be shown at the correct line of the file in question.

**Comment by EnTeQuAk** [comment]
> * global (not related to a particular file/line): ~~This should probably be displayed at the top of the manifest.json file, assuming that is the default file being shown. Also open to other ideas, maybe showing it at the top for every file?~~ This seems to exist conceptually only. In practice, every message is tied to a file, according to @EnTeQuAk.

Correct, conceptionally they do exist - e.g for a missing manifest.json (which afaik might even be the only message) - but in reality all messages are bound to a file.

Although… on second thought… many of the addons-server don't have a `file` set, e.g legacy add-on warnings, etc. But imho, then they should be shown all the time, they're very rare.

**Comment by bobsilverberg** [comment]
Implementation note:

An icon should be displayed in the file tree beside each file that includes linter warnings, and it should "bubble up", so that a folder that contains a file with warnings should also have the icon, as well as that folder's parent, etc.

**Comment by kumar303** [comment]
The validation data will be included directly in the Browse API response as of https://github.com/mozilla/addons-server/issues/10620 (I think)

**Comment by kumar303** [comment]
> I'm happy to put this into a proper API endpoint and change formatting into whatever works best for you.

@EnTeQuAk I don't think you need to spend time changing the format. We might as well spend that time on the frontend (someone has to do it!). It isn't a friendly format but it's usable.

**Comment by willdurand** [comment]
> It isn't a friendly format but it's usable.

:+1: We can live with that and ship a MVP. We can file issues to improve things _after_.

**Comment by EnTeQuAk** [comment]
>  It isn't a friendly format but it's usable.

I wouldn't be changing too much about the format anyway, so maybe it's a good idea you'll play with it and file an issue afterwards about your dream format?

**Comment by willdurand** [comment]
In the `CodeView`, we can inline components by returning a table row in addition to the table row with the code:

```diff
commit 899c9df0af264bbaeb139aadca1567f6d7f21837
Author: William Durand <will+git@drnd.me>
Date:   Thu Feb 28 11:22:56 2019 +0100

    wip linter errors

diff --git a/src/components/CodeView/index.tsx b/src/components/CodeView/index.tsx
index e52be2e..d519ba1 100644
--- a/src/components/CodeView/index.tsx
+++ b/src/components/CodeView/index.tsx
@@ -1,6 +1,7 @@
 import * as React from 'react';
 import refractor from 'refractor';
 
+import Comment from '../Comment';
 import styles from './styles.module.scss';
 import text from './text-language';
 import { getLanguage, getLines, mapWithDepth } from './utils';
@@ -40,13 +41,25 @@ const CodeViewBase = ({ mimeType, content }: PublicProps) => {
             const line = i + 1;
 
             return (
-              <tr key={`row-${line}`}>
-                <td className={styles.lineNumber}>{`${line}`}</td>
+              <React.Fragment>
+                <tr key={`row-${line}`}>
+                  <td className={styles.lineNumber}>{`${line}`}</td>
 
-                <td className={styles.code}>
-                  {renderHighlightedCode(code, language)}
-                </td>
-              </tr>
+                  <td className={styles.code}>
+                    {renderHighlightedCode(code, language)}
+                  </td>
+                </tr>
+                {line === 3 && (
+                  <tr
+                    key={`row-comment-${line}`}
+                    style={{ display: 'inline-table', width: '100%' }}
+                  >
+                    <td colSpan={2}>
+                      <Comment comment={{ content: 'linter error' }} />
+                    </td>
+                  </tr>
+                )}
+              </React.Fragment>
             );
           })}
         </tbody>
```

**Comment by kumar303** [comment]
I think we added `needs: api` because we wanted the results included in the main API response (https://github.com/mozilla/addons-server/issues/10620) but we have a workaround in place.
