### ISSUE TITLE
"New" version list should list versions newer than the currently selected "old" version

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#415]
### Describe the problem and steps to reproduce it:

1. Open a compare view: http://localhost:3000/en-US/compare/502955/versions/1541794...1541798/
2. Open the "Choose a new version" dropdown

### What happened?

The list contains all the versions including `1.3.0`, which is lower than the selected "old" version (`1.4.0`).

### What did you expect to happen?

The list only contains "newer" versions.

### Anything else we should know?

I don't know whether we want to list the version that is equal to the selected old version or only strictly newer versions.

**Comment by AlexandraMoga** [comment]
@willdurand 
I've read in the pull request that you decided to list all the available versions in the drop down, except that new versions <= than  the old version selected will be disabled. 

This seems to work as expected, my only objection being that the un-selectable versions could be grayed out a bit more, to make it more obvious that they are disabled in the list.

- in this case, `1.1` and `1.0` are disabled, but you can't immediately tell.
![2019-04-12_15-15-47](https://user-images.githubusercontent.com/31961530/56037126-44c73080-5d37-11e9-9c0e-f86a0f7bab70.gif)

I've also checked with a retina display, which has slightly better colors compared to my usual monitor and I arrived to the same conclusion.

**Comment by willdurand** [comment]
> This seems to work as expected, my only objection being that the un-selectable versions could be grayed out a bit more, to make it more obvious that they are disabled in the list.

mmh, weird. I don't get this contrast/style at all locally. Which OS do you have in this screencast?

**Comment by AlexandraMoga** [comment]
@willdurand in the screencast I was using Firefox 66 Win10x64, I've also compared with a macOS High Sierra 10.13.6 and the contrast looks slightly better than on Windows:

![image](https://user-images.githubusercontent.com/31961530/56044024-02a5eb00-5d47-11e9-98a5-26edbea3dfcc.png)

**Comment by willdurand** [comment]
@AlexandraMoga could you file a new issue for the contrast issue? Thanks!
