### ISSUE TITLE
Tell eslint how to resolve @types (DefinitelyTyped) module files

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#416]
Consider this import path:

https://github.com/mozilla/addons-code-manager/blob/03e7b39f66615fb3108c5992282bbb29d3cf8534/src/components/VersionSelect/index.tsx#L3-L4

The definition for this lives in `node_modules/@types/react-bootstrap/lib/FormControl` which eslint does not know how to find. It is probably looking for it in `node_modules/react-bootstrap/lib/FormControl` which doesn't exist.

Let's try and fix this if there's a way.

**Comment by willdurand** [comment]
ah, that is correct. I did not think about that 😥 

We could maybe use the `import/external-module-folders` option set to:

```
['node_modules/', 'node_modules/@types/']
```

**Comment by kumar303** [comment]
I tried adding `node_modules/@types/` to `node.moduleDirectory` and I also tried [eslint-import-resolver-typescript](https://www.npmjs.com/package/eslint-import-resolver-typescript) but neither seemed to work. Maybe I just wasn't doing it right.

**Comment by willdurand** [comment]
ah 😞 

I read https://www.npmjs.com/package/eslint-import-resolver-node, and now this patch works:

```diff
diff --git a/.eslintrc b/.eslintrc
index 6927ff2..b57f156 100644
--- a/.eslintrc
+++ b/.eslintrc
@@ -41,7 +41,8 @@
   "settings": {
     "import/resolver": {
       "node": {
-        "extensions": [".js", ".ts", ".tsx"]
+        "extensions": [".js", ".ts", ".tsx", ".d.ts"],
+        "paths": ["node_modules/", "node_modules/@types/"]
       }
     }
   }
diff --git a/src/components/VersionSelect/index.tsx b/src/components/VersionSelect/index.tsx
index 56d69da..9de8d53 100644
--- a/src/components/VersionSelect/index.tsx
+++ b/src/components/VersionSelect/index.tsx
@@ -1,9 +1,9 @@
 import * as React from 'react';
 import { Col, Form } from 'react-bootstrap';
-// eslint-disable-next-line import/no-unresolved
-import { FormControlProps } from 'react-bootstrap/lib/FormControl';
 import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
 
+import { FormControlProps } from 'react-bootstrap/lib/FormControl';
+
 import { VersionsList } from '../../reducers/versions';
 import { gettext } from '../../utils';
 import styles from './styles.module.scss';
```
