### ISSUE TITLE
Add CDN endpoints to CSP

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-code-manager#421]
When CDN endpoints are known the CSP should be updated to configure `script-src`, `img-src` and `font-src` and any other relevant directives with the CDN endpoints. 

If the favicon is served from the main origin then `'self'` will need to remain under `img-src` otherwise it can be removed. For all others `'self'` should be removed when the CDN hosts are added.

When setting the directives, it's preferable to use a path rather than just an origin if at all possible. E.g. `https://cdn.blah.net/static/` is better than just `https://cdn.blah.net`

**Comment by kumar303** [comment]
It looks like we'll need this before we can deploy to dev since we'll be using a CDN right out of the gate. See https://github.com/mozilla/addons-code-manager/issues/327#issuecomment-473513809 for the endpoints.

I moved it to the top of the list: https://github.com/orgs/mozilla/projects/53

**Comment by willdurand** [comment]
This depends on how it gets deployed. Assets might still be served by the node server by default. If we don't configure a CDN endpoints that is used into the HTML returned by the node server, assets will probably be served anyway.

**Comment by kumar303** [comment]
> Assets might still be served by the node server by default. 

Ah, ok. I didn't know that.

**Comment by willdurand** [comment]
> > Assets might still be served by the node server by default.
> 
> Ah, ok. I didn't know that.

This has been confirmed. https://code.addons-dev.allizom.org/ serves the static files without any issue, so we can live with this setup. That being said, now that #475 has landed, it should be easier to use a CDN.

1. We can use `PUBLIC_URL` to set the CDN URL according to this page: https://facebook.github.io/create-react-app/docs/advanced-configuration. Unfortunately, we cannot use a more meaningful name for this env variable :(
2. We should make sure static files are sent to a CDN on deploy

**Comment by willdurand** [comment]
> 2. We should make sure static files are sent to a CDN on deploy

Static files are already uploaded on http://addons-code-manager-dev-cdn.allizom.org/.
