### ISSUE TITLE
Ensure CSP report endpoint is setup to consume reports

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-code-manager#423]
There's a no-op CSP report endpoint configured on the app, this should be superseded by a real CSP report endpoint setup by ops that feeds the actual security logs.

Endpoint is `/__cspreport__`

**Comment by bqbn** [comment]
Can you use the existing CSP endpoint for AMO?

i.e. [https://addons-dev.allizom.org/\_\_cspreport\_\_](https://addons-dev.allizom.org/__cspreport__), [https://addons.allizom.org/\_\_cspreport\_\_](https://addons.allizom.org/__cspreport__) and [https://addons.mozilla.org/\_\_cspreport\_\_](https://addons.mozilla.org/__cspreport__) respectively.

**Comment by willdurand** [comment]
@muffinresearch does the report-uri needs to be white-list in one of the CSP directives by chance? I am asking because the suggested endpoints above won't be on the same domain.

**Comment by muffinresearch** [comment]
@willdurand No whatever is configured in the CSP is what's allowed it doesn't need to be in a separate directive. What @bqbn is proposing will work.
