### ISSUE TITLE
`FileMetadata` has overflow issues due to Bootstrap and its default `code` style

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#424]
See also: https://github.com/mozilla/addons-code-manager/pull/398#issuecomment-474470983

---

On FF 66 (current release at the time of writing), there is a CSS overflow issue:

![](https://user-images.githubusercontent.com/55398/54623111-e6a97500-4a38-11e9-99fe-55eb29ba2cbf.png)

This is because Bootstrap uses `break-word` for the `code` style, but this value isn't universally supported (see: https://developer.mozilla.org/en-US/docs/Web/CSS/word-break).

We should override the `code` style in the `FileMetadata` component to avoid the hash overflow.

**Comment by AlexandraMoga** [comment]
This is now fixed on -dev - FF66, WIn10x64

![image](https://user-images.githubusercontent.com/31961530/55380590-4ae43280-5529-11e9-87b8-3acca0f20811.png)
