### ISSUE TITLE
standard endpoints for ops to onboard the app

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-code-manager#428]
### Describe the problem and steps to reproduce it:

In order for ops to onboard an application, we need the app to provide a few standard endpoints, namely,

* `/__version__`
* `/__heartbeat__`
* `/__lbheartbeat__`

Please see https://mana.mozilla.org/wiki/display/SVCOPS/New+Service+Guide for the specifics of these endpoints.

### What happened?

n/a

### What did you expect to happen?

The app provides the above mentioned 3 endpoints.

### Anything else we should know?

Please let us know if there are questions.

**Comment by kumar303** [comment]
@bqbn will a `version.json` file be written automatically like how it happens in `addons-frontend`?

**Comment by willdurand** [comment]
> @bqbn will a `version.json` file be written automatically like how it happens in `addons-frontend`?

I can answer that. There is a `version.json` added to each docker image built on Circle CI.

**Comment by willdurand** [comment]
I should also mention that we added an empty `version.json` at the root of this project, which gets overridden by Circle CI.
