### ISSUE TITLE
Add storybook for deep file trees, long names, and linter messages

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#431]
Let's make a storybook out of this file tree: http://localhost:3000/en-US/browse/494431/versions/1532144/

It showcases some important style behaviors:
* A deep tree of files
* Long file names that might need to be truncated
* Icons for linter messages 

Example:

<img width="568" alt="Screenshot 2019-03-20 12 57 59" src="https://user-images.githubusercontent.com/55398/54708034-740bc880-4b10-11e9-8e47-08791e51b8af.png">

**Comment by AlexandraMoga** [comment]
Could you please add a qa:not needed label to this issue?
Thanks
