### ISSUE TITLE
Fix return type of getVersionInfo

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#442]
The `getVersionInfo` selector currently looks like this:

https://github.com/mozilla/addons-code-manager/blob/5efef278ed8e2e3b7b2d7dfa1ceae7451cf3d801/src/reducers/versions.tsx#L309-L311

The return type should be `Version | void` because the `versionId` might be missing from `versions.versionInfo`. However, TypeScript infers the return type only as `Version`.

Let's declare the correct return type and fix the fallout (there is a lot). It should look more like:

```tsx
export const getVersionInfo = (
  versions: VersionsState,
  versionId: number,
): Version | void => {
  return versions.versionInfo[versionId];
};
```

This change will help ensure that all components are working with mapped Redux props correctly.

**Comment by willdurand** [comment]
Sentry issue: [ADDONS-CODE-MANAGER-DEV-1](https://sentry.prod.mozaws.net/operations/addons-code-manager-dev/issues/5469345/)
