### ISSUE TITLE
App not listening on IPv4 address 0.0.0.0

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-code-manager#457]
### Describe the problem and steps to reproduce it:

Problem: the app does not listen on IPv4 address 0.0.0.0
STR:

1. run the docker image, e.g.: `docker run --net host -e PORT=4000 mozilla/addons-code-manager:latest`
2. in a different terminal window, run `netstat -tnlp` and note that the app is listening on the default IPv6 address, e.g.: `tcp6       0      0 :::4000                 :::*                    LISTEN      6507/node`

### What happened?

We tried to pass `SERVER_HOST` environment variable to the container and set its value to `0.0.0.0` like we did for addons-frontend app, but it didn't work. The app seems to ignore that environment variable.
 
### What did you expect to happen?

The app should provide an option to allow it to listen on an ipv4 address. The AWS ELB health check can only talk to an IPv4 address.

### Anything else we should know?
n/a

**Comment by bqbn** [comment]
This is blocking issue #327.

**Comment by willdurand** [comment]
Interesting, because in most cases, listening to ipv6 should also listen to ipv4. I will add support for the `SERVER_HOST` variable.

**Comment by willdurand** [comment]
@bqbn the support for the env variable named `SERVER_HOST` has been merged, it should be available soon-ish on Docker Hub. Let us know if you encounter any other issue. Thanks!
