### ISSUE TITLE
Create FxA "code-manager" configs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#463]
The FxA configuration we are using right now is `amo` but it does not sound right. The redirect URL for this config points to addons-frontend, not code-manager.

We need FxA configs for: -dev, stage and prod.

**Comment by bqbn** [comment]
Add a link for reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1345936

It was the ticket that was used to obtain FxA config for addons-frontend.

**Comment by willdurand** [comment]
I filed the following server issues:

- https://github.com/mozilla/addons-server/issues/11015
- https://github.com/mozilla/addons-server/issues/11018
- https://github.com/mozilla/addons-server/issues/11019

**Comment by willdurand** [comment]
This has been done by ops for -dev in https://github.com/mozilla/addons-code-manager/issues/477. We have implemented the code-manager feature too, so we can close this issue.

**Comment by bqbn** [comment]
@willdurand do you think you could follow the example in https://github.com/mozilla/addons-code-manager/issues/463#issuecomment-476470757 to ask Fxa team to generate the secrets for -stage and -prod respectively. In the tickets you can have them deliver the secrets to me directly (like Mark did).

I'm happy to do it too if you let me know the name and exact redirection URI for both envs.

**Comment by willdurand** [comment]
> @willdurand do you think you could follow the example in [#463 (comment)](https://github.com/mozilla/addons-code-manager/issues/463#issuecomment-476470757) to ask Fxa team to generate the secrets for -stage and -prod respectively. In the tickets you can have them deliver the secrets to me directly (like Mark did).

Yep, I'll do that soon. I created two check-lists for stage and prod deployments:

- https://github.com/mozilla/addons-code-manager/issues/512
- https://github.com/mozilla/addons-code-manager/issues/513
