### ISSUE TITLE
Setup a Rapid Risk Assessment ahead of this going into production.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-code-manager#47]
New services should have a rapid risk assessment (RRA) carried out before they enter production. This can probably be organized earlier rather than later.

**Comment by kumar303** [comment]
Isn't there a doc describing this process? I thought I had the link but I can't find it.

**Comment by muffinresearch** [comment]
@kumar303 there are some docs here: https://infosec.mozilla.org/guidelines/risk/rapid_risk_assessment I would usually just contact Simon to set one up.

**Comment by muffinresearch** [comment]
RRA carried out Wednesday 13th March.

**Comment by kumar303** [comment]
RRA doc: https://docs.google.com/document/d/1nzpVxcI3n9dJG07s8kwELmpISrNr7uuwgxXEhwpJtEk/edit?ts=5c8909c5
