### ISSUE TITLE
Add env vars in -dev

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#470]
We need to set the following environment variables in -dev:

- `REACT_APP_API_HOST=https://addons-dev.allizom.org`

**Comment by bqbn** [comment]
The said env variable is passed to the container, for instance,

```
$ sudo docker exec addons-code-manager env |egrep REACT_APP_API_HOST
REACT_APP_API_HOST=https://addons-dev.allizom.org
```

**Comment by bqbn** [comment]
The running container gets the following env variables. Please let me know which need to be changed:

```
$ sudo docker exec addons-code-manager env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=ip-172-31-22-211.ec2.internal
NODE_ENV=production
NODE_CONFIG_ENV=dev
SERVER_HOST=0.0.0.0
SERVER_PORT=4000
NODE_APP_INSTANCE=amo
DATADOG_HOST=localhost
DATADOG_PORT=8125
REACT_APP_API_HOST=https://addons-dev.allizom.org
REACT_APP_SENTRY_DSN=******
PORT=4000
NODE_VERSION=10.15.3
YARN_VERSION=1.13.0
HOME=/root
```

**Comment by willdurand** [comment]
Thanks!

**Comment by willdurand** [comment]
@bqbn FYI if you want to do some clean-up, we don't need the following environment variables:

- `NODE_CONFIG_ENV`
- `NODE_APP_INSTANCE`

**Comment by bqbn** [comment]
The above two env variables removed. Thx @willdurand.
