### ISSUE TITLE
Implement connected-react-router

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#48]
Depends on #6 
Depends on #24 

Once we have redux in the app, we'll likely want to upgrade the vanilla [react-router](https://reacttraining.com/react-router) to [connected-react-router](https://github.com/supasate/connected-react-router).

**Comment by bobsilverberg** [comment]
Version 6 (the current version) of `connected-react-router` requires `React` 16.4 and `React Redux` 6.0 or later. We're okay for the `React` dependency but not the `Redux` dependency. As I understand it there's an issue with `Enzyme` that is preventing us from using `Redux` 6.

So, we can either implement version 5 of `connected-react-router` now, and plan to upgrade later, or we can wait until we are able to use `Redux` 6 and then implement version 6 of `connected-react-router`.

@kumar303 / @willdurand what do you think we should do?

**Comment by kumar303** [comment]
Hmm, tough call. I believe that https://github.com/airbnb/enzyme/pull/1960 will fix the issue in enzyme and that looks close to landing. Maybe we should wait a bit?

**Comment by bobsilverberg** [comment]
I agree that it's worth waiting a bit. I guess if we get to the point where we actually need it, and we still can't upgrade Redux, then we can implement version 5 for now.

**Comment by willdurand** [comment]
I'll use [v5](https://github.com/supasate/connected-react-router/releases/tag/v5.0.1) because we cannot upgrade Redux to v6 or v7.
