### ISSUE TITLE
Linter custom API code should use `REACT_APP_API_HOST`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#480]
We have some custom API code for fetching the linter messages, mainly because we are not relying on the addons-server API _per se_. In #460, we did not update this code though, so let's do it!

https://github.com/mozilla/addons-code-manager/blob/c6cad11653b45538292c5d2fd5b65033adb65b11/src/reducers/linter.tsx#L161-L163

**Comment by willdurand** [comment]
This happens because the `validationURL` field (in the reviewers API responses) contains a relative URL. If we change addons-server to return an absolute URL, then this problem would not occur.

**Comment by willdurand** [comment]
I requested an API change that should fix this issue :)

**Comment by kumar303** [comment]
Maybe this is a good time to implement https://github.com/mozilla/addons-code-manager/issues/466 ?

**Comment by willdurand** [comment]
> Maybe this is a good time to implement #466 ?

Yes, I have it opened too. I am thinking about writing a patch for both issues, but the linter API call does not need the API params (version, lang, etc)

**Comment by willdurand** [comment]
Yep, I went for something quite similar with nullable `prefix` (api) and `version`.
