### ISSUE TITLE
`LoginButton` should pass an absolute URL in the FxA URL

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#486]
We pass `location.pathname` to the API when initiating the login dance in the [`LoginButton` component](https://github.com/mozilla/addons-code-manager/blob/c6cad11653b45538292c5d2fd5b65033adb65b11/src/components/LoginButton/index.tsx) but this won't work.

First, `location.pathname` is a relative URL. Second, the API is hosted on a domain that is not the same as this app (`addons-dev.allizom.org` vs `code.addons-dev.allizom.org`). Passing a relative URL in the `to` query parameter works when both the API and the app are on the same domain because the API returns a redirect with the relative URL, but in the context of code-manager, we should pass an absolute URL.

**Comment by willdurand** [comment]
This needs https://github.com/mozilla/addons-server/issues/11018 first.

**Comment by AlexandraMoga** [comment]
Verified on -dev with FF66, Win10x64

The login request for code-manager is now passing and absolute URL to FxA:

https://addons-dev.allizom.org/api/v4dev/accounts/login/start/?config=code-manager&to=https://code.addons-dev.allizom.org/en-US/browse/616627/versions/1655509/

For comparison, an amo login request will send a relative URL:
https://addons-dev.allizom.org/api/v4/accounts/login/start/?config=amo&to=/en-US/firefox/addon/awesome-screenshot-plus-/?src=featured
