### ISSUE TITLE
Set a origin + path for the CDN hosted statics

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#493]
From: https://github.com/mozilla/addons-code-manager/pull/485#issuecomment-477693502

**Comment by willdurand** [comment]
@muffinresearch if we want to allow `/static/*` and `/favicon.ico`, should we add the following definition?

```
img-src https://code.addons-dev.allizom.org/static,  https://code.addons-dev.allizom.org/favicon.ico
```

**Comment by muffinresearch** [comment]
@willdurand Yep that works, though I'd add a slash on the end of the first path.

**Comment by muffinresearch** [comment]
Also the first path is not a CDN host, but if that's just an example it's fine.

**Comment by willdurand** [comment]
> Also the first path is not a CDN host, but if that's just an example it's fine.

oh yes, that was an example
