### ISSUE TITLE
Navigating the file tree is slow

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#494]
### Describe the problem and steps to reproduce it:

* Browse a version like http://localhost:3000/en-US/browse/494431/versions/1532144/
* Click the root to expand it
* Click various directories to expand and collapse them

### What happened?

There is a bit of lagginess introduced by https://github.com/mozilla/addons-code-manager/pull/487

### What did you expect to happen?

File navigation should not be laggy

### Anything else we should know?

I [profiled](https://calibreapp.com/blog/react-performance-profiling-optimization/) to see what's happening here. The `CodeView` component seems to cause most of the slowdown. The patch in https://github.com/mozilla/addons-code-manager/pull/487 dispatches a Redux action every time a directory is expanded. This causes `CodeView` to re-render each time when previously it would not. There also seems to be some slowdown in `FileTreeNode` which I haven't dug into yet.

**Comment by willdurand** [comment]
> The `CodeView` component seems to cause most of the slowdown. The patch in #487 dispatches a Redux action every time a directory is expanded. This causes `CodeView` to re-render each time when previously it would not.

This component does not have any guards and re-render all the time (because it is not using `connect()` for instance, which implements `shouldComponentUpdate()`). The `React.memo` helper might be a good solution here.

**Comment by willdurand** [comment]
I tried the STR above in FF Nightly + React profiler (commit: aa565fbf0e2088c1988780890dd00eb777b3e3f7):

![Screen Shot 2019-04-01 at 11 14 33](https://user-images.githubusercontent.com/217628/55316756-612db800-546f-11e9-9413-532d80b7c8b9.png)

**Comment by willdurand** [comment]
Similar capture with the patch from https://github.com/mozilla/addons-code-manager/pull/501:

![Screen Shot 2019-04-01 at 11 18 24](https://user-images.githubusercontent.com/217628/55317007-e87b2b80-546f-11e9-9b95-2438bc58684c.png)

I did not open/closed the exact same folders in the exact same order. I did open/closed lots of folders though. We should probably have a [protocol](https://en.wikipedia.org/wiki/Protocol_(science)) for such analyses though.

**Comment by kumar303** [comment]
I forgot to mention that the slowness is dependent on the speed of rendering the currently selected file (which can be very slow depending on line length). I updated the PR with details: https://github.com/mozilla/addons-code-manager/pull/501#issuecomment-478617440

When I first noticed the problem, it was because I had a big-ish file selected.

> We should probably have a protocol for such analyses.

Yeah. For this kind of thing, a repeatable benchmark could be useful to catch regressions (after we fix it!). But it has to run on the exact architecture each time and our CI isn't set up for that. Until then, I think it's OK to spot check things with a less scientific approach just to get a sense of where slowness lies. Architecting and maintaining an automated benchmark would take time.

**Comment by willdurand** [comment]
We should at least use the same STR (described in https://github.com/mozilla/addons-code-manager/pull/501#issuecomment-478617440). That's already some sort of protocol.

Speaking of which, I cannot reproduce slowness anymore after #501 and without CPU throttling. With "6x slowdown", I notice that toggling a folder is slow. I don't know what to expect because it looks like everything is slow, but I get a similar (inverted) flamegraph as in #504:

![Screen Shot 2019-04-01 at 18 10 45](https://user-images.githubusercontent.com/217628/55342616-7aebf100-54a9-11e9-8e32-cd9b4aa12e38.png)

A lot of `FileTreeNode` are fully re-rendered for some reasons.

**Comment by kumar303** [comment]
I don't notice any lag at all in today's version of the site.
