### ISSUE TITLE
Jest typeahead doesn't work and cannot be configured

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#50]
https://github.com/facebook/create-react-app/issues/6227 😞

This is an issue to track the upstream bug and maybe see if we can come up with workarounds.

**Comment by willdurand** [comment]
oh no :(

**Comment by bobsilverberg** [comment]
Thanks for raising that, @kumar303. It looks like there's already a PR open to fix it on `create-react-app` and that's just waiting on a release of `jest-watch-typeahead`, so hopefully this will be fixed soon.

**Comment by willdurand** [comment]
> Thanks for raising that, @kumar303. It looks like there's already a PR open to fix it on `create-react-app` and that's just waiting on a release of `jest-watch-typeahead`, so hopefully this will be fixed soon.

So, a new version of the plugin has been released. I commented on the PR to see if we can get it merged now.

**Comment by willdurand** [comment]
Fixed by https://github.com/mozilla/addons-code-manager/pull/178
