### ISSUE TITLE
The SHA hash doesn't fit in the file Information card

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#511]
**STR:**

1. Log in to AMO -dev
2. Access the code-manager page for an addon - see https://code.addons-dev.allizom.org/en-US/browse/616549/versions/1655416/
3. Look at the File Information card

**Actual result:**
The SHA hash doesn't fit in the file Information card

**Expected result:**
The SHA hash doesn't flow outside the file information card

Notes:
- reproduced on -dev with FF66, Win10x64

![image](https://user-images.githubusercontent.com/31961530/55327736-6f8dcb00-5493-11e9-92d2-c4983c41548a.png)

**Comment by willdurand** [comment]
Indeed, thanks for the issue. This is a dup of #424.

**Comment by AlexandraMoga** [comment]
Ah, sorry. Missed that one.
