### ISSUE TITLE
Deploy stage

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#512]
Issue for deploying this project in stage at `code.addons.allizom.org`.

## Checklist

- [x] reuse -dev "ops config" to deploy a stage environment
- [x] setup Git tag-based deployments
- [x] setup a Sentry project for code-manager in stage. Project created: https://sentry.prod.mozaws.net/operations/addons-code-manager-stage/
- [x] create a new FxA (OAuth) client for code-manager in stage. This probably [requires a bugzilla bug](https://github.com/mozilla/addons-code-manager/issues/463#issuecomment-476470757). The redirect URI should be:
    ```
    https://addons.allizom.org/api/v4/accounts/authenticate/?config=code-manager
    ```
- [x] ensure the following environment variables are set:
  - [ ] `REACT_APP_API_HOST=https://addons.allizom.org`
  - [ ] `PUBLIC_URL=https://addons-code-manager-stage-cdn.allizom.org`
  - [ ] `REACT_APP_SENTRY_DSN` with the DSN provided by Sentry as value
  - [ ] `CODE_MANAGER_FXA_CLIENT_ID` with the client ID given by FxA
  - [ ] `CODE_MANAGER_FXA_CLIENT_SECRET` with the secret given by FxA

**Comment by willdurand** [comment]
>     * create a new FxA (OAuth) client for code-manager in stage.

I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1541346

**Comment by willdurand** [comment]
We now have a FxA client for code-manager in stage and it looks like the stage deployment pipeline is ready (according to the recent secret channel logs).

@bqbn you'll find all the mandatory env vars in the issue description above :)

**Comment by bqbn** [comment]
https://code.addons.allizom.org/ is now available. Please test it.

**Comment by willdurand** [comment]
This looks good from a deployment perspective. I don't think we have a link to code-manager in the reviewers tool so we can't really do anything yet.

We can close this issue though.
