### ISSUE TITLE
Deploy prod

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#513]
Issue for deploying this project in prod at `code.addons.mozilla.org`.

## Checklist

- [x] reuse the stage "ops config" to deploy a prod environment
- [x] setup a Sentry project for code-manager in prod. Project created: https://sentry.prod.mozaws.net/operations/addons-code-manager-prod/
- [x] create a new FxA (OAuth) client for code-manager in prod. This probably [requires a bugzilla bug](https://github.com/mozilla/addons-code-manager/issues/463#issuecomment-476470757). The redirect URI should be:
    ```
    https://addons.mozilla.org/api/v4/accounts/authenticate/?config=code-manager
    ```
- [ ] ensure the following environment variables are set:
  - [ ] `REACT_APP_SENTRY_DSN` with the DSN provided by Sentry as value
  - [ ] `CODE_MANAGER_FXA_CLIENT_ID` with the client ID given by FxA
  - [ ] `CODE_MANAGER_FXA_CLIENT_SECRET` with the secret given by FxA

Other environment variables can be omitted since their default values are the prod settings (these default values can be seen in [this `.env` file](https://github.com/mozilla/addons-code-manager/blob/0739412d4c98a7078e13c9d06aed968546bf7428/.env)).

**Comment by willdurand** [comment]
>     * create a new FxA (OAuth) client for code-manager in prod.

I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1541346.

**Comment by willdurand** [comment]
@bqbn we just tagged addons-code-manager and we'll enable the link from the Reviewer Tools to this project in stage. Assuming everything looks good, we'd like to have a prod environment.

**Comment by willdurand** [comment]
@bqbn should we try to push to prod today (May 2nd, 2019)?

**Comment by willdurand** [comment]
It's up! https://code.addons.mozilla.org/

**Comment by AlexandraMoga** [comment]
The functionality of the browse and compare pages will have to be verified by the reviewers who will have access to the tool. QA doesn't have reviewer permissions in prod.

**Comment by kumar303** [comment]
It was down but now it's up again! @wagnerand and I confirmed that everything is working.
