### ISSUE TITLE
Logout does not seem to work in -dev

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#515]
### Describe the problem and steps to reproduce it:

1. Go to https://code.addons-dev.allizom.org/
2. Make sure you're logged in
3. Click the "Logout" button
4. Refresh the page

### What happened?

You appear logged in again. Logout did not work.

### What did you expect to happen?

You should be successfully logged out.

### Anything else we should know?

The API call succeeds. It returns the `set-cookie` headers to clear the cookies for the user on FF, Chrome does not display them though, so that might be an hint. Not sure why it is not working though. I believe it has something to do with having 2 different domains or CORS or something in between.

It works in local dev.

**Comment by kumar303** [comment]
I compared to `addons-frontend` and my best guess is that we need to pass `credentials: 'include'` to `fetch()` for the `DELETE` request. The `addons-frontend` code [does this](https://github.com/mozilla/addons-frontend/blob/6f57080800997e0ac56ef84950cf1e6db847cc38/src/core/api/index.js#L276) but the `code-manager` code [does not](https://github.com/mozilla/addons-code-manager/blob/164d265781da81e71aea109e55dc65881e19f111/src/api/index.tsx#L135-L138). I'm not sure how to reproduce this locally. Maybe try landing a patch on dev to see if that works?

**Comment by willdurand** [comment]
Yes, that's my best guess for now too. I remember that this was part of the initial patch and then removed because it worked without locally and we wanted a simple API.

**Comment by willdurand** [comment]
So there is a CORS issue because we cannot send the credentials to the API when its `Access-Control-Allow-Origin` header is set to `*`.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![2019-04-03_11-46-28](https://user-images.githubusercontent.com/31961530/55465892-bea83d00-5606-11e9-8e98-5d1bb9f070d7.gif)
