### ISSUE TITLE
Error messages for 403/404 responses should be more user oriented

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#518]
**STR:**

1. Log in to AMO -dev
2. Open https://code.addons-dev.allizom.org/en-US/browse/3006/versions/1541689/ where the version number is incorrectly specified

**Actual result:**
Currently we are displaying a raw error message based on the api response

**Expected result:**
The error message should be more informative and relevant for the end user. Also, the loading version indicator should not be there.

**Notes:**
- the same applies for 403 responses
- reproduced on -dev with FF66, WIn10x64

![image](https://user-images.githubusercontent.com/31961530/55388225-8ee03300-553b-11e9-884f-92a286acbafa.png)

![image](https://user-images.githubusercontent.com/31961530/55388087-4fb1e200-553b-11e9-81b6-95da1430c6d6.png)

**Comment by willdurand** [comment]
@kumar303 I am using the code-manager in production today. I am looking at what looks like old-ish add-ons, and there is no git repository for the versions I am interested in.

I found the error in the network panel:

```
HTTP/1.1 404 Not Found

{"detail":"Couldn't find the requested version in git-repository"}
```

Not sure what we could do but maybe we could try to display the response payload to fix this issue?

**Comment by willdurand** [comment]
> @willdurand For the issue of not finding a git-repository, can you file a server issue for that with the API request/response?

I thought there were some already, like https://github.com/mozilla/addons-server/issues/8727 maybe. @EnTeQuAk what do you think?

**Comment by AlexandraMoga** [comment]
I think this is still an issue that should be fixed, especially since developers can access code manager by clicking on linked files in validation results. In such cases they will see the 403 error message (see https://github.com/mozilla/addons-server/issues/14607 for background).
