### ISSUE TITLE
Enable keyboard navigation between linter messages

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#520]
User story:

> As a reviewer, I want to quickly see inline linter messages so I can understand their impact when reviewing code.

This supports #199 

Two of the keyboard shortcuts required for #199 are meant to allow a user to jump between linter messages for the extension. 

The "Next message" shortcut would:
- Scroll to the next linter message in the current file, if there is another linter message which has not yet been scrolled to.
- Jump to the next file with a linter message, and scroll it into view, if there are no more linter messages in the current file. 

The "Previous message" shortcut would:
- Scroll to the previous linter message in the current file, if there is another linter message above the current scroll position.
- Jump to the previous file with a linter message, and scroll the last message for that file into view, if there are no previous linter messages in the current file. 

Note that the first case for each shortcut is a requirement (i.e., scrolling to messages in the current file), and that the second case is a "nice-to-have", but it does seem like it would add a lot of value in terms of enabling keyboard navigation for the entire extension's code.

See https://github.com/mozilla/addons-code-manager/issues/523 for addressing this same user story with a visual UI.

**Comment by bobsilverberg** [comment]
In terms of implementation, it looks like we'll need to use the data provided by `LinterProvider` to determine what messages exist. 

Each message `td` is assigned an `id` by `CodeView`, so we can use that, along with `scrollIntoView()` to do the scrolling, but we need to know the order in which these messages exist in order to do the previous/next functionality. 

For an individual file that's not such a big deal, but if we want to enable navigating between files with linter messages then we'll also need to know the order of the files, from the perspective of the `FileTree`. At this point I believe that only the `FileTree` knows what order it is in (because it's sorted as part of its creation), so if we want to enable navigating between files I think we'll need to store that information somewhere.

Note also that we need something similar for #471, because that also involves navigating between files, so maybe that's a problem we should address first.

It seems like we need to store information about the exact order of all files in the tree for #471, but for this issue we'd also need to know which of those files contain linter messages. So something like an array or map which contains the files in order, and indicates which have linter messages seems like something we should have. If we're going that far, I wonder if it makes sense to just store the ids of each linter message in this structure as well (as opposed to just a flag that says whether a file has linter messages or not).

@kumar303 / @willdurand: Does it sound like I'm going down the right path with this? Do you have any suggestions for a simpler solution? If my take makes sense, where would we store this information? I assume it would be in the Redux store.

**Comment by willdurand** [comment]
> At this point I believe that only the `FileTree` knows what order it is in (because it's sorted as part of its creation), so if we want to enable navigating between files I think we'll need to store that information somewhere.

Yes, sorting is determined by `recursiveSortInPlace()` (alphabetically sorted, directories first).

> Note also that we need something similar for #471, because that also involves navigating between files, so maybe that's a problem we should address first.

It looks like knowing the order of the files becomes more and more important indeed.

> It seems like we need to store information about the exact order of all files in the tree for #471, but for this issue we'd also need to know which of those files contain linter messages.

Does that mean #471 is not only about navigating between files but the feature will skip files without linter messages?

> So something like an array or map which contains the files in order, and indicates which have linter messages seems like something we should have. If we're going that far, I wonder if it makes sense to just store the ids of each linter message in this structure as well (as opposed to just a flag that says whether a file has linter messages or not).

Yes, I believe we want the list of `path` sorted like in `FileTree`. I like the idea of storing the ids of the linter messages so that an empty array would mean "no linter messages".

**Comment by bobsilverberg** [comment]
> Does that mean #471 is not only about navigating between files but the feature will skip files without linter messages?

I'm not sure I entirely understand the question. For #471, we would want to navigate between all files. It doesn't care about linter messages. For this issue (#520), if we want to enable the second set of cases described above, we would want to be able to navigate to the next or previous file *that does have a linter message*.

**Comment by willdurand** [comment]
Sorry, I misunderstood "this issue" in "[...] for #471, but for this issue we'd also need". I thought it referred to #471 and not #520.

It seems most of the logic could be shared if we are able to express the "go to next" and "go to previous" actions. There could be an optional list of conditions passed to these actions so that we could express "go to next" file, but also "go to next" file with linter messages or even "go to next" file with errors.

**Comment by kumar303** [comment]
Yes, it sounds like you need to move [`buildFileTree()`](https://github.com/mozilla/addons-code-manager/blob/a2b7474868558333f137bcf68acd096c4a50923d/src/components/FileTree/index.tsx#L52) to a reducer so that actions can work with its structure. This probably makes sense anyway since we don't need to rebuild it every time `FileTree` renders. 

You can probably make a new `fileTree` reducer for this purpose. I know we have been keying things by `version` but we won't ever need to simultaneously manage file trees for two versions so I don't think it's important. You could just put a `forVersionID` attribute on the reducer (like [this](https://github.com/mozilla/addons-code-manager/blob/a2b7474868558333f137bcf68acd096c4a50923d/src/reducers/linter.tsx#L127)) so we know when to reload the data.

Storing linter message IDs along with each file node sounds fine, too. We could introduce a `byUID` mapping in [reducers/linter](https://github.com/mozilla/addons-code-manager/blob/a2b7474868558333f137bcf68acd096c4a50923d/src/reducers/linter.tsx#L126) to facilitate lookups.

**Comment by bobsilverberg** [comment]
@wagnerand I think we need some new keys to use for this feature. It looks like in the current Reviewer Tools app, `p` and `n` are assigned to "Previous diff" and "Next diff" when in compare mode, but they are assigned to "Previous note" and "Next note" in browse mode. My understanding is that this feature to navigate between linter messages is a replacement for "Previous note" and "Next note", but we cannot use those shortcut keys in compare view as they are already assigned to "Previous diff" and "Next diff". We can make this linter message navigation work in both modes, so we need a new unique set of shortcut keys for them. I'm using `a` and `z` for "Previous message" and "Next message" in development, but I can change those to whatever you'd like.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this issue on -dev - FF67(Win10). 
I used the following sample https://code.addons-dev.allizom.org/en-US/browse/492486/versions/1529211/?messageUid=da19520b66044478872637302eb2fcca&path=manifest.json#I0 

Test results:
- navigation with `z` and `a` works for linter messages inside a file. 

![in the same file ](https://user-images.githubusercontent.com/33448286/59909527-8b609780-9418-11e9-9ce2-e1069068064e.gif)

- navigation between folders using `z` and `a` is working fine too 

![from a folder to another into files](https://user-images.githubusercontent.com/33448286/59909633-c1058080-9418-11e9-99e4-08952149c002.gif)

**Comment by ioanarusiczki** [comment]
@bobsilverberg I do have a question about the `compare files`. 
I used this sample for testing https://code.addons-dev.allizom.org/en-US/compare/390151/versions/1688192...1688302/?messageUid=be7ea3a5e3b1428ba282fe417273cf86&path=popup%2Fjs%2Funderscore-min.js#I0
In this case there are no differences between the linter message files ( the old version file versus new version file), yet down below "No differences" the linter notices are displayed but the linter warnings are not.

Is that expected or the warnings should be displayed too?

Navigating through a file with linter warnings - the Uid is visible in the URL yet the messages are not visible 

![compare files](https://user-images.githubusercontent.com/33448286/59914043-3033a280-9422-11e9-8cb9-94660f55d2d4.gif)

**Comment by kumar303** [comment]
> I used this sample for testing https://code.addons-dev.allizom.org/en-US/compare/390151/versions/1688192...1688302/?messageUid=be7ea3a5e3b1428ba282fe417273cf86&path=popup%2Fjs%2Funderscore-min.js#I0
> In this case there are no differences between the linter message files ( the old version file versus new version file), yet down below "No differences" the linter notices are displayed but the linter warnings are not.
> 
> Is that expected or the warnings should be displayed too?
> 
> Navigating through a file with linter warnings - the Uid is visible in the URL yet the messages are not visible

@ioanarusiczki Yes, this is confusing. Originally we were going to skip files with *no differences* (https://github.com/mozilla/addons-code-manager/issues/831) but we decided to just show the full file when it doesn't have any differences (https://github.com/mozilla/addons-code-manager/issues/846). Once that's fixed, navigating linter messages should work as you'd expect it to.
