### ISSUE TITLE
Visualize and navigate inline linter messages

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#523]
User story:

> As a reviewer, I want to quickly see inline linter messages so I can understand their impact when reviewing code.

The current tool offers a vertical strip to the left of the file pane that attempts to let a reviewer visualize what slice of the file they are viewing and what lines have linter messages. It is buggy and unintuitive and does not show you actual linter messages.

It attempts to implement a common UX pattern of showing a condensed overview of a long file, found in IDEs. Here is an example of one, along the right side of this screen:

<details>
<summary>Screenshot</summary>

<img width="1277" alt="Screenshot 2019-04-02 at 19 08 51" src="https://user-images.githubusercontent.com/55398/55422685-d49ffa00-5541-11e9-832b-5358337db515.png">

</details>

Maybe we can implement something like this so that it addresses the user story above and possibly future user stories about navigating reviewer comments in files and other annotations from analysis. However, starting with a quicker implementation would be fine, too.

See https://github.com/mozilla/addons-code-manager/issues/520 for addressing this same user story purely with keyboard shortcuts

**Comment by vcarciu** [comment]
@kumar303 : If the message is at the beginning of the file, then you can't visualize the linter message directly from the right side.  For example : https://code.addons-dev.allizom.org/en-US/browse/494431/versions/1532144/?path=manifest.json .

Please let me know if this is expected.

**Comment by vcarciu** [comment]
I will log a new issue for comment from above.
