### ISSUE TITLE
API check in `/__heartbeat__`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#524]
In #428, we introduce new server endpoints for ops. The `/__heartbeat__` endpoint should indicate whether the app as well as its dependent services are healthy.

For code-manager, we should make sure the API is healthy. We cannot rely on `/__heartbeat__` (or `/__lbheartbeat__`) on AMO because they are not implemented.

**Comment by willdurand** [comment]
@diox would you know an endpoint (without authentication) that we could call to know whether the API is healthy?

**Comment by diox** [comment]
Depends on your definition of *healthy*... Maybe `OPTIONS` on an endpoint that doesn't require any parameters, such as `https://addons.mozilla.org/api/v4/accounts/authenticate/` works as a hack. But we don't have a specific endpoint to ensure everything is up and running (ops has [a monitor endpoint](https://addons.mozilla.org/services/monitor.json) but it isn't really meant to be consumed by other clients)
