### ISSUE TITLE
An error occurs when trying to change the "new" version in the Compare page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#534]
### Describe the problem and steps to reproduce it:

1. Go to https://code.addons-dev.allizom.org/en-US/compare/502955/versions/1541794...1541798/
2. Select a "new" version, e.g., `1.4.0`

### What happened?

It crashes.

### What did you expect to happen?

It does not crash.

### Anything else we should know?

Error in local dev is:

```
TypeError: version is undefined
render
src/components/DiffView/index.tsx:205

  202 | 
  203 | return (
  204 |   <LinterProvider
> 205 |     versionId={version.id}
      | ^  206 |     validationURL={version.validationURL}
  207 |     selectedPath={version.selectedPath}
  208 |   >
```

Selecting another "old" version seems to work.

**Comment by willdurand** [comment]
This is likely related to https://github.com/mozilla/addons-code-manager/issues/442

**Comment by AlexandraMoga** [comment]
I haven't run into error with the compare file component. I've also tried with the following example:
https://code.addons-dev.allizom.org/en-US/compare/616548/versions/1655414...1655415/
