### ISSUE TITLE
Generate an anchor link to a line of code

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#546]
For the code overview panel (https://github.com/mozilla/addons-code-manager/issues/523), each line needs to link to a line of code. We already generate these links (see https://github.com/mozilla/addons-code-manager/issues/317) so now we need a shared function that more than one component can use.

Note that the compare view is a little different because we rely on the upstream library to generate the anchor links.

**Comment by kumar303** [comment]
Ultimately, we'll want the code overview to link to lines of code in the Compare view as well as the Browse view.

The Compare view will be tricky because the anchor tags we'll deal with will either look like `#N123` (for the normal part of the diff) or `#I123` (for insertions).

These anchors are generated here: https://github.com/otakustay/react-diff-view/blob/4bca86cec1168b2ca05c16dd6d202053a727931a/src/utils/diff/getChageKey.js

I'm not going to worry about it for this first patch.

**Comment by willdurand** [comment]
@ioanarusiczki added QA instructions

**Comment by AlexandraMoga** [comment]
I've verified this on -dev for the browse view and each line of code, for any of the inspected files has an anchor link:

![2019-04-16_16-03-48](https://user-images.githubusercontent.com/31961530/56214738-19aa4d00-6067-11e9-8b6f-f7d2ce4e1155.gif)
