### ISSUE TITLE
Find the most severe type of linter message

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#548]
We already have [`findMostSevereTypeForPath()`](https://github.com/mozilla/addons-code-manager/blob/edfccc76df32d839cd76b0735e7794cce701f30c/src/components/FileTreeNode/index.tsx#L20) but the code overview panel (https://github.com/mozilla/addons-code-manager/issues/523) needs to work with it in a different way. Let's extract a more generic function that the code overview panel can use.

**Comment by willdurand** [comment]
@ioanarusiczki added QA instructions

**Comment by AlexandraMoga** [comment]
I have looked at several add-ons and the files seem to have the correct color and badge corresponding to the validation messages they've generated.

Here are some examples:

- the `jquery-2.1.1.min.js` generated a validation error and a notice => the file and the `jquery`  parent folder are highlighted in red and have the suggestive error icon:
![image](https://user-images.githubusercontent.com/31961530/56293839-90604c80-6132-11e9-98ff-82e61d4c3782.png)

- here, the `servicedata.js` file generated a validation warning, while other files in the same folder have generated only notices => the `js` parent folder  will be highlighted in orange and displays the corresponding warning badge
![image](https://user-images.githubusercontent.com/31961530/56294045-edf49900-6132-11e9-9d46-6152e8d8e937.png)
