### ISSUE TITLE
Clicking on a line of code should go to that line

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#559]
### Describe the problem and steps to reproduce it:

- Sign and load http://localhost:3000/en-US/browse/494431/versions/1532144/
- Click Line 13 of the code

### What happened?

Nothing happens

### What did you expect to happen?

Line 13 should be selected

### Anything else we should know?

If you reload the page after clicking, line 13 will appear selected. This is how it should behave.

Line anchors were added in https://github.com/mozilla/addons-code-manager/issues/317

**Comment by willdurand** [comment]
Marking this issue as regression because it used to work.

**Comment by willdurand** [comment]
I think the problem comes from `LinterProvider`, which blocks the update of the rest of the `CodeView` component. Clicking an anchor does update the routing data (i.e. `locationhash`) but because nothing else changes, the `CodeView` does not update the selected line...

**Comment by kumar303** [comment]
ok, I see what the problem is. I need it for https://github.com/mozilla/addons-code-manager/issues/523 so I'll fix this.

**Comment by AlexandraMoga** [comment]
Verified on -dev with FF66, WIn10x64 for both the Browse and Compare views.

Lines of code are immediately selected when clicking on them:

![2019-04-16_16-03-48](https://user-images.githubusercontent.com/31961530/56212102-06e14980-6062-11e9-8a5e-92be4c09952a.gif)
