### ISSUE TITLE
Open the parent folder(s) when navigating to a new file

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#562]
Depends on #468 

This is a follow-up to PR #468. When navigating to a new file via a keyboard shortcut, the new file is highlighted in the tree, but if the parent folder was closed, it remains closed, so the user cannot see that the new file is now highlighted.

We should fix this so that any parent folders of the current file are expanded automatically when a new file is selected. It seems like doing this as part of the response to the `updateSelectedPath` action would make the most sense.

**Comment by bobsilverberg** [comment]
>  It seems like doing this as part of the response to the `updateSelectedPath` action would make the most sense.

While that makes sense in terms of the fact that we will always want the parent folders opened whenever we have processed `updateSelectedPath`, this creates another situation where we need data from two different reducers.
- The data that describes/controls which folders are open is in the `versions` reducer, specifically in `version.expandedPaths`, so an action in `versions` must do the updating of this data.
- Information about which folders are the parents of other folders is stored in the `fileTree` reducer.
- Having said that, we can still calculate which parents exist for a given file using the `entries` data in the `version` in the `versions` reducer, so we can probably avoid having to interact with the `fileTree` reducer at all, but it feels a bit off to be doing this calculation again when we've already (kind of) done it to build the tree in the `fileTree` reducer.

Sorry for the brain dump here, but if anyone can follow what I'm saying above, and has any specific advice about how to best deal with this, I'm all ears.

**Comment by willdurand** [comment]
If `updateSelectedPath` receives the `path`, then we could find the parents by splitting on `/`, no? We could then dispatch an action to open each value from the `.split('/')` but the last one, but maybe I missed something.

**Comment by bobsilverberg** [comment]
> If `updateSelectedPath` receives the `path`, then we could find the parents by splitting on `/`, no? We could then dispatch an action to open each value from the `.split('/')` but the last one, but maybe I missed something.

I don't think you missed anything. It does indeed seem to be as simple as that. I hadn't even looked at the data yet when I wrote my comment. Thanks for that!

**Comment by willdurand** [comment]
@ioanarusiczki added QA instructions

**Comment by AlexandraMoga** [comment]
Verified on -dev with FF66, Win10x64

The parent folder is now expanded when navigating by keyboard within the file tree, both for the browse and compare view. For a more comprehensive test result, please check https://github.com/mozilla/addons-code-manager/issues/459#issuecomment-484063600


Additionally, in the browse page, when a link with a direct file path is accessed, the corresponding parent folder will be opened in the file tree:

![image](https://user-images.githubusercontent.com/31961530/56289379-6e160100-6129-11e9-8d5e-dee197cceeb3.png)
