### ISSUE TITLE
Infinite loop when fetching a file has errored

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#565]
In the `versions` reducer, `fetchVersionFile` dispatches `abortFetchVersionFile` when an API error is returned. The reducer reacts to this action by setting the `loading` flag to `false`.

This is problematic because a component (like `Browse`) won't know that an error has occured and will retry to fetch the file given that `file` is not defined and `fileIsLoading` is `false`. This behavior will be triggered again and again, hence the infinite loop.

**Comment by willdurand** [comment]
Maybe we should always use this convention: https://github.com/mozilla/addons-code-manager/blob/d7e02107869b4b2a5f63e5abdfb32af3d07f9f6e/src/reducers/versions.tsx#L257-L259 so that we could detect API errors and avoid re-fetching forever.

**Comment by kumar303** [comment]
In `addons-frontend`, it was always possible to see if a saga had produced an error or not. All loaders would check for an error before loading. Hmm.

**Comment by willdurand** [comment]
@ioanarusiczki added QA instructions

**Comment by willdurand** [comment]
>  As a sidenote, I don't think we should have a 500 error in this case, which is why I've filed [mozilla/addons-server#11196](https://github.com/mozilla/addons-server/issues/11196) a little while ago.

:+1:
