### ISSUE TITLE
Expose a `contribute.json` file?

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#573]
While reviewing code.addons-dev.allizom.org on Mozilla Observatory, I learnt about the [`contribute.json` file](https://infosec.mozilla.org/guidelines/web_security#contributejson). Do we want to expose such a file here?

**Comment by kumar303** [comment]
Yes, probably, but the site isn't really set up for contributors right now. The developer documentation is pretty good but we need some good first bugs. There is also a complication in that we need to grant reviewer access (on dev) to new contributors.
