### ISSUE TITLE
Browse files page is not rendered if the lang parameter is missing

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#580]
**STR:**

Load https://code.addons-dev.allizom.org/browse/616653/versions/1655542/

**Actual result:**
An "Ooops, page not found!" message is displayed. There isn't an actual 404 response though.

**Expected result:**
A redirect to the default language set by the browser.

**Notes:**
- also happens with the compare files page
- reproduced on -dev with FF66, Win10x64

Working link: https://code.addons-dev.allizom.org/en-US/browse/616653/versions/1655542/

**Comment by willdurand** [comment]
I think this is intended because (1) it's a new URL and (2) we don't plan to localize this app yet.

**Comment by bobsilverberg** [comment]
I recall raising this some time ago - the fact that we're including `en-US` in our URL even though we have no localization. It seems like we should support a path with no language as well. What do you think @willdurand?

**Comment by willdurand** [comment]
> I recall raising this some time ago - the fact that we're including `en-US` in our URL even though we have no localization. It seems like we should support a path with no language as well. What do you think @willdurand?

I suppose we could some sort of "redirect middleware" like in addons-frontend, so that we handle locale-less URLs, but it is probably low priority.

We decided to make the app i18n-aware, which is why we have `en-US` in the URLs (I think).
