### ISSUE TITLE
Add a scroll bar in the file tree

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#582]
**STR:**

1. Open the code manager for an addon that has many files - https://code.addons-dev.allizom.org/en-US/browse/8542/versions/1655535/
2. Collapse the parent folder to see the contents
3. Scroll down until you reach the end of the file tree

**Actual result:**
The whole page will scroll down

**Expected result:**
There should be a scroll bar in the file tree component, which will make the entire page more compact. A max-height could be defined and only after this is exceeded the scroll bar should be rendered.

![2019-04-15_12-49-24](https://user-images.githubusercontent.com/31961530/56123404-10dd4c80-5f7d-11e9-85f2-9d745b1efa75.gif)

**Comment by willdurand** [comment]
Yes, I think that's what @kumar303 wants to solve in #575.

**Comment by kumar303** [comment]
@AlexandraMoga This is a good example of why we need it. Thanks.

**Comment by kumar303** [comment]
This was fixed in https://github.com/mozilla/addons-code-manager/pull/681

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx66 Win10x64

![2019-05-07_13-25-19](https://user-images.githubusercontent.com/31961530/57293546-b5126900-70cd-11e9-9d78-e0bfe5e1628b.gif)

There is also no scroll bar if there are fewer files to display:

![image](https://user-images.githubusercontent.com/31961530/57293972-e6d7ff80-70ce-11e9-9aa6-4ff7305ca39e.png)
