### ISSUE TITLE
Remove TS extra type hints that were used to fix an issue with the `connect()` HOC

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#585]
We added type hints to help TS validate the public APIs of our exported connected components because there was an issue with `connect()` loosing the prop types (especially when combined with default props).

Here is an example of type hint:

```js
export default connect(mapStateToProps)(Foo) as React.ComponentType<PublicProps & Partial<DefaultProps>>;
```

This issue seems to be fixed, so we could remove the type hint and only keep the connected component export:

```js
export default connect(mapStateToProps)(Foo);
```

In order to make sure we don't introduce a weakness in our code, please make sure that TS validates the public API of each component by:

- adding an unknown prop in the Storybook file
- adding an unknown prop in the test file

**Comment by mirefly** [comment]
@willdurand 
I removed ` as React.ComponentType<PublicProps & Partial<DefaultProps>>`, then manually tested that adding an unknown prop to the Storybook and test file triggers TS compilation error like "Type ... is not assignable to type ....". I just want to make sure the Storybook and test files should not be changed in the commit, right?

**Comment by willdurand** [comment]
> I just want to make sure the Storybook and test files should not be changed in the commit, right?

Yep, I don't think we should change those files.
