### ISSUE TITLE
Open parent folders for the default file

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#586]
This is a follow-up to #566 

When we first load a version, and set the `selectedPath` to whatever the API returned, we should also add the parent folders for that file to `expandedPaths` so that the tree appears expanded to that point. We know for now that it will always just be a file in the root folder, so we could just make sure that the root folder is added to `expandedPaths`, but I think it's worth implementing a proper solution which takes into account the value of `selectedPath`.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
The parent (root) folder is automatically expanded when the the default file - manifest.json - is opened in the browse and compare pages:

https://code.addons-dev.allizom.org/en-US/browse/616658/versions/1655548/

![2019-04-23_12-15-10](https://user-images.githubusercontent.com/31961530/56569738-40660780-65c2-11e9-96a6-ff99978d553f.gif)
