### ISSUE TITLE
Provide keyboard shortcuts for navigating through file messages

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#587]
This is a spin-off from #199.
This depends on #520.

The shortcuts should be:
`p` - previous note
`n` - next note

When moving to a next or previous message, if the current file does not have one, go to the next or previous file with a message.

If at the last message in the file, or the first message in the file, and trying to go to the next or previous message, respectively, wrap around to the first/last message, respectively.

**Comment by kumar303** [comment]
How is this different from https://github.com/mozilla/addons-code-manager/issues/520 ?

**Comment by kumar303** [comment]
@bobsilverberg is this because https://github.com/mozilla/addons-code-manager/issues/520 will only jump between inline messages, not global file messages?

**Comment by bobsilverberg** [comment]
No, this is actually superfluous now. I guess my original thought was to implement all of the functionality, but without the keyboard shortcuts, in #520, but now my plan is to finish the feature, including the keyboard shortcuts in #520, so this can be closed.
