### ISSUE TITLE
Provide keyboard shortcuts for hiding and unhiding the file tree

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#588]
This is a spin-off from #199.

The shortcut should be:
`h` - hide or unhide tree

It should be a toggle which either hides or unhides the tree based on the current state.

We might want to discuss this one a bit, because at this point just hiding or unhiding the tree won't free up real estate for the file contents because there are other things on the left-hand side. I.e., keyboard shortcuts and file metadata. We probably need to define a new view which allows for more screen real estate for the file contents, but which keeps the keyboard shortcuts available and also the file metadata.

Here are examples from the current app:

With tree unhidden:
![Screenshot 2019-04-15 14 41 36](https://user-images.githubusercontent.com/142755/56157145-c95ebc80-5f8c-11e9-8fbb-46e00873d9e7.png)

With tree hidden:
![Screenshot 2019-04-15 14 41 51](https://user-images.githubusercontent.com/142755/56157135-c237ae80-5f8c-11e9-9e10-d0ca598daea1.png)

With tree hidde, hovering over the folder icon shows the tree:
![Screenshot 2019-04-15 14 42 00](https://user-images.githubusercontent.com/142755/56157120-ba780a00-5f8c-11e9-82d8-d334b69ec95f.png)

@wagnerand / @kumar303 / @willdurand what do you think?

**Comment by willdurand** [comment]
Could we try to build a sidebar _à la_ GitLab, which we could collapse but still keep in the page?

Menu expanded:

<img width="1392" alt="Screen Shot 2019-04-15 at 21 47 18" src="https://user-images.githubusercontent.com/217628/56160696-24fa6b80-5fc8-11e9-9d2d-1017431fd797.png">

Menu collapsed:

<img width="1392" alt="Screen Shot 2019-04-15 at 21 47 20" src="https://user-images.githubusercontent.com/217628/56160697-24fa6b80-5fc8-11e9-99fe-247a3c885bd7.png">

This is a menu here but we could build something similar for the left panel.

**Comment by bobsilverberg** [comment]
> Could we try to build a sidebar _à la_ GitLab, which we could collapse but still keep in the page?

I like that, very nice @willdurand! I think we might also want to make sure the file metadata remains visible in this collapsed state. The old app used a footer, which worked well for this, but one of the issues with a footer is that it gets pushed off the page when the file is too large. Although I suppose the same happens with our current layout when the tree is too large as well.

Maybe a file metadata header, which always appears above the left-nav and the file contents, would be better?

**Comment by kumar303** [comment]
Ah, yes, I think an accordion menu (a left-hand nav with *files*, *information*, and *keyboard shortcuts*) would look nice. We could go all in on a fixed layout (header and side navs) with just the center area scrollable. Example: https://react-redux.js.org/api/connect

I started a quick prototype for https://github.com/mozilla/addons-code-manager/issues/582 (it solves other problems, too!) but it's not laid out correctly yet

<img width="1087" alt="Screenshot 2019-04-15 17 22 04" src="https://user-images.githubusercontent.com/55398/56169235-1b124180-5fa3-11e9-85ee-0283b6457b1c.png">

**Comment by wagnerand** [comment]
The footer could also be static (actually `relative` iirc) and always be shown. The `h` shortcut could be expanded into a *focus* mode, that would collapse file tree and footer, freeing up space in order to focus on the currently shown code.

**Comment by willdurand** [comment]
@kumar303 @wagnerand how about having this state below when a user uses the shortcut or a button to collapse the left panel?

![Screen Shot 2019-05-08 at 18 00 35](https://user-images.githubusercontent.com/217628/57389826-49a6c500-71bb-11e9-96c0-0f03dd0424df.png)

**Comment by bobsilverberg** [comment]
> @kumar303 @wagnerand how about having this state below when a user uses the shortcut or a button to collapse the left panel? The thing to focus on is the left panel that is transformed into a button. Clicking the button reveals the accordion menu.

I know I wasn't asked, but I think it looks good!

**Comment by wagnerand** [comment]
Looks great!

**Comment by willdurand** [comment]
I opened a draft PR with a demo of what I posted above: https://github.com/mozilla/addons-code-manager/pull/721#issue-277405846. Let me know what you think!

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx67  Win10x64

The file tree can be hidden/expanded with the `h` key:

![2019-06-19_15-27-28](https://user-images.githubusercontent.com/31961530/59765923-cdb69700-92a7-11e9-97c6-550b874d300b.gif)
