### ISSUE TITLE
Link to a URL for viewing a single file (compare page)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#590]
This is similar to #286 but for the compare page, e.g,  https://code.addons-dev.allizom.org/en-US/compare/502955/versions/1541794...1541798/.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx66, Win10x64

![2019-04-22_17-04-36](https://user-images.githubusercontent.com/31961530/56504336-e3664500-6520-11e9-8a99-92563bd935fc.gif)
