### ISSUE TITLE
Too many actions are dispatched when loading a file by path

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#591]
### Describe the problem and steps to reproduce it:

1. Open the Redux devtools
2. Load http://localhost:3000/en-US/browse/494431/versions/1532144/?path=notification.js

### What happened?

There are lots of `BEGIN_LINTER_RESULT` and `LOAD_LINTER_RESULT` actions dispatched.

### What did you expect to happen?

Only one `BEGIN_LINTER_RESULT` and one `LOAD_LINTER_RESULT` are dispatched.

### Anything else we should know?

The default file is not yet affected because of #586.

It looks like we cannot prevent all but the first action to be dispatched even though we have a loading flag in the state to avoid this issue... Thunks are asynchronous and that's probably the reason.

This diff "fixes" the issue:

```diff
diff --git a/src/reducers/linter.tsx b/src/reducers/linter.tsx
index 4b41911..d7d0239 100644
--- a/src/reducers/linter.tsx
+++ b/src/reducers/linter.tsx
@@ -177,7 +177,12 @@ export const fetchLinterMessages = ({
   url: string;
   versionId: number;
 }): ThunkActionCreator => {
-  return async (dispatch) => {
+  return async (dispatch, getState) => {
+    if (getState().linter.isLoading) {
+      log.info('early return');
+      return;
+    }
+
     dispatch(actions.beginFetchLinterResult({ versionId }));
 
     // This is a special URL and returns a non-standard JSON response.
```

**Comment by willdurand** [comment]
The author of Redux suggests to put the conditional statement inside the thunk in https://egghead.io/lessons/javascript-redux-avoiding-race-conditions-with-thunks. There is also an example in the Redux's README.

**Comment by AlexandraMoga** [comment]
Would this issue explain why there might be some lag when switching between files inside the file tree, especially when the files have many lines of code?
For this addon, when I switch to the following file -  https://code.addons-dev.allizom.org/en-US/browse/385621/versions/1655456/?path=public%2Fjs%2Fbackground.js  - the loading time is too long and the browser will throw the below error:

![image](https://user-images.githubusercontent.com/31961530/56297197-99541c80-6138-11e9-8905-665e8dad520f.png)

**Comment by willdurand** [comment]
> Would this issue explain why there might be some lag when switching between files inside the file tree, especially when the files have many lines of code?

Yep

**Comment by AlexandraMoga** [comment]
The `validation.json` file is fetched only once, when a browse or compare page is loaded. Also I wasn't able to reproduce the browser freeze error from before.

There still is some lag when switching between larger files and it takes quite a bit of time for the content to be loaded.
[This addon](https://code.addons-dev.allizom.org/en-US/browse/596951/versions/1635812/) is a good example. You'll be able to find a few large files in the `script` folder.
