### ISSUE TITLE
The parent folder closes when a new file is selected in the compare view

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#592]
**STR:**

1. Open the compare view for an addon - see https://code.addons-dev.allizom.org/en-US/compare/616548/versions/1655558...1655559/
2. Click on the Parent folder and select another file from the list

**Actual result:**
The parent folder closes

**Expected result:**
The parent folder stays open

**Notes:**
- this might be fixed when a solution for #586 is found, but I wasn't sure about this case
- I don't remember seeing this behavior before, so it might be a very recent regression

![2019-04-16_13-03-31](https://user-images.githubusercontent.com/31961530/56201488-a9410300-6049-11e9-8f15-ce1409b3894b.gif)

**Comment by willdurand** [comment]
It seems `LOAD_DIFF` collapses the file tree for some reason.

**Comment by bobsilverberg** [comment]
Sure, I can investigate this one @willdurand.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx66, Win10x64

![2019-05-07_14-34-08](https://user-images.githubusercontent.com/31961530/57296264-3cafa600-70d5-11e9-8683-b134906dd0a4.gif)
