### ISSUE TITLE
The contrast between selectable and non-selectable versions in the compare file lists should be more evident

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#595]
Follow up for #415 

**STR:**

1. Go to the compare view for an add-on: https://code.addons-dev.allizom.org/en-US/compare/616548/versions/1655415...1655559/
2.  Open the  `Choose a new version` list
3. Look at the available entires to see which are selectable and which not

**Actual result:**
At a first glance, it is hard to tell which versions are available for selection

**Expected result:**
There should be a more evident contrast between selectable and non-selectable versions

**Notes:**
- reproduced on -dev with FF66, Win10x64 and macOS High Sierra 10.13.6

- in this case, `1.1` and `1.0` are disabled, but you can't immediately tell.
![2019-04-12_15-15-47](https://user-images.githubusercontent.com/31961530/56037126-44c73080-5d37-11e9-9c0e-f86a0f7bab70.gif)

 - on mac:
![image](https://user-images.githubusercontent.com/31961530/56044024-02a5eb00-5d47-11e9-98a5-26edbea3dfcc.png)

**Comment by AlexandraMoga** [comment]
I think I know why we had differences before. It looks like on Firefox release ( I have the latest 66.0.3), the contrast issue is still present. This goes back to older FF versions as well. 

On Beta 67 and Nightly (and other non-FF browsers) the contrast looks fine:

- Win10x64, with Beta 67
![image](https://user-images.githubusercontent.com/31961530/56416509-bf450280-6299-11e9-8591-cd1f8737fafc.png)

- macOS with Nightly
![image](https://user-images.githubusercontent.com/31961530/56416540-d5eb5980-6299-11e9-982e-a70a9733904d.png)

So, this has been a browser issue all along.

**Comment by willdurand** [comment]
@AlexandraMoga could you please provide a screenshot with release?

**Comment by AlexandraMoga** [comment]
On release, the contrast is basically the same as before:

Win10 - the highlighted versions are non-selectable:
![image](https://user-images.githubusercontent.com/31961530/56486552-a8442180-64e0-11e9-8fa6-baa79dccc543.png)


Mac:
![image](https://user-images.githubusercontent.com/31961530/56486563-b003c600-64e0-11e9-971c-234646d68e7e.png)
