### ISSUE TITLE
Infinite loop for 404 errors generated by an invalid addon/version id in the browse view

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#602]
**STR:**

Open the browse view for an add-on and make sure that either the addon or the version Id is incorrect:
see https://code.addons-dev.allizom.org/en-US/browse/616653/versions/1655549/

**Actual result:**
An infinite loop for the 404 error 

**Expected result:**
The 404 error and its corresponding message should be caught only once

![2019-04-17_13-29-24](https://user-images.githubusercontent.com/31961530/56281721-ff7b7800-6115-11e9-8abf-8e07ca0062f2.gif)

**Comment by vcarciu** [comment]
Verified as fixed : 
![404](https://user-images.githubusercontent.com/1583842/57084669-664a8500-6d03-11e9-8a45-2fa9e2b892bb.png)
