### ISSUE TITLE
Use `Skeleton` components in `VersionChooser`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#608]
Instead of rendering a `Retrieving all the versions [...]` message when navigating to [a new "compare" page](https://code.addons-dev.allizom.org/en-US/compare/502955/versions/1541794...1541798/), we should render the component with most of its content (all the static content can be rendered) and `Skeleton` (a.k.a. fake animations) where we have dynamic content.

The dynamic content for this component are the two `select`/dropdown lists.

**Comment by AlexandraMoga** [comment]
Verified on -dev with Fx66, Win10x64
Loading animations are now visible in the version chooser drop down lists for a compare page.

https://code.addons-dev.allizom.org/en-US/compare/616548/versions/1655411...1655560/
![2019-04-23_12-43-48](https://user-images.githubusercontent.com/31961530/56571706-2fb79080-65c6-11e9-986b-b8890e6b731f.gif)
