### ISSUE TITLE
Fetch linter messages when switching versions (and other cleanup)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#611]
This is a follow-up to https://github.com/mozilla/addons-code-manager/issues/591

Here are some change requests: https://github.com/mozilla/addons-code-manager/pull/600#pullrequestreview-228022478

**Comment by AlexandraMoga** [comment]
@willdurand can I test anything for this issue?

**Comment by willdurand** [comment]
nope, thanks
