### ISSUE TITLE
Links to specific file paths are no longer working in the browse page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#626]
**STR:**

Open the browse files page for the following addon: https://code.addons-dev.allizom.org/en-US/browse/385621/versions/1655456/?path=html%2Ffeedback.html

**Actual result:**
You are redirected to the default file - manifest.json - even though a different file path is specified in the URL

**Expected result:**
You are viewing the file specified in the URL

**Notes:**
 - this is not happening in the compare page
 - could be a regression from #596  because this function used to work before

![2019-04-22_16-57-40](https://user-images.githubusercontent.com/31961530/56504017-e3b21080-651f-11e9-9e09-b0c5a55e3d41.gif)

**Comment by willdurand** [comment]
Yes it looks like https://github.com/mozilla/addons-code-manager/pull/596 introduced an issue 😞

**Comment by vcarciu** [comment]
Verified as fixed : 
![specificpath](https://user-images.githubusercontent.com/1583842/57134721-b0894000-6daf-11e9-9318-1a611bc2c4ba.png)
