### ISSUE TITLE
Infinite loop when quickly switching files in compare view

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#628]
### Describe the problem and steps to reproduce it:

* Sign in
* Go to https://code.addons-dev.allizom.org/en-US/compare/502955/versions/1541794...1541798/?path=popup/popup.js
* Press `k` seven times, very quickly, as if you were using the keyboard to ascend a big file tree

### What happened?

The selected file flickers repeatedly, loading diffs in an infinite loop.

### What did you expect to happen?

I'd expect the UI to select the files as I navigate but only load the diff once I am done navigating.

### Anything else we should know?

* If you only press `k` twice or three times, it doesn't get stuck in a loop. That's odd.
* This might be related to the [use of `prevProps`](https://github.com/mozilla/addons-code-manager/pull/385#discussion_r265723893) but I'm not sure.
* I researched whether we can debounce thunks and I guess we can but I'm hesitant to do this unless we really have to. State changes like this should not *cause* an infinite loop, I think?
* The thunk itself does not check if another thunk is in progress but that may not be the final solution since we do actually want the last thunk to execute.
* [`saga.takeLatest()`](https://redux-saga.js.org/docs/api/#takelatestpattern-saga-args) was an easy way to solve this. D'oh

**Comment by vcarciu** [comment]
Verified as fixed : 
![k](https://user-images.githubusercontent.com/1583842/57077802-9b4fdb00-6cf5-11e9-9afc-cc389c87ec59.gif)
