### ISSUE TITLE
Selecting a line of code inside a larger file is not immediately highlighted in the UI

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#630]
**STR:**

1. Open the browse page for an add-on and select a large file to inspect - see https://code.addons-dev.allizom.org/en-US/browse/596951/versions/1635812/?path=scripts%2Fbackground_analytics.js
2. Click on a line of code inside the opened file
3. Observe how the UI reacts

**Actual result:**
The line doesn't appear highlighted immediately after its selection

**Expected result:**
The UI should immediately reflect the line that has been selected

**Notes:**
- reproduced on -dev with Fx66, Win10x64

![2019-04-23_17-13-07](https://user-images.githubusercontent.com/31961530/56588973-09591b80-65ed-11e9-8588-dada2151e584.gif)

**Comment by kumar303** [comment]
This was happening because the file renders slowly. We now have a workaround (the file is truncated) but really we need a holistic solution here.

**Comment by AlexandraMoga** [comment]
Still reproduces

**Comment by willdurand** [comment]
@bobsilverberg not a new issue afterall
