### ISSUE TITLE
Infinite loop in Compare page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#638]
### Describe the problem and steps to reproduce it:

1. Load an incorrect file in the compare page, e.g., https://code.addons-dev.allizom.org/en-US/compare/502955/versions/1541794...1541798/?path=META-INF%2Fmozilla.fsf

### What happened?

The page tries to re-fetch the data even though the filename (in `?path=`) is incorrect.

### What did you expect to happen?

No retry, it should only display **one* error.

**Comment by vcarciu** [comment]
Verified as fixed : 
![noloop](https://user-images.githubusercontent.com/1583842/57085256-7f076a80-6d04-11e9-8049-5a96a5ac27fe.png)
