### ISSUE TITLE
Shortcuts `o` and `c` for open and close folders makes page jump unexpectedly

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-code-manager#642]
### Describe the problem and steps to reproduce it:

When using `o` and `c` to open and close folders, the page jumps up and down unexpectedly. 

### What happened?

Unexpected scrolling/jumping.

### What did you expect to happen?

No scrolling, or some predictable scrolling?

### Anything else we should know?

It seems that you have to scroll down to make the top level folder go out of the viewport in order to reproduce this. I couldn't reproduce it when being at the top of the page.

![2019-04-24 19 58 44](https://user-images.githubusercontent.com/873258/56682523-fc5f2980-66cb-11e9-9a68-de7f3bbdc3b3.gif)

**Comment by AlexandraMoga** [comment]
Now that the file tree and the code viewer live in separate panels, I don't think this is reproducible anymore. - at least I didn't find a way to reproduce it.
@wagnerand if you run into the issue again, please let us know.

**Comment by kumar303** [comment]
Yep, this was fixed by https://github.com/mozilla/addons-code-manager/issues/653 . Thanks for the bug report, though.
