### ISSUE TITLE
File tree flickers when pressing `k`/`j` too rapidly

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#644]
### Describe the problem and steps to reproduce it:

1. Go to a compare page
2. Make sure you are at the bottom of the file tree list (use the mouse to select the last file in the tree)
2. Press <kbd>k</kbd> multiple times rapidy

### What happened?

The UI lags and the file tree flickers.

### What did you expect to happen?

A file is selected and there is no flicker.

### Anything else we should know?

From: https://github.com/mozilla/addons-code-manager/pull/639#issuecomment-486603111

**Comment by kumar303** [comment]
This looks fixed to me. I tried a couple different compare pages. The debouncing I mentioned in the comment might still be helpful to reduce network requests but the UI no longer flickers because of it so I'm closing the issue.
