### ISSUE TITLE
File metadata (info) is not displayed on the compare page

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#647]
I don't know if this is intentional, but it seems like a missing feature to me. The "Information about this file" box is shown on the Browse page, but not on the Compare page.

**Comment by kumar303** [comment]
Yeah, we should show file info on the compare page. The info would be related to the head / newer version. Showing a download link and hash all seem like useful things.

**Comment by ioanarusiczki** [comment]
Verified on -dev with FF67(Win10). 
Looks good to me. 
I used the following compare view
https://code.addons-dev.allizom.org/en-US/compare/495710/versions/1541610...1688333/

![Information for file](https://user-images.githubusercontent.com/33448286/60433737-338f1100-9c0e-11e9-9b02-b897ad7906f3.gif)
