### ISSUE TITLE
Make side panels accessible when the file tree is open

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#653]
After https://github.com/mozilla/addons-code-manager/issues/652 we'll have a side panel that stays in one place and lets you scroll through the overflow. This is nice for long file trees but it obscures the metadata and keyboard shortcuts panels. 

Let's make it so you can still scroll through long file trees but also access the other panels more easily. I'm thinking of an [accordion menu](http://ui-patterns.com/patterns/AccordionMenu).

Ultimately, this aims to make the file tree easier to use. See https://github.com/mozilla/addons-code-manager/issues/582

**Comment by AlexandraMoga** [comment]
@kumar303 I've used the new side panel menus to navigate the file tree and I didn't find any significant issues with this new structure.

I can mention a couple of 'hindrances' that one might consider:

1. having to keep switching between different views, especially between the 'Files' and 'Information' menus is probably not an ideal workflow. I know this will steal some space in the file tree, but maybe we should consider leaving the information panel open whenever a file is selected?
2. I'm not sure if I remember correctly, but wasn't the code manager supposed to be usable on smaller viewports? The new layout doesn't look very responsive to me:

![image](https://user-images.githubusercontent.com/31961530/57440489-ccc62a80-7250-11e9-9eea-54ea13ee95d3.png)

**Comment by kumar303** [comment]
>     1. having to keep switching between different views, especially between the 'Files' and 'Information' menus is probably not an ideal workflow. I know this will steal some space in the file tree, but maybe we should consider leaving the information panel open whenever a file is selected?

I asked the reviewers about this and they don't think it will be a problem. They don't need to frequently access the information panel.

> 
>     2. I'm not sure if I remember correctly, but wasn't the code manager supposed to be usable on smaller viewports?

We don't intend to support smaller viewports at this time.
