### ISSUE TITLE
Always link directly to linter messages in the overview

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#665]
### Describe the problem and steps to reproduce it:

After https://github.com/mozilla/addons-code-manager/issues/523 lands ...
- Browse a long file in a version that has linter messages
- Make the height of the window smaller so that the file fills the whole overview
- Click on a linter message from the overview

### What happened?

The link takes you to a line *above* the actual linter message line

### What did you expect to happen?

It should take you directly to the linter message line

### Anything else we should know?

This is because lines are grouped together in the overview in "windows" to make all of the lines fit.

**Comment by vcarciu** [comment]
Verified as fixed : 
![linterline](https://user-images.githubusercontent.com/1583842/57145013-03bcbc00-6dcb-11e9-9d98-edb2d13f74d2.gif)
