### ISSUE TITLE
Error displaying files with special characters in name

### ISSUE THREAD

**Issue by psiinon** [mozilla/addons-code-manager#666]
Add-ons can contain files with 'non standard' characters in them, and these can prevent those files from being displayed.
In this case the file name is '<script>alert(1);' - its worth noting that the script is _not_ run :)
![amo-bad-files](https://user-images.githubusercontent.com/1081115/56963418-2b0c5280-6b59-11e9-8a4f-c61331f86eae.png)

**Comment by kumar303** [comment]
I love how the issue ID for this was 666. Nice one.

@psiinon Good find. Can you attach the add-on XPI that caused this to https://github.com/mozilla/addons-server/issues/11297 ?

**Comment by psiinon** [comment]
Yeah, pure serendipity - I honestly didnt hang on just to get that ID :D
Have attached a ZIP that exhibits several such problems.

[weird-file-names2.zip](https://github.com/mozilla/addons-code-manager/files/3137026/weird-file-names2.zip)

**Comment by willdurand** [comment]
> @psiinon Good find. Can you attach the add-on XPI that caused this to [mozilla/addons-server#11297](https://github.com/mozilla/addons-server/issues/11297) ?

This needs confirmation but it looks like a pure server bug, isnt it?

**Comment by kumar303** [comment]
> This needs confirmation but it looks like a pure server bug, isnt it?

It probably is but it's possible that fixing the bug could trigger something new in the UI so we might as well wait on the server fix and see what happens.

**Comment by willdurand** [comment]
Unblocking this issue as we can fix it in code-manager itself.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx66, Win10x64

The error above can no longer be reproduced with file names containing special characters

![2019-05-07_14-47-51](https://user-images.githubusercontent.com/31961530/57297077-505c0c00-70d7-11e9-8bfb-2b4ef3f2b988.gif)
