### ISSUE TITLE
Add CodeOverview support to the compare page

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#672]
A CodeOverview component was added in https://github.com/mozilla/addons-code-manager/issues/523 to provide an overview of the entire file while in browse mode.

Let's add this feature to the compare mode. Since the compare mode shows the diff in context of the *newer* file then showing an overview of the newer file would be helpful. You could, for example, navigate to linter messages more easily.

**Comment by ioanarusiczki** [comment]
Verified on AMO dev and stage - FF67 -Win10 

![code overview in compare](https://user-images.githubusercontent.com/33448286/60183809-a7f13b00-982f-11e9-97b4-58772190ba41.gif)
