### ISSUE TITLE
switch api to v5

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-code-manager#675]
mozilla/addons-server#11328 is going to rename v4dev to v5 so addons-code-manager is going to have to rename too.  Plus, without mozilla/addons-server#11328 (or some other patch) v4dev isn't available in prod addons-server.

**Comment by AlexandraMoga** [comment]
I've navigated in the browse and compare pages on both -dev and stage and they seem to be functional. All api requests are made to `api/v5`.

I think this can be marked as verified fixed.
