### ISSUE TITLE
Global linter messages are not visible in the overview

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-code-manager#677]
Steps to reproduce:
1. Go to https://code.addons-dev.allizom.org/en-US/browse/494431/versions/1532144/?path=manifest.json
2.Observe the linter message at the beginning

Expected results:
The linter message should be signaled in the right side in order to be able to directly scroll at its position if you are in the middle of a long file

Actual result:
Linter message not highlighted at all 

Please see a screenshot for the issue :
![lintbegin](https://user-images.githubusercontent.com/1583842/57141499-fc91b000-6dc2-11e9-8cde-4715b89262ae.png)

**Comment by bobsilverberg** [comment]
I think this is a good point. I recall that, when reviewing the code, it was intentional to not include them in the `CodeOverview`, which does make sense when you're at the top of the file. If you scroll down farther, however, it seems reasonable to expect an indication in the overview that there is a message at the top of the file.

**Comment by willdurand** [comment]
Note that these are global messages, not inline messages.

**Comment by bobsilverberg** [comment]
> Note that these are global messages, not inline messages.

Correct, but it still seems worthwhile to indicate that they exist in the overview.

**Comment by kumar303** [comment]
I think makes sense to display global messages in the overview, at least for consistency.

**Comment by ioanarusiczki** [comment]
Verified on dev with FF70(Win10). 

![global messages shown](https://user-images.githubusercontent.com/33448286/70446454-c9747500-1aa5-11ea-9a21-7e38cfb463de.png)
