### ISSUE TITLE
Decouple KeyboardShortcuts from FileTree

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#678]
Currently, `KeyboardShortcuts` (https://github.com/mozilla/addons-code-manager/issues/459) is coupled with `FileTree` because it relies on the [`tree.pathList`](https://github.com/mozilla/addons-code-manager/blob/f1672ff648a02551eb4b1b7329524943a35d158c/src/components/FileTree/index.tsx#L175). This makes it difficult to render `KeyboardComponents` *outside* of `FileTree`.

Let's make it easier to render `KeyboardComponents` on its own.

**Comment by bobsilverberg** [comment]
This makes sense, but just FYI, one of the reasons I did it that way is because the keyboard shortcuts do not make any sense outside of the context of a `FileTree`, so I wanted to ensure that they are never mounted/rendered unless a tree exists.

**Comment by kumar303** [comment]
> I wanted to ensure that [keyboard shortcuts] are never mounted/rendered unless a tree exists.

We can still do this while decoupling the component. We could either make a parent component responsible for loading the file tree (and passing it as a prop) or make a file tree provider component that the both of them could use.

Really, I just filed this issue so I can land https://github.com/mozilla/addons-code-manager/issues/653 with a temporary solution. The quickest fix was to just let `KeyboardComponents` look for a tree in state and do nothing when one doesn't exist. That's not ideal, though.
