### ISSUE TITLE
Stop the version dropdowns on the compare page from scrolling out of view

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#679]
**For QA:** check that browsing the compare page and switching between versions still works.

The app layout entered a fullscreen grid in https://github.com/mozilla/addons-code-manager/issues/652

The compare page is a bit hard to use (but not harder than before!) because the version dropdowns scroll out of view when you scroll through a diff.

<details>
<summary>Example screencast</summary>

![2019-05-03 08 48 27](https://user-images.githubusercontent.com/55398/57141727-89674a00-6d80-11e9-8327-e246cf6df6a1.gif)

</details>

Let's make the controls sticky to fix this.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx66, Win10x64

Browsing the compare page is still working, you can change between files and select various versions to compare

![2019-05-07_13-11-54](https://user-images.githubusercontent.com/31961530/57292144-c194c280-70c9-11e9-8de9-192ffd28d740.gif)
