### ISSUE TITLE
Add a UI framework

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#7]
We want something simple. There are two options:

- Bootstrap with [react-bootstrap](https://react-bootstrap.netlify.com/) but v4 support isn't stable yet!!
- Primer (GitHub's CSS framework): https://primer.style/components

Note: https://github.com/otakustay/react-diff-view is very GitHub-oriented, so using Primer would make things more consistent, I (willdurand) suppose.

**Comment by bobsilverberg** [comment]
Looking at the two projects mentioned above, neither seem to be available as stable yet.

- React-bootstrap is in beta (for the version supporting bootstrap v4)
- Primer Components has a big warning on the front page "This project is not production-ready yet!"

We could just use the [Primer styles](https://primer-css.now.sh/css), and not the Primer Components package, but then we're getting styles as opposed to a UI library. I think they're probably both used widely enough/from a reliable enough source, that we could go with either and not worry too much about the fact that neither are officially final yet.

Taking a quick look around Primer, I'm not sure that much of what it includes we actually need, as it's quite geared towards GitHub. If we want our app to look like GitHub (which isn't a bad idea), then I think going with Primer makes sense. If we don't care about that, and are just concerned with the functionality available from the library, I think the more popular/widely used Bootstrap might be a better choice.

@willdurand / @kumar303 What do you think about:
- Primer vs. Bootstrap
- Whether we should use a beta/unstable lib

**Comment by willdurand** [comment]
I believe Bootstrap has more components and we should adopt a UI lib, not just some CSS stylesheets.

Can we consider Material UI too? Asking because it is well maintained, stable (AFAIK) and it looks nice. Of course, it is a bit "Google-like" but so is Bootstrap with Twitter.

If not then my vote goes to Boostrap unstable. Primer has indeed not a lot of components.

**Comment by kumar303** [comment]
@muffinresearch has used Bootstrap components -- it looks more mature to me when compared to Primer components. I haven't looked at Material UI.

**Comment by bobsilverberg** [comment]
Material UI sounds like something to look at. I've certainly seen it mentioned in a lot of code examples I've come across over the past couple of weeks.

I think it might make sense to hold off on choosing a UI framework until we have at least a little bit to style, or we have an idea of what the product will look like. We don't have any mocks for anything, right? How do we plan on addressing that?

**Comment by willdurand** [comment]
Let's go for Bootstrap v4 components (unstable).
