### ISSUE TITLE
Create a getRelativeDiff function to return an anchor or path for the next/previous diff

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#702]
This supports #615 

The `getRelativeDiffAnchor` function we have will be useful on its own for locating the first anchor in a file, but we also need to be able to navigate between diffs in the current file *and* to be able to navigate to the next/previous file with a diff. 

This issue is about creating a `getRelativeDiff` which will return either an anchor or a path depending on whether the next diff is in the current file or a different file.

This new function can then be used in conjunction with a keyboard shortcut and action to navigate between diffs.

**Comment by AlexandraMoga** [comment]
@bobsilverberg could you please add some guidelines for QA if there is anything we can verify?
Thanks

**Comment by bobsilverberg** [comment]
Oops, sorry @AlexandraMoga. No QA needed.
