### ISSUE TITLE
Horizontal scrolling is not available for image viewing

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#704]
Follow up for #109 

**STR**

1. Open the browse files page for an add-on
2. Look for an image file that has a larger width - for example https://code.addons-dev.allizom.org/en-US/browse/8542/versions/1655535/?path=images%2Fnewlogo%2FLastPass_Black.png

**Actual result:**
There is no horizontal scrolling available

**Expected result:**
Horizontal scrolling should be possible for wider images 

Notes:
reproduced on -dev with Fx66, Win10x64

**Comment by kumar303** [comment]
https://github.com/mozilla/addons-code-manager/pull/803 made this invalid 🥇
