### ISSUE TITLE
Implement server code in TypeScript

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#71]
We are about to ship some server logic in https://github.com/mozilla/addons-code-manager/pull/56/ but it's not type safe. This logic will be very important to get right so let's port it to TypeScript. This will probably require a new webpack entry point and other annoying things.

**Comment by willdurand** [comment]
> This will probably require a new webpack entry point and other annoying things.

I believe we can add a post npm script to build the server code with `tsc`. I'd rather keep things simple, especially because the amount of code is small enough (even if I anticipate 2x more code with all the extra TS code, but still :D).

**Comment by willdurand** [comment]
In order to ease the build/run in both dev and prod modes, without having to add too many dependencies, I was thinking about using https://github.com/zeit/ncc.

**Comment by willdurand** [comment]
> `ncc` seems like it might be overkill. If we run `tsc` on `server.tsx`, it will just generate `server.js` and we can execute that, right?

Not sure because we have a source file and a script file. We could merge both, maybe.

**Comment by willdurand** [comment]
We also need the server in dev mode, ideally without the compilation step.

**Comment by willdurand** [comment]
So, I managed to start the server in both dev and prod using `ts-node`.

**Comment by willdurand** [comment]
You'll find more explanations in the PR description.
