### ISSUE TITLE
Delete a comment on a specific line of a file

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#714]
User story:

> After adding a comment (https://github.com/mozilla/addons-code-manager/issues/113, https://github.com/mozilla/addons-code-manager/issues/112) as a reviewer, decide you want to delete a comment before submitting it to the developer (https://github.com/mozilla/addons-code-manager/issues/114)

**Comment by kumar303** [comment]
This depends on an API change https://github.com/mozilla/addons-server/issues/11380

**Comment by EnTeQuAk** [comment]
mozilla/addons-server#11380 has landed so I think the API should be in place now to tackle this. Just let me know if you need anything else on top of that though.

**Comment by ioanarusiczki** [comment]
@kumar303 I tested this on dev with FF69(Win10). 

The functional testing : the button is working. A delete can be done using the `Delete` button.
Also as mentioned in https://github.com/mozilla/addons-server/issues/11380 the Delete through API works as expected. 

Test results:
- when the code line is long the button is not visible on the page. Also for shorter code lines when I resize the browser the button won’t be visible unless I do not collapse the side panels. Perhaps a shorter standard length of the text box would fix both cases?

![scroll to the right to see delete](https://user-images.githubusercontent.com/33448286/67212114-83475180-f424-11e9-914d-d2d35355d613.gif)

![resize the screen](https://user-images.githubusercontent.com/33448286/67212135-89d5c900-f424-11e9-9733-d42ce7551a30.gif)

- I'd increase the contrast between the background and the border for `Cancel` and `Delete,really`.
- I’d replace `Delete, really?` with `Confirm`.
- I tried to see what happens with `Delete` when I log back in with another reviewer account so I filed https://github.com/mozilla/addons-code-manager/issues/1143

**Comment by kumar303** [comment]
Thanks for the detailed feedback on this.

>  when the code line is long the button is not visible on the page. Also for shorter code lines when I resize the browser the button won’t be visible unless I do not collapse the side panels. Perhaps a shorter standard length of the text box would fix both cases?

Can you file an issue for that? Until we fix https://github.com/mozilla/addons-code-manager/issues/997 we could move the delete button to the left to address these issues.

>  I'd increase the contrast between the background and the border for `Cancel` and `Delete,really`.

Good idea. Can you file an issue?

>  I’d replace `Delete, really?` with `Confirm`.

Yeah, this makes sense but the confirmation state should still convey that a deletion is about to happen. Can you file an issue to make it *Confirm delete* instead of *Delete, really?*. I think that will make it more clear and still provide enough context.

**Comment by ioanarusiczki** [comment]
@kumar303 Done.
This issue is verified on dev with FF69(Win10).
