### ISSUE TITLE
Edit a comment on a specific line of a file

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#715]
User story:

> After adding a comment (https://github.com/mozilla/addons-code-manager/issues/113, https://github.com/mozilla/addons-code-manager/issues/112) as a reviewer, decide you want to edit it before submitting to the developer (https://github.com/mozilla/addons-code-manager/issues/114).

**Comment by kumar303** [comment]
This depends on an API change: https://github.com/mozilla/addons-server/issues/11379

**Comment by EnTeQuAk** [comment]
mozilla/addons-server#11379 has been landed, so I think the `needs: api` label should be safe to remove. Let me know if you need anything specific on top of that though.

**Comment by mirefly** [comment]
@kumar303 Could I work on this?

**Comment by kumar303** [comment]
@mirefly yes, for sure! Thanks

**Comment by ioanarusiczki** [comment]
@mirefly I verified on dev and the Edit button is available. Text can be edited and saved.
Should the comments allow some HTML text such and for bold <b>,<italic> or even links?

**Comment by mirefly** [comment]
@ioanarusiczki Thanks for verifying it. I am not sure if the reviewers uses HTML formatting comments. @wagnerand @bobsilverberg do we want to support it?

**Comment by bobsilverberg** [comment]
> @ioanarusiczki Thanks for verifying it. I am not sure if the reviewers uses HTML formatting comments. @wagnerand @bobsilverberg do we want to support it?

Considering that the current workflow is to copy the comments from the Summary and then paste them into a form in the older reviewer tools, it doesn't seem like having the ability to add HTML formatting would help much. Perhaps down the road when we are able to have a tighter integration it will make sense, but for now I don't think it's worth adding support for that.

@wagnerand What do you think?

**Comment by wagnerand** [comment]
I agree with Bob. No need to add HTML support in the foreseeable future.
