### ISSUE TITLE
Bmps with myme type 'image/x-ms-bmp' are not rendered in the file viewer

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#718]
Follow up for #109

**STR**

1. Log in to the code manager with reviewer permissions
2. Try to view the following `.bmp` image file - https://code.addons-dev.allizom.org/en-US/browse/616837/versions/1688164/?path=Img%2Fmydearbonnie.bmp

**Actual result:**
The image is not displayed and an "Unrecognized image format" message is triggered

**Expected result:**
The image is displayed

**Notes:**
- reproduced on -dev with Fx66, Win10x64

**Comment by EnTeQuAk** [comment]
Double-checked mimetype, `image/x-ms-bmp` which should be fine but I suppose normalizing this to `image/bmp` would be better for the frontend to recognize the format?

**Comment by bobsilverberg** [comment]
> Double-checked mimetype, `image/x-ms-bmp` which should be fine but I suppose normalizing this to `image/bmp` would be better for the frontend to recognize the format?

I was going to simply add `image/x-ms-bmp` to the list of allowed mime types in the front-end, but sure, if you think it would be better to normalize all bmp files to a mime type of `image/bmp` then the front-end wouldn't have to change at all.

Is that how you think we should proceed, @EnTeQuAk?

**Comment by bobsilverberg** [comment]
Oh, I guess I should have checked https://github.com/mozilla/addons-server/pull/11384 first. It looks like the code for bmps is being handled there. Thanks @willdurand!

**Comment by willdurand** [comment]
This is fixed now. The API returns `image/bmp` for (hopefully) all BMP files.

**Comment by AlexandraMoga** [comment]
For all the BMP examples I had, the returned mymetype is `image/bmp` and they are being displayed by the file viewer:

https://code.addons-dev.allizom.org/en-US/browse/616837/versions/1688169/?path=Img%2Fbmp-mydearbonnie.bmp
![2019-05-13_16-18-35](https://user-images.githubusercontent.com/31961530/57625693-0bcfe500-759d-11e9-8769-58b025ffc618.gif)

Verified fixed on -dev with Fx66, Win10x64
