### ISSUE TITLE
Svgs with myme type 'image/svg' are not rendered in the file viewer

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#719]
Follow up for #109

**STR**

1. Log in to the code manager with reviewer permissions
2. Try to view the following `.svg` image file - https://code.addons-dev.allizom.org/en-US/browse/616837/versions/1688164/?path=Img%2Flisting-small.svg

**Actual result:**
The image is not displayed and an "Unrecognized image format" message is triggered

**Expected result:**
The image is displayed

**Notes:**
- reproduced on -dev with Fx66, Win10x64

**Comment by EnTeQuAk** [comment]
Here the returned mimetype from the backend is `image/svg` which should be fine, right?

**Comment by willdurand** [comment]
> Here the returned mimetype from the backend is `image/svg` which should be fine, right?

Is `image/svg` a valid mimetype? I cannot find any official docs mentioning that it's an official mimetype for SVGs. Only `image/svg+xml` seems valid, which would explain why it cannot be displayed correctly.

**Comment by EnTeQuAk** [comment]
you're right, https://www.w3.org/TR/SVG/mimereg.html - there's only `image/svg+xml` that's registered.

**Comment by willdurand** [comment]
Ok, then I'll file an issue in addons-server and assign myself :) I guess we want to update `MIMETYPE_COMPAT_MAPPING`.

**Comment by bobsilverberg** [comment]
> Ok, then I'll file an issue in addons-server and assign myself :) I guess we want to update `MIMETYPE_COMPAT_MAPPING`.

Yes, this is what we discussed in IRC yesterday. We should always use a mime type of `image/svg+xml` for any svg files. Thanks for taking care of this, @willdurand!

**Comment by willdurand** [comment]
This looks fixed now that the API returns a valid mimetype.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx66, Win10x64

SVGs have a `image/svg+xml`  mymetype now and they seem to be rendered in the file viewer now:

![2019-05-13_16-08-33](https://user-images.githubusercontent.com/31961530/57624055-c6f67f00-7599-11e9-81e9-4af5c02119ca.gif)

I've noticed some weird rendering with a couple of  SVGs that I've used, but I'm going to file a follow up for that once I cover more examples and have more conclusive results.
