### ISSUE TITLE
Allow for DiffView to automatically select the first/last diff in a file

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#722]
This supports #615 

When a user tries to navigate to the next/previous diff and they are already on the last/first diff for the current file, we need to load the next/previous file with a diff, and jump to the first/last diff in that file.

This issue is about enabling that to happen. I.e., adding the ability to specify a URL param which will indicate that the diff being loaded should have the first/last difference in the file selected.

For QA:

The new URL parameters can be tested by loading a file that contains multiple changes in the compare view. Then add `?scrollTo=firstDiff` to the URL, and the page should reload with the first line of the first change scrolled to the top of the window, and selected. Next, change the URL parameter to `?scrollTo=lastDiff`, and the page should reload with the first line of the last change scrolled to the top of the window, and selected.

**Comment by willdurand** [comment]
@bobsilverberg is there any instruction for QA?

**Comment by bobsilverberg** [comment]
> @bobsilverberg is there any instruction for QA?

Thanks for the reminder @willdurand. I have added QA instructions to the description.

**Comment by AlexandraMoga** [comment]
Verified on -dev with Fx66, Win10x64 based on the QA instruction provided.

After trying with various files, I concluded that this new feature is working

Here is an example
https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1541685...1688187/?path=src%2Fcss%2Fpopup.css

![2019-05-21_17-59-44](https://user-images.githubusercontent.com/31961530/58107881-7a432180-7bf3-11e9-83b3-ec02700895c1.gif)
