### ISSUE TITLE
Folders scroll out of view when opening them

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#724]
### Describe the problem and steps to reproduce it:

- Sign in
- Load this extension file: https://code.addons-dev.allizom.org/en-US/browse/8542/versions/1655535/?path=menu.js
- Scroll upwards and click the `_locales` folder to open it

### What happened?

The `_locales` folder opens but all you see is `menu.js`, the selected file.

### What did you expect to happen?

You should see the contents of the `_locales` folder

### Anything else we should know?

This is a regression of https://github.com/mozilla/addons-code-manager/issues/680

**Comment by kumar303** [comment]
This is pretty bad. If anyone wants to take this issue while I'm on PTO, please do 😅

**Comment by AlexandraMoga** [comment]
This does look like a duplicate of https://github.com/mozilla/addons-code-manager/issues/699

**Comment by kumar303** [comment]
Whoops, thanks. Yes it is.
