### ISSUE TITLE
Change API and reducer code to support no array of diffs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#726]
Depends on #738 
Depends on https://github.com/mozilla/addons-server/pull/11402

This issue is now just about making the changes to support the fact that the API will return a single diff object and not an array of diffs.

For QA:

Please check for regressions in the Compare feature. Also note that in order for this to work on dev, both this change and the change from https://github.com/mozilla/addons-server/pull/11402 need to have landed. I will take care of landing them at the same time.

**Comment by willdurand** [comment]
The addons-server patch is ready: https://github.com/mozilla/addons-server/pull/11402. It has been r+ed so you can merge it whenever you want.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx66, Win10x64

I haven't spotted any regressions in the Compare view.
