### ISSUE TITLE
Move `ContentShell` component to its own file

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#730]
Supports #588

---

This is needed because we'll likely connect this component as well as the `FullscreenGrid` component. There will be too much code into this `FullscreenGrid.tsx` file, so let's split it.

**For QA:** there should be no visual regression, i.e. pages should show 3 panels (left panel usually has the accordion menu, center panel has code, right panel has a code overview).

**Comment by AlexandraMoga** [comment]
No visual regressions noticed in the browse or compare pages

![image](https://user-images.githubusercontent.com/31961530/57710583-e82c9d80-7675-11e9-8ac3-2362de792834.png)

Verified fixed on -dev with Fx66, Win10x64
