### ISSUE TITLE
Toggle the main side panel

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#736]
Supports #588

---

In order to ship #588, which is about hiding the main side panel using a keyboard shortcut, we need to be able to toggle the main side panel (i.e. opening/closing it). Let's do this here.

**For QA:** a new button will be added to the left panel (a.k.a. main side panel) and it will also users to open/close this panel.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx67, Win10x64

The side panel can be collapsed/expanded both in the browse and the compare pages:

![2019-05-24_17-07-16](https://user-images.githubusercontent.com/31961530/58333615-7ce98500-7e46-11e9-88c9-c5403615e07c.gif)
