### ISSUE TITLE
Unify main side panel button style

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#737]
Once https://github.com/mozilla/addons-code-manager/issues/736 lands, we'll have similar buttons (derived from Bootstrap) in two locations. It'd be nice to extract the style of these buttons. It could be done by creating a `Button` component, maybe.

**For QA:** there should be no visual regression related to the buttons in the left panel (accordion menu and collapse/expand buttons).

**Comment by kumar303** [comment]
> Once #736 lands, we'll have similar buttons (derived from Bootstrap) in two locations. 

Which two locations?

**Comment by willdurand** [comment]
> Which two locations?

- https://github.com/mozilla/addons-code-manager/blob/8fc513313df7e89f3affa1230f39334e060e1c59/src/components/AccordionMenu/styles.module.scss
- https://github.com/mozilla/addons-code-manager/blob/8fc513313df7e89f3affa1230f39334e060e1c59/src/components/ToggleButton/styles.module.scss

**Comment by ioanarusiczki** [comment]
@willdurand No visual or functional regressions found - FF67(win10). 

The only 2 changes I see  on -dev are at Keyboard Shortcuts:
-  the greyed out shortcuts were switched, `p` was first (as seen on stage). Now `n` is the first (on dev)
- `h` was added for Toggle main side panel. Is there a keyboard shortcut for the alt side panel too?

**Comment by willdurand** [comment]
> `h` was added for Toggle main side panel. Is there a keyboard shortcut for the alt side panel too?

nope, not yet

**Comment by willdurand** [comment]
> the greyed out shortcuts were switched, `p` was first (as seen on stage). Now `n` is the first (on dev)

that's alright, thanks!
