### ISSUE TITLE
Change the versions reducer to work with a single diff per file rather than an array

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#738]
This supports #726 and will allow us to land a change immediately, rather than having to wait for the API to change. This involves changing createInternalDiff to just take the first diff in the array and then changing all of the other reducer code to work with a single diff.

For QA:

Please check for regressions in the Compare view.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx66, Win10x64

I haven't spotted any regressions in the Compare view.
