### ISSUE TITLE
Toggle the alt side panel

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#742]
Supports #588

---

In #588, we talked about a "focus" mode that would hide the side panels so that reviewers can focus on the source code. Depending on how we implement #588, we might want to hide both side panels instead of only the left side panel. In any case, we can still provide a button to collapse/expand the right panel (or "alt side panel").

**For QA:** a new button will be added to the right panel (a.k.a. alt side panel) and it will also users to open/close this panel.

**Comment by ioanarusiczki** [comment]
@willdurand I checked this on dev and stage servers with FF67- Win10
The panel collapses using the button and can be closed reopened with the Enter Key. 
I filed followups for what I've noticed 
https://github.com/mozilla/addons-code-manager/issues/841
https://github.com/mozilla/addons-code-manager/issues/842
