### ISSUE TITLE
Add a lint rule to disallow .ts files, enforce .tsx

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#75]
We want to always create `.tsx` files, not `.ts` files. This reduces the mental burden of trying to figure out which file to create. This lint rule is important because our lint command in https://github.com/mozilla/addons-code-manager/pull/74 will *ignore* `.ts` files.

**Comment by willdurand** [comment]
Could be done with https://www.npmjs.com/package/eslint-plugin-filenames
