### ISSUE TITLE
Move compare dropdowns into header bar

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-code-manager#757]
Another suggestion (in addition to https://github.com/mozilla/addons-code-manager/issues/758): We could move the compare dropdown into the header bar, to save some space and have the code panel be always at the same position, regardless of browse or compare mode.

**Comment by ioanarusiczki** [comment]
@kumar303 
- There's a blue `Compare Versions` button available in the navbar for both browse and compare pages. 
- when there's only one version of the add-on submitted the button is already available in the Browse page. I don't see it as an issue but I can't tell if it is what you expected too. 

![one version](https://user-images.githubusercontent.com/33448286/70127985-c849df00-1684-11ea-968c-1974db0a2cc4.gif)

- using the mouse cursor and clicking the content of the `Compare Versions` drop down menu I could navigate to browse pages or other comparison pages. 
- I filed an issue for the keyboard navigation here https://github.com/mozilla/addons-code-manager/issues/1304

**Comment by kumar303** [comment]
>     * when there's only one version of the add-on submitted the button is already available in the Browse page. I don't see it as an issue but I can't tell if it is what you expected too.

Yeah, that's expected. I suppose the UX could communicate that a comparison isn't possible somehow but it's not a big deal.
