### ISSUE TITLE
Opened and closed folder icons have different size

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-code-manager#759]
Nit:

The size of the icon for _closed folder_ is 16x12,
the size of the icon for _opened folder_ is 18x12.

This makes the label jump left or right a little when a folder is opened or closed.

**Comment by AlexandraMoga** [comment]
The _opened_ and _closed_ folder icons don't have the exact same size, but there's no jumping left or right visible anymore:

![2019-08-14_16-09-35](https://user-images.githubusercontent.com/31961530/63023707-4b64e080-beae-11e9-9900-873869f81a59.gif)
