### ISSUE TITLE
Sentry does not seem to be enabled in prod

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#760]
We don't receive errors in Sentry. Based on an IRC discussion with @wagnerand and @kumar303, we should have received errors in prod.

We need to investigate to make sure everything is correctly configured.

**Comment by willdurand** [comment]
Environment variables (in all the hosted envs) are correctly configured with the right DSNs.

**Comment by kumar303** [comment]
For STR (this requires reviewer permissions in prod) https://github.com/mozilla/addons-code-manager/issues/761

**Comment by kumar303** [comment]
> Environment variables (in all the hosted envs) are correctly configured with the right DSNs.

I also confirmed with Adrian that the prod DSN is exactly correct (the secret, too).

As far as I can tell, Raven does not post the error. I don't see any relevant CSP errors. I see raven.js in stack traces so it appears to be installed.

**Comment by kumar303** [comment]
I think https://github.com/mozilla/addons-code-manager/issues/784 will fix this. I'm going to do some tests to see.

**Comment by kumar303** [comment]
Errors are going to prod Sentry now 💃  https://sentry.prod.mozaws.net/operations/addons-code-manager-prod/

**Comment by AlexandraMoga** [comment]
Since verifying this would require reviewer permissions in prod, I don't think QA can help here.
Could you please add a "qa:not needed" label?
Thanks

**Comment by willdurand** [comment]
@AlexandraMoga added the "qa: not needed" label :)
