### ISSUE TITLE
Make layout a bit more compact

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-code-manager#771]
This may be a matter of personal preference, but I've reduced the page size to about 80% so it is somewhat similarly sized to the old file viewer. I think we should consider adjusting the styling so it is a bit more compact and you can see more code on one screen.

**Comment by kumar303** [comment]
> I've reduced the page size to about 80%

@kewisch what do you mean by this? Could you provide the dimensions of your window, roughly?

In the next release, the side panel can be collapsed which might help. Demo: https://github.com/mozilla/addons-code-manager/pull/735

**Comment by kewisch** [comment]
I've used the page zoom features of Firefox to zoom out to 80%. I'm basically saying I feel the whole UI is a bit too big and we could save space by making fonts and such smaller.

I'm running a Macbook Pro with 2880 x 1800 Retina.

**Comment by kumar303** [comment]
Oh, I totally see what you mean now. Yeah, the font size was bigger than how I have my own code editor set up.

I made some adjustments in https://github.com/mozilla/addons-code-manager/pull/810 ; can you check the screenshots? @wagnerand maybe you'd also like to weigh in on these screenshots?

**Comment by kewisch** [comment]
This already looks better, thanks! I'm thinking next it would be good to reduce margins and padding a bit, for example on `.alert` it would be enough to have let's say `padding: .5rem .75rem`. Buttons also could be a bit more dense. What do you think?

**Comment by kumar303** [comment]
Sure, we could tighten it up more. Can you file a separate issue?

**Comment by kumar303** [comment]
@kewisch actually, I ended up making the buttons more compact as part of this change, too. It should be landing on https://code.addons-dev.allizom.org/ shortly.

**Comment by ioanarusiczki** [comment]
@kumar303 I verified this issue on code.addons-dev.allizom.org (on FF67 -Win10) 
The font size is smaller, also the buttons look more compact as shown in https://github.com/mozilla/addons-code-manager/pull/810

Am example 

<details>
<summary>Before - AMO stage </summary>


![AMO stage](https://user-images.githubusercontent.com/33448286/59272967-d7188180-8c5f-11e9-8ed1-bf73752637ee.png)

</details>

<details>
<summary>After - AMO dev </summary>

![AMO dev](https://user-images.githubusercontent.com/33448286/59272990-e4357080-8c5f-11e9-83b4-a3272b42c065.png)

</details>
