### ISSUE TITLE
Using keyboard shortcuts to switch files resets the scroll position in the file tree

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons-code-manager#772]
### Describe the problem and steps to reproduce it:

* Go to any file tree with a lot of files
* Go down to one of the lower files
* Press `j` to go down one file

### What happened?
* Scroll is reset to the top of the file tree

### What did you expect to happen?
* Scroll is set to have the selected file visible in the tree

**Comment by kumar303** [comment]
@kewisch Thanks for filing. Could you link to an example? I wonder if this is what we fixed in https://github.com/mozilla/addons-code-manager/issues/699

**Comment by kewisch** [comment]
Oh actually it is likely related to #770: When I pressed j and the find bar appeared, it highlights the j from "message.json" at the top, as expected. Thanks for checking in!

**Comment by kumar303** [comment]
Duplicate of #770
