### ISSUE TITLE
The file tree is not refreshed when another old version is selected in the compare view

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#776]
**STR**

1. Go to the compare versions page for an add-on - see https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1541685...1688187/
2. Select a file to inspect - for example https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1541685...1688187/?path=src%2Fjs%2FGrammarly.js
3. After the file is loaded, choose the next OLD version from the drop down list (version 8.842.2007)
4. Observe the file tree during the loading diff process

**Actual result:**
When another old version is selected, the file tree is not refreshed. This could create confusion, because file statuses (i.e. added, modified, unmodified) will not be updated. 

**Expected result:**
The file tree is refreshed when another old version is selected in the compare view

**Notes:**
- in this particular example, when old version 8.842.2007 is selected, the file in `?path=src%2Fjs%2FGrammarly.js` will still appear as modified when in fact there are no differences to display
- the file tree is refreshed when a New version is selected for comparison 
- reproduced on -dev with Fx66, Win10x64

![2019-05-21_17-38-43](https://user-images.githubusercontent.com/31961530/58105780-b70d1980-7bef-11e9-9a87-72318e4d611b.gif)

**Comment by kumar303** [comment]
Thanks for the report. I added the security label because showing an incorrect file status could trick reviewers.

**Comment by kumar303** [comment]
This is a regression caused by this [if statement](
https://github.com/mozilla/addons-code-manager/pull/627/files#diff-849d3d7e822fc2a7e48991bf6abc02a2R690), which prevents the version data from loading.

We had https://github.com/mozilla/addons-code-manager/issues/671 on file to fix it but we were not aware of any concrete bugs (just theoretical bugs!).

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx67, Win10x64

The file tree is now refreshed when a different old version is selected from the dropdown

In the below screencast, I'm repeating the STR to demonstrate that the issue is fixed:

![2019-06-10_13-30-44](https://user-images.githubusercontent.com/31961530/59190088-7f591800-8b84-11e9-8e97-a1264f27ce1d.gif)
