### ISSUE TITLE
File paths are not preserved in the URL when selecting a different old version in the compare view

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#777]
**STR**

1. Go to the compare versions page for an add-on - see https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1688183...1688187/
2. Select a file to inspect - for example https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1688183...1688187/?path=src%2Fcss%2Fmodal.js
3. After the file is loaded, choose another OLD version from the drop down list
4. Notice the file returned by the file viewer

**Actual result:**
The file viewer returns the `manifest.json` details when selecting a different old version  in the compare view - file path not preserved

**Expected**
If a file path was specified before another old version was selected, the file viewer should return the same file details

**Notes:**
- while this issue exists, reviewers will have to re-navigate the file tree in order to find the file they were trying to compare against previous versions
- another issue here is that the file tree is not refreshed when selecting an older version, but for this I filed #776 
- reproduced on -dev and stage with Fx66, Win10x64

![2019-05-21_16-47-34](https://user-images.githubusercontent.com/31961530/58102533-17995800-7bea-11e9-8c2c-23fbccb62c13.gif)

**Comment by kumar303** [comment]
Thanks for the report. This is pretty simple to fix but it is more complicated when the file you are viewing doesn't exist in the next version.

But, more importantly, I am not sure that this is something reviewers would ever want to do.

@wagnerand would it be helpful for the version compare view to try and preserve the current file when switching between versions? I.E. is switching versions something you'd do a lot?

**Comment by wagnerand** [comment]
I think this would be quite helpful, yes. Especially so, until we have a `git blame` like feature. If the file does not exist in the older version, we could just fallback to manifest.json.

**Comment by kumar303** [comment]
This was fixed by @mirefly 🎉 but I'm not sure what to do about deleted files, such as the ones in `src/icon` of https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1688183...1688187/ I think we should open a new issue for that.

**Comment by ioanarusiczki** [comment]
@kumar303 I could not reproduce this scenario on AMO dev or stage with FF69(Win10) - selecting an older version will keep the path and show the same file. 
I did see an issue when I select the `new version` so I filed it here https://github.com/mozilla/addons-code-manager/issues/1094
