### ISSUE TITLE
Unable to load large files in the compare view - the browser freezes 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#779]
**STR:**

1. Try to load the following compare page - https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1541685...1688187/?path=src%2Fjs%2Feditor-popup.js

**Actual result:**
The file appears to be loading, but the browser freezes after several seconds

**Expected result:**
The file is loaded in the file viewer

**Notes:**
- the file can be opened in the browse page; it does take a bit longer to load, but it is opened eventually
- I used to see the same issue in the browse page a while ago - see my comment in https://github.com/mozilla/addons-code-manager/issues/591#issuecomment-484121734
- Link to the add-on review page: https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/grammarly-for-dev
- reproduced on -dev with Fx67, Win10x64

![image](https://user-images.githubusercontent.com/31961530/58154140-8ec9fd00-7c79-11e9-9828-c6a95a3502dd.png)

**Comment by kumar303** [comment]
We have a workaround in https://github.com/mozilla/addons-code-manager/issues/942 which should speed this up but, really, we can do syntax highlighting faster once https://github.com/mozilla/addons-code-manager/issues/928 lands so I'm going to keep this open as a way to test it.

**Comment by kumar303** [comment]
This was fixed in https://github.com/mozilla/addons-code-manager/issues/946
