### ISSUE TITLE
Send all console.error messages to Sentry

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#784]
Aside from Sentry not working right now (see https://github.com/mozilla/addons-code-manager/issues/760), we also want to send all `console.error()` (and `log.error()`) messages to Sentry. Currently, Sentry is only configured to send thrown errors.

I looked at `addons-frontend` and it appears that it was never configured to send console messages to Sentry. Huh. In fact, the documentation on how to do this is terrible. I finally found a [CaptureConsole](https://docs.sentry.io/platforms/javascript/?platform=browsernpm#captureconsole) plugin but the installation is not documented correctly.

**Comment by willdurand** [comment]
> I looked at `addons-frontend` and it appears that it was never configured to send console messages to Sentry. Huh. In fact, the documentation on how to do this is terrible. I finally found a [CaptureConsole](https://docs.sentry.io/platforms/javascript/?platform=browsernpm#captureconsole) plugin but the installation is not documented correctly.

Not sure I understand how it works in addons-frontend then.

**Comment by kumar303** [comment]
> Not sure I understand how it works in addons-frontend then.

Does it? It no longer works from here: https://docs.sentry.io/platforms/javascript/?platform=browsernpm#captureconsole Maybe it regressed? I could have sworn it was working at some point but maybe it was never working?
