### ISSUE TITLE
Need some permission to reach api host? 

### ISSUE THREAD

**Issue by mirefly** [mozilla/addons-code-manager#788]
### Describe the problem and steps to reproduce it:
- `yarn dev` to start local development servers
- open http://localhost:3000, log in
- click `a browse page` link (to `http://localhost:3000/en-US/browse/494431/versions/1532144/`).

### What happened?
![image](https://user-images.githubusercontent.com/4984681/58387036-d7f5b600-7fc5-11e9-97f5-2851cb8299ae.png)

### Anything else we should know?
![image](https://user-images.githubusercontent.com/4984681/58387058-4cc8f000-7fc6-11e9-8569-53b14469c46b.png)
os: debian 9
browser: firefox

**Comment by willdurand** [comment]
Hey @mirefly, indeed this project requires special permissions when calling the API. You won't be able to consume the -dev, stage or prod APIs.

That being said, you should be able to install [addons-server](https://github.com/mozilla/addons-server) locally and make it work with this project. It is not documented yet, but if you want to try that, I can probably help you.

**Comment by mirefly** [comment]
Thanks @willdurand 
I tried the following steps, but no success..
- Install addons-server with Docker (https://addons-server.readthedocs.io/en/latest/topics/install/docker.html). `docker-compose ps` shows that all servers are up.
- Add `127.0.0.1 olympia.test` to `/etc/hosts`
- Run `yarn olympia` in addons-code-manager
- Visited localhost:5000 and log in, then I got
![image](https://user-images.githubusercontent.com/4984681/58438497-6a608d00-808c-11e9-90dc-be11bcb42bc3.png)
Is it due to the empty database in the local?

**Comment by kumar303** [comment]
Hi @mirefly, yes, this might be due to an empty database. You'd have to submit an add-on locally and set up a separate reviewer account. 

It would be easier on the hosted dev site. If you register an account on https://addons-dev.allizom.org/ (note the domain) then let me know the email address and I can grant you access to the code manager. Mention my name in this issue so I don't miss your response.

**Comment by mirefly** [comment]
Great. Thanks @kumar303 
My email address is mirefly@gmail.com on addons-dev.allizom.org

**Comment by kumar303** [comment]
@mirefly you should be all set to log into https://code.addons-dev.allizom.org/ . You can find add-ons to review at this link: https://reviewers.addons-dev.allizom.org/en-US/reviewers/queue/auto_approved Pick an add-on and scroll all the way down until you see *Add-on History*. That section will contain links to *Code Manager*. 

The repo isn't set up with 'good first bugs' yet but if you see something that isn't already assigned then mention my username and I can give you info about it. Thanks for your interest!

**Comment by kumar303** [comment]
@mirefly here's a good first bug: https://github.com/mozilla/addons-code-manager/issues/774 I'll see if I can find some more.
