### ISSUE TITLE
Hide top-level folder

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-code-manager#789]
Suggestion: Hide the top-level folder. Collapsing it does not provide much value, since then you don't see any actual add-on files anymore. Also, that folder is actually not part of the add-on, so it could be a little confusing?

**Comment by mirefly** [comment]
Is it expected to work like this?
![1](https://user-images.githubusercontent.com/4984681/59325579-dbb15a00-8ca0-11e9-9c5f-1e0aae5340f2.gif)

**Comment by wagnerand** [comment]
Yes, that looks good to me!

**Comment by kumar303** [comment]
Thanks again, @mirefly. This makes the file tree much more concise.

I will note that https://github.com/mozilla/addons-code-manager/issues/756 is more important now because there is no longer a way to know what add-on you are browsing besides looking at the page title.

**Comment by ioanarusiczki** [comment]
@kumar303 Verified on AMO dev - FF67 -Win10
The top folder is no longer displayed for both: versions and compare versions pages.

![no top folder](https://user-images.githubusercontent.com/33448286/60104948-1c15db00-976b-11e9-86a4-a11926ffdf92.gif)
