### ISSUE TITLE
Syntax highlight all JSON files

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-code-manager#790]
### Describe the problem and steps to reproduce it:

I was reviewing an add-on that contains a JSON file (not manifest.json)

### What happened?

That file was not syntax highlighted.

### What did you expect to happen?

Syntax highlighting for all JSON files.

### Anything else we should know?

https://code.addons.mozilla.org/en-US/browse/1482277/versions/3189741/?path=data%2Fconfig.json

**Comment by kumar303** [comment]
Seems like an API issue https://github.com/mozilla/addons-server/issues/11534

**Comment by kumar303** [comment]
This looks like it has been fixed in https://github.com/mozilla/addons-server/issues/11534

**Comment by EnTeQuAk** [comment]
Indeed, until there's another bug in libmagic :see_no_evil: keep your eyes open though!

**Comment by ioanarusiczki** [comment]
@kumar303 If I go to https://code.addons-dev.allizom.org/en-US/browse/616914/versions/1688318/
It automatically lands on manifest.json 
I click the config.json but I don't see anything highlighted. 
The `mimetyp` of config.json file is correct though as I mentioned in https://github.com/mozilla/addons-server/issues/11534



![config json file](https://user-images.githubusercontent.com/33448286/60339657-06debd80-99b2-11e9-8d6c-10e77fb7e2d6.gif)

**Comment by EnTeQuAk** [comment]
The highlighting looks good to me, pretty identical to manifest.json.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk Ok, I understood now. It's the blue versus green for the values inside the file. 
Verified on -dev FF67(Win10)
