### ISSUE TITLE
Setup Jest as testing framework

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#8]
We want to use [Jest](https://jestjs.io/) for writing/running tests.

See: https://jestjs.io/docs/en/tutorial-react#setup-with-create-react-app

**Comment by willdurand** [comment]
Also useful: https://github.com/kulshekhar/ts-jest

**Comment by kumar303** [comment]
Ideally we want the test suite to also show us lint and typing errors, like in addons-frontend.

**Comment by willdurand** [comment]
Jest is already bundled with CRA.

**Comment by willdurand** [comment]
About CRA, jest and tests: CRA (and FB) promotes the "tests files near source files" approach, which means we'll have to put our test files in `src/`. There are various strategies to organize files, one that I like being this structure:

```
src/
  reducers/
    users/
      index.ts
      index.test.ts
  components/
    Foo/
      index.tsx
      index.test.tsx
      styles.module.scss
```

One folder per unit and everything inside. That's what we are doing for React components in addons-frontend (except that we don't have the test files here), so that would be that + adding test files + generalizing to all source "units".
