### ISSUE TITLE
Display linter messages that apply to the entire add-on

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#805]
### Describe the problem and steps to reproduce it:

Load https://code.addons-dev.allizom.org/en-US/browse/616915/versions/1688319/?path=background.js which produces the message *Validation generated too many errors/warnings so 2 messages were truncated*

### What happened?

The page does not display the *too many errors* message. 

At the time of filing this issue, an error could be seen in the console. Here is a similar production error:

Unexpectedly received a message not mapped to a file: Validation generated too many errors/warnings so 163 messages were truncated. After addressing the visible messages, you'll be able to see the others.

https://sentry.prod.mozaws.net/operations/addons-code-manager-prod/issues/5884330/?query=is:unresolved

### What did you expect to happen?

The page should display the *too many errors* message.

### Anything else we should know?

Example:

```js
"messages": [
      {
        "tier": 1,
        "type": "warning",
        "id": [
          "validation",
          "messages",
          "truncated"
        ],
        "message": "Validation generated too many errors/warnings so 163 messages were truncated. After addressing the visible messages, you&#39;ll be able to see the others.",
        "description": [],
        "compatibility_type": null
      }
]
```

Complete response: [validation-gen-too-many-warnings.json.zip](https://github.com/mozilla/addons-code-manager/files/3248130/validation-gen-too-many-warnings.json.zip)

**Comment by kumar303** [comment]
I added the security label because the UI fails to show a validation error which is bad

**Comment by kumar303** [comment]
How common is it to see top-level, general linter messages? @EnTeQuAk gave me some detailed info to suggest that it won't be very common.

Relevant code: https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/file_validation_annotations.py

Top-level messages are primarily related to:

* Legacy add-ons restrictions (these are in 99.9% errors, so won't end up in the code-manager)
* WebExt incompatibilities (As those are upgrades from legacy-addons they won't appear in recent add-ons either)
* Akismet related errors: https://github.com/mozilla/addons-server/blob/master/src/olympia/devhub/file_validation_annotations.py#L107
  * Same, they're errors and won't end up in the code-manager
* Search plugin validation - same, all errors, none will end up in code-manager

In `devhub.tasks` are three more validation errors, one for "api key in XPI detected", another for "unsupported file type" (e.g if the uploaded file isn't a XPI, ZIP etc) and
"Invalid or corrupt add-on file.".

For addons-linter…

The only messages that are "global" are also errors which won't end up in the code-manager. We do have all or most "message adding" going through an interface that verifies `file` to be set 
so this is tested and as a general rule, "global" messages should primarily be errors as warnings will end up being seen by the user and should have the context
of a specific file. If that's not the case, then it's a bug (or a very good reason).

That being said, from a pure technical stand point, it'll always be possible to throw warnings for the whole package. Both, the linter and addons-server
avoid that as much as possible though, so that the only "global" messages are errors and these will block submission.

**Comment by willdurand** [comment]
> so that the only "global" messages are errors and these will block submission.

admins can by-pass that though, and admins might be reviewers as well.

**Comment by EnTeQuAk** [comment]
> admins can by-pass that though, and admins might be reviewers as well.

True, that still makes it very very rare I think. I didn't think about admin-overwrites though, that's right.

**Comment by ioanarusiczki** [comment]
@kumar303 The message with too many errors is displayed on the page. 

![message loaded](https://user-images.githubusercontent.com/33448286/60601292-8dccd500-9dba-11e9-9720-f652f21de752.png)

There's a warning in the Console though

`No tree was loaded for version 1688319`
