### ISSUE TITLE
Show meaningful web page titles

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#809]
### Describe the problem and steps to reproduce it:

Go to any browse or compare page

### What happened?

The web browser page title is the same for both

### What did you expect to happen?

The titles should be different so that one can work in multiple tabs more easily. The titles should include the add-on name, for example, to make it easier to distinguish tabs.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx67, Win10x64

The browse and the compare pages have a corresponding web page title:

![image](https://user-images.githubusercontent.com/31961530/58964145-17d34f00-87b7-11e9-8095-d222353b49b5.png)

I've also filed #813  with a suggestion for the Browse page title,
