### ISSUE TITLE
The Browse web page title contains an '@' before the add-on version string

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#813]
Follow up for #809 

**STR:**
1. Open the  browse page for an add-on - see https://code.addons-dev.allizom.org/en-US/browse/385621/versions/1655456/
2. Observe the page title

**Actual result:**
The page title is `Browse DuckDuckGo Plus@2019.1.31`

**Expected result:**
The page title should more likely be `Browse DuckDuckGo Plus:2019.1.31`

**Notes:**
- another suggestion would be to use the version ID instead of the version string
- repoduced on -dev with Fx67, Win10x64

![image](https://user-images.githubusercontent.com/31961530/58963824-849a1980-87b6-11e9-92e6-e2bcdd50d4bb.png)

**Comment by kumar303** [comment]
I used the at sign on purpose to convey *this add-on at this version*. Maybe I'll add a space, though, to make it look more like `Browse DuckDuckGo Plus @ 2019.1.31`

**Comment by kumar303** [comment]
It seems that switching the browse title to a colon is a popular request so I'll go with that 😅

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev
![image](https://user-images.githubusercontent.com/31961530/59110719-5ea47e80-8948-11e9-959d-97188e3740ad.png)

![image](https://user-images.githubusercontent.com/31961530/59110734-6401c900-8948-11e9-8fa9-e403c984a2e0.png)
