### ISSUE TITLE
the toggleExpandedPaths action deletes old version data

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#819]
**For QA**: please check for regressions in expanding / collapsing paths in the file tree.

There is a bug in the [spread](https://redux.js.org/recipes/using-object-spread-operator) used to recreate Redux state when the `toggleExpandedPaths` action is dispatched:

https://github.com/mozilla/addons-code-manager/blob/76b4da69eac7b4072830b497a84a90a3088cc459/src/reducers/versions.tsx#L1148

This should be:

```js
...state.versionInfo
```

...to preserve historic versions.

This spread deletes old versions but I can't think of any actual bug this causes in the app. I discovered it when I was trying to inspect versions state so, if anything, it's confusing for debugging purposes.

**Comment by AlexandraMoga** [comment]
I've checked the browse and the compare page but I haven't run into any issues with collapsing or expanding  paths in th file tree.

I'm marking the issue as verified fixed on -dev with Fx67, Win10x64
