### ISSUE TITLE
Deal with version comparisons in a more robust way

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#820]
**For QA**: please check for regressions in *TBD*

PR https://github.com/mozilla/addons-code-manager/pull/817 enhanced [Version](https://github.com/mozilla/addons-code-manager/blob/d821eeb670e7a24b321654684a4f40fe802ff67a/src/reducers/versions.tsx#L187) with a new property, `comparedToVersionId`. This indicates that the version object contains extra data because it was compared to another version. 

For example, if you retrieve version 2 and it includes the file `manifest.json`, the entry status will be empty. If you retrieve version 2 [compared to](https://addons-server.readthedocs.io/en/latest/topics/api/reviewers.html#compare) version 1, `manifest.json` might have an entry status of *added* or *modified*, depending on the comparison.

Let's model this data in a better way.

Perhaps we need to split [VersionEntry](https://github.com/mozilla/addons-code-manager/blob/d821eeb670e7a24b321654684a4f40fe802ff67a/src/reducers/versions.tsx#L169) into its own state key, like `versionEntries`. That is, instead of putting them directly on the `version` object as [`version.entries`](https://github.com/mozilla/addons-code-manager/blob/d821eeb670e7a24b321654684a4f40fe802ff67a/src/reducers/versions.tsx#L189).

**Comment by ioanarusiczki** [comment]
@kumar303 I did not find issues (except for https://github.com/mozilla/addons-code-manager/issues/1094) - verified on dev and stage - FF69(Win10).
