### ISSUE TITLE
Give the "selected" linter message a style

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#826]
#824 introduces navigating between linter messages, and when there are multiple global messages, or multiple messages for a given line, only the line of code is selected/scrolled into view, but we still "navigate" between each message. This can be confusing as it seems like nothing is happening when multiple messages for the same line are navigated.

We should change the styling of the current "selected" message so it becomes apparent that we are moving from message to message.

Additional note:
If there are enough messages that they do not all appear on a single screen, then this could still be an issue because the user wouldn't see that the style is changing for any messages currently off the screen. We could address that by changing our strategy and not scrolling the code line into view, but rather scrolling the actual message into view, but I think we decided against that awhile back. I believe we are considering collapsing multiple messages for a line, and if so maybe we can look at how this can best work with that at that time. That's not to say we shouldn't implement the styling for "selected" messages now.

**Comment by bobsilverberg** [comment]
FYI, I have already started working on this, and it seems to be working well. It does introduce quite a bit of duplication between `CodeView` and `DiffView`, but I wonder if we can just continue down that path for now and have a separate issue to try to resolve some of this duplication later.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
When navigating between linter messages using the keyboard shortcuts the message looks as being selected (a border is added). 

![adding style with shortcuts nav](https://user-images.githubusercontent.com/33448286/60507741-7e259180-9cd1-11e9-870b-bedf702044cc.gif)

- should this be applied when a message is selected using the page's overview (clicking the orange line which indicates the presence of a linter message) ? I believe it's not applicable for this scenario but I'm not 100% sure.

**Comment by bobsilverberg** [comment]
> * should this be applied when a message is selected using the page's overview (clicking the orange line which indicates the presence of a linter message) ? I believe it's not applicable for this scenario but I'm not 100% sure.

You are correct that it's not applicable, but it might be something we'd consider doing, so if you want to open up an issue to request that as an enhancement we could consider it. It might not make sense though, as often the lines in the code overview correspond to more than one line in the actual code, and therefore could correspond to multiple messages, and therefore it might not make sense to show one specific message as being selected.
