### ISSUE TITLE
White, transparent PNG images are invisible

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#829]
### Describe the problem and steps to reproduce it:

View a white, transparent PNG image, such as http://localhost:3000/en-US/browse/8542/versions/1655535/?path=images%2Fnewlogo%2FLastPass_White.png

### What happened?

You cannot see the image

### What did you expect to happen?

There should be a checkered background so that the image is visible. I think it'd be fine to include this background for all images, not just transparent ones.

### Anything else we should know?

I see some simple solutions here: https://stackoverflow.com/questions/27277641/create-a-checkered-background-using-css

**Comment by willdurand** [comment]
I currently see part of the image because of https://bugzilla.mozilla.org/show_bug.cgi?id=1557156 :(

**Comment by rbrishabh** [comment]
Hey! Can I take this up?

**Comment by kumar303** [comment]
Hi @rbrishabh, sorry, I missed your comment. This is still available to work on. Thanks for your interest! I changed the label to `contrib: welcome` since it may not be such a simple task now that I think about it.

**Comment by rbrishabh** [comment]
Well, I'd still like to tackle and hopefully solve this! @kumar303

**Comment by kumar303** [comment]
Awesome. Thanks. You'll need to begin by going to https://addons-dev.allizom.org/en-US/firefox/ and registering for an account. Next, send me the exact email you used to kmcmillan@mozilla.com and I will grant you a reviewer account, which you'll need for local development.

**Comment by rbrishabh** [comment]
> Awesome. Thanks. You'll need to begin by going to https://addons-dev.allizom.org/en-US/firefox/ and registering for an account. Next, send me the exact email you used to [kmcmillan@mozilla.com](mailto:kmcmillan@mozilla.com) and I will grant you a reviewer account, which you'll need for local development.

Done! @kumar303 ! Do let me know when you grant one.
