### ISSUE TITLE
Fix `CodeOverview` so that it adjusts itself when its container is expanded

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#830]
### Describe the problem and steps to reproduce it:

- Sign in and load the home page http://localhost:3000
- Collapse the alt side panel
- Click 'a browse page'
- Expand the alt side panel

### What happened?

No code overview...

![](https://user-images.githubusercontent.com/55398/58259122-889b5580-7d39-11e9-8e03-68ba1b475125.png)

### What did you expect to happen?

A code overview!

### Anything else we should know?

See this thread: https://github.com/mozilla/addons-code-manager/pull/743#discussion_r286958562

**Comment by ioanarusiczki** [comment]
@willdurand Not reproducible on dev - FF67(Win10)

![works on dev](https://user-images.githubusercontent.com/33448286/59510610-cd3f8a00-8ebc-11e9-8672-c6692937656d.gif)
