### ISSUE TITLE
When navigating between linter messages in the Compare view, skip files without any changes

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#831]
This is a follow-up to #824, specifically to the comment at https://github.com/mozilla/addons-code-manager/pull/824#discussion_r292206253. It seems that files without any changes breaks linter message navigation in the Compare view, so we should skip them. This might be a lot harder than it sounds, as I'm not sure we have access to that information currently when looking for next/previous messages.

**Comment by bobsilverberg** [comment]
I've started looking into this. I believe that we need to enhance [`getRelativeMessage`](https://github.com/mozilla/addons-code-manager/blob/2019.06.13/src/reducers/fileTree.tsx#L305) so that it is able to skip any files that do not include changes, when we are in Compare mode. 

This information is stored in the [`status`](https://github.com/mozilla/addons-code-manager/blob/2019.06.13/src/reducers/versions.tsx#L176) property of `VersionEntry`. This means that we need a full `Version` object while we are processing `getRelativeMessage`. `getRelativeMessage` is only ever called from [`goToRelativeMessage`](https://github.com/mozilla/addons-code-manager/blob/2019.06.13/src/reducers/fileTree.tsx#L407), which itself is only ever called from [`KeyboardShortcuts`](https://github.com/mozilla/addons-code-manager/blob/aa0750074a468d693ce7712ff5c8110d8f24d812/src/components/KeyboardShortcuts/index.tsx#L177). This means that we could pass a `Version` object from `KeyboardShortcuts` into `goToRelativeMessage`. We know currently that `KeyboardShortcuts` will always have access to a `Version` object, but the way that's set up is less than ideal, which is why we have #678.

So, it seems like it's time to tackle #678, because it doesn't make sense to try to make this work without that, IMO.

@kumar303 Can you please let me know if what I've said above makes sense in terms of the implementation, and if you agree that we should address #678 before trying to fix this issue?

**Comment by bobsilverberg** [comment]
This should be fixed via https://github.com/mozilla/addons-server/issues/11639

**Comment by kumar303** [comment]
The point of this issue was to skip files without changes when using keys to navigate linter messages. We no longer want to do that because https://github.com/mozilla/addons-server/issues/11639 will just show the whole file. Thus, I'm closing the issue.

**Comment by bobsilverberg** [comment]
I agree it makes sense to close this, but do we have an issue open to track the fact that this is currently a problem? It seems like it would be good to have an issue that can be verified as fixed when this is actually fixed.

**Comment by kumar303** [comment]
I'm not sure we really need an issue since https://github.com/mozilla/addons-code-manager/issues/846 will make it moot. In any case, this issue (https://github.com/mozilla/addons-code-manager/issues/831) isn't helpful since it describes a solution, not a problem.
