### ISSUE TITLE
Remove lint rules that are redundant with prettier

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#84]
After eslint is configured in https://github.com/mozilla/addons-code-manager/pull/74, we should be able to see a speed-up by introducing https://github.com/prettier/eslint-config-prettier since it will remove rules that are redundant while using prettier.

**Comment by willdurand** [comment]
> since it will remove rules that are redundant while using prettier.

I did not introduce this config in addons-frontend because there were rules that we actually wanted to keep (I don't remember which ones). It was easier to only disable 3 or 4 rules, because everything else applied.

**Comment by willdurand** [comment]
I believe we don't need this based on my previous comment. I could not name the rules that the Prettier preset disables for no reason (I could do it upon request, I guess) but in both addons-frontend and this project, only 4 rules are disabled to avoid conflicts with Prettier. It is a lot less than that: https://github.com/prettier/eslint-config-prettier/blob/master/index.js

**Comment by kumar303** [comment]
> only 4 rules are disabled to avoid conflicts with Prettier

Rules that *conflict* with Prettier is only one aspect of this issue. 

I'm more concerned with getting a *speedup* in eslint by disabling all the rules we don't need. We need eslint to be as fast as possible, especially since it now blocks the test suite (as a reporter).

@willdurand could we re-open this to disable all the rules in https://github.com/prettier/eslint-config-prettier/blob/master/index.js ? That's a big list of rules. Disabling them seems like it would speed things up (but I haven't measured).

**Comment by willdurand** [comment]
> @willdurand could we re-open this to disable all the rules in [prettier/eslint-config-prettier:index.js@`master`](https://github.com/prettier/eslint-config-prettier/blob/master/index.js) ? That's a big list of rules. Disabling them seems like it would speed things up (but I haven't measured).

Of course, yes.

**Comment by willdurand** [comment]
> Disabling them seems like it would speed things up (but I haven't measured).

With this config enabled, `yarn lint` runs 0.4 seconds faster than before on average.
