### ISSUE TITLE
The alt side panel looks all white after resizing the browser 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#841]
STR:
1. Go to code manager on AMO stage and open the versions page for an addon
2. Collaps the panel on the right 
3. Resize the browser 
4. Reopen the panel

Expected result:
The display did not change.

Actual result:
It's blank.

Notes:
I could reproduce this issue every time on AMO stage. - FF67(Win10)
Not reproducible on AMO dev and also not reproducible for the main side panel - FF67(Win10)

An example

![blank on the right](https://user-images.githubusercontent.com/33448286/59419529-c4bf5480-8dd3-11e9-82dc-200462a3f7f3.gif)

**Comment by willdurand** [comment]
I think this has been fixed in #834.

**Comment by ioanarusiczki** [comment]
@willdurand Alright, I'll check both scenarios then!

**Comment by ioanarusiczki** [comment]
@willdurand Right now this issue and https://github.com/mozilla/addons-code-manager/issues/830 are only reproducible on stage.  So perhaps https://github.com/mozilla/addons-code-manager/pull/834 landed yesterday on dev, reason why I filed this as being reproducible on stage only.

**Comment by willdurand** [comment]
> @willdurand Right now this issue and #830 are only reproducible on stage. So perhaps #834 landed yesterday on dev, reason why I filed this as being reproducible on stage only.

That's correct.
