### ISSUE TITLE
Panels should stay collapsed after refreshing page or tab reopened

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#842]
STR:
1. Load a version page for an addon from code manager
2. Collaps the main and alt side panels
3. Refresh the page 

Expected result:
Panels should stay collapsed.

Actual result:
The panels are displayed as being open.

Notes:
Issue is reproducible on dev and stage servers - FF67(Win10). 
It is also reproducible when the browser's tab is closed and reopened.

Both scenarios 

![both scenarios](https://user-images.githubusercontent.com/33448286/59420484-a35f6800-8dd5-11e9-8dc8-d69c069e140b.gif)

**Comment by willdurand** [comment]
@ioanarusiczki Is this feature available in the old tool? If not, then it's a wontfix. I did not expect to retain the collapsed panels after a page refresh.

**Comment by ioanarusiczki** [comment]
@willdurand If by the old tool you mean this https://reviewers.addons-dev.allizom.org/en-US/firefox/files/browse/408955/ I don't see side panels so I can't compare.

**Comment by willdurand** [comment]
> @willdurand If by the old tool you mean this [reviewers.addons-dev.allizom.org/en-US/firefox/files/browse/408955](https://reviewers.addons-dev.allizom.org/en-US/firefox/files/browse/408955/) I don't see side panels so I can't compare.

Yep, then I guess it's a feature request.

**Comment by ioanarusiczki** [comment]
@wagnerand Would such a feature be useful for reviewers ?

**Comment by wagnerand** [comment]
I would consider that a nice-to-have feature.
