### ISSUE TITLE
Unrecognized mimeType passed to convertImageData:  image/tiff

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#843]
https://sentry.prod.mozaws.net/operations/addons-code-manager-dev/issues/5945010/

```
Unrecognized mimeType passed to convertImageData:  image/tiff
```

I am not sure what we can do about this `tiff` format because it does not seem supported by most browsers: https://en.wikipedia.org/wiki/Comparison_of_web_browsers#Image_format_support. We need to check whether FF is able to display `tiff` images though (Wikipedia says no but we should be 100% sure).

**Comment by bobsilverberg** [comment]
A couple of quick tests (trying to open a tiff file in the browser, and using one as the `src` for an `img` element) both seem to indicate that Firefox does not support displaying the format.

**Comment by wagnerand** [comment]
Could be mitigated by #858.

**Comment by bobsilverberg** [comment]
This is no longer relevant after the landing of https://github.com/mozilla/addons-code-manager/commit/c3f8ad7c42499ab9a024e7a58e35f9aa1de92637.
