### ISSUE TITLE
Show the full file in compare mode when there are no differences

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#846]
### Describe the problem and steps to reproduce it:

- Sign in
- Go to a compare page and view a file that has no differences, such as https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1541685...1688187/?path=Grammarly.html

### What happened?

The page just says *No differences*

### What did you expect to happen?

It should show the complete file contents, like the current file viewer: https://reviewers.addons-dev.allizom.org/en-US/firefox/files/browse/408848/file/Grammarly.html#top

### Anything else we should know?

The API will be patched for this in https://github.com/mozilla/addons-server/issues/11639 but the frontend might still need tweaks.

**Comment by kumar303** [comment]
This was fixed by https://github.com/mozilla/addons-server/issues/11639

**Comment by ioanarusiczki** [comment]
@kumar303 Perhaps I should wait for this fixed first https://github.com/mozilla/addons-server/issues/11712

**Comment by kumar303** [comment]
@ioanarusiczki Thanks for catching that bug. I'm not sure if you need to wait because it's working for non-binary files (html files, for example): https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1541685...1688187/?path=Grammarly.html

<img width="1462" alt="Screenshot 2019-06-26 09 27 10" src="https://user-images.githubusercontent.com/55398/60188264-9d658000-97f4-11e9-9b47-e063c822e91a.png">

**Comment by ioanarusiczki** [comment]
@kumar303 That is correct. For all the files I've checked for https://github.com/mozilla/addons-server/issues/11639#issuecomment-505803174 I noticed them as being displayed in code-manager too. 

Another example 
https://code.addons.allizom.org/en-US/compare/1002795/versions/2474830...2474841/?path=background.js

Verified on -dev and -stage - FF67(Win10).
