### ISSUE TITLE
Adding a logging abstraction

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#85]
We closed https://github.com/mozilla/addons-code-manager/issues/13 because we're not doing SSR but we still need to add something that can be called like `log.info()` so that lint rules such as `amo/only-log-strings` catch the right mistakes. Also, I think we'll want to disable debug logging in production.

**Comment by willdurand** [comment]
The `amo/only-log-strings` rule can be configured with the `console` object IIRC.

**Comment by kumar303** [comment]
If we can find a way to toggle debug on/off with just `console` then I'd be fine with that. However, I do like having a `no-console` lint rule because sometimes I just want to put some console statements in for debugging and I don't ever intend to commit them.

**Comment by willdurand** [comment]
> However, I do like having a `no-console` lint rule because sometimes I just want to put some console statements in for debugging and I don't ever intend to commit them.

:+1:
