### ISSUE TITLE
Page is no longer loaded correctly with a larger image

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#856]
STR: 
1. I uploaded an addon containing a large .jpg or .bmp file such as these examples:
https://code.addons-dev.allizom.org/en-US/browse/616906/versions/1688308/?path=Img%2Fhs-2015-02-a-hires_jpg.jpg -> a 20MB .jpg file
https://code.addons-dev.allizom.org/en-US/browse/616909/versions/1688312/?path=Img%2F3.24MB.bmp -> 2 .bmp files each of 16 MB
https://code.addons-dev.allizom.org/en-US/browse/616911/versions/1688314/?path=Img%2Fhs-2015-02-a-hires_jpg.bmp ) -> 13 MB .bmp and a 6 MB .jpg

2. I navigated away from the .jpg file (clicked on the manifest) then returned to the image or collapsed the side panels and then reopen it.  (The main idea is to navigate through the files from the image to other files and back)

Expected result:
The image or the other files clicked are displayed.

Actual result:
The screen remains white. Other times a Json.parse message is displayed on top of the page (even if I reload the page).  

Notes:
I could reproduce this issue with a single .jpg file of 10MB (but the issue becomes intermittent, it's way harder to reproduce it). 
I could reproduce the above issue on FF67(Win10) for all the 3 samples above - on an older and on a new profile on dev and stage servers. 
I could not reproduce the issue with Chrome. 

![json parse](https://user-images.githubusercontent.com/33448286/59681331-5c5de200-91dc-11e9-9998-30ddf9a3c879.gif)

back and forth through files 

![back and forth through files](https://user-images.githubusercontent.com/33448286/59681888-a85d5680-91dd-11e9-8e32-1086fc63979a.png)

**Comment by bobsilverberg** [comment]
This looks to be an issue with the API response, because of the `JSON.parse` error, which makes this a server issue. We discussed this in Whistler and it was suggested that the API should not be encoding and sending file content that is this large. If we can use the download URL for the image src, rather than the file content, then that would allow the API to choose not to encode files over a certain size.

I will file issues regarding these items.

**Comment by EnTeQuAk** [comment]
I'm going to close this issue - as we switched to using the download-url many weeks ago. If this, for some reason, is still an issue please do let me know.

**Comment by ioanarusiczki** [comment]
@EnTeQuAk I verfied on dev with FF69(Win10) and the issue is no longer reproducible. 

![fixed the big images](https://user-images.githubusercontent.com/33448286/65048023-1c89d080-d96c-11e9-96a4-98385768d900.gif)
