### ISSUE TITLE
Use download_url to display images rather than the file content

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#858]
This is a spin-off from #856.

In order to allow the API to not encode and send the content of large image files, we should use the `download_url` of the file to display the image in the browser. This may require an update to our CSP rules.

For QA:

Please verify that all image types that should be viewable in Firefox are still working and displaying images.

**Comment by AlexandraMoga** [comment]
@bobsilverberg I've looked on -dev and stage and there is no actual image rendered for any of the supported img types:

 - example of extensions with images:
https://code.addons-dev.allizom.org/en-US/browse/616837/versions/1688164/
https://code.addons.allizom.org/en-US/browse/1002855/versions/2475140/?path=icon-512.png

**Comment by willdurand** [comment]
> @bobsilverberg I've looked on -dev and stage and there is no actual image rendered for any of the supported img types:
> 
>     * example of extensions with images:
>       [code.addons-dev.allizom.org/en-US/browse/616837/versions/1688164](https://code.addons-dev.allizom.org/en-US/browse/616837/versions/1688164/)
>       [code.addons.allizom.org/en-US/browse/1002855/versions/2475140/?path=icon-512.png](https://code.addons.allizom.org/en-US/browse/1002855/versions/2475140/?path=icon-512.png)
> 
> 
> This is what I'm seeing instead:
> 
> ![image](https://user-images.githubusercontent.com/31961530/61362919-bb6e4f80-a88b-11e9-91d7-f50897df2782.png)

Looks like an issue with the URL that is used. It seems we don't use the -dev server but prod? I opened https://github.com/mozilla-services/cloudops-deployment/pull/3305 to fix the puppet config.

**Comment by bobsilverberg** [comment]
> 
> Looks like an issue with the URL that is used. It seems we don't use the -dev server but prod? I opened [mozilla-services/cloudops-deployment#3305](https://github.com/mozilla-services/cloudops-deployment/pull/3305) to fix the puppet config.

Thanks @willdurand. I didn't realize we needed to do that. Is there a way to mark that as a P1? We really need that done ASAP.

**Comment by willdurand** [comment]
> Thanks @willdurand. I didn't realize we needed to do that. Is there a way to mark that as a P1? We really need that done ASAP.

Let's track this problem in: https://github.com/mozilla/addons-code-manager/issues/954

**Comment by willdurand** [comment]
@AlexandraMoga so I think this issue has been fixed.

**Comment by willdurand** [comment]
Specifically, we filed https://github.com/mozilla/addons-code-manager/issues/954 to track the issues you mentioned in your last comment, so maybe you can verify both now?

**Comment by AlexandraMoga** [comment]
Images are rendered in the browse view for both -dev and stage.

![image](https://user-images.githubusercontent.com/31961530/61446565-ffc72180-a957-11e9-8b77-07c39e5716dd.png)


I'm marking the issue as verified fixed.
