### ISSUE TITLE
`yarn dev` presents confusing output when fixing TypeScript errors

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#86]
After https://github.com/mozilla/addons-code-manager/pull/56 landed, `yarn dev` will run both the server and `create-react-app` (CRA) process within the same stdout stream. This means CRA will no longer clear the stdout buffer when files change and that makes it confusing to fix a TypeScript error -- you still see the old error until it scrolls off the screen.

I'd like to bring back the default CRA experience where the stdout buffer gets cleared on file changes.

**Comment by willdurand** [comment]
You are free to run the two commands in two separate consoles, we can document that.

I prefer the "one command to run everything" approach.

**Comment by willdurand** [comment]
Sorry I did not want to close this issue.
