### ISSUE TITLE
Store linter messages that apply to the entire add-on

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#879]
**For QA**: please check for any regressions in the features relating to linter messages

To support https://github.com/mozilla/addons-code-manager/issues/805 we need to first store linter messages that apply to the entire add-on, i.e. messages that apply to all files.

**Comment by ioanarusiczki** [comment]
@kumar303 
Verified on -dev. FF67(Win10)
https://github.com/mozilla/addons-code-manager/issues/887 is still reproducible.
I'll update https://github.com/mozilla/addons-code-manager/issues/402 with the examples I worked with.
