### ISSUE TITLE
CSS for the Button's transform transition is fractured

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#882]
**For QA**: please check for regressions in the side panel buttons

A shared [`Button` component](https://github.com/mozilla/addons-code-manager/blob/dc18550b066dbb741cef5712b9a46b9611ecb1cf/src/components/Button/index.tsx) was created for https://github.com/mozilla/addons-code-manager/issues/737

The original component, the [`AccordionMenu`](https://github.com/mozilla/addons-code-manager/blob/dc18550b066dbb741cef5712b9a46b9611ecb1cf/src/components/AccordionMenu/index.tsx), had a transform transition to create a physical push effect. When you clicked it, the button moved up 4px.

This feature still works but the logic for it is now spread in two places. The transition is defined here:

https://github.com/mozilla/addons-code-manager/blob/dc18550b066dbb741cef5712b9a46b9611ecb1cf/src/components/Button/styles.module.scss#L8

...and the transform is defined here:

https://github.com/mozilla/addons-code-manager/blob/dc18550b066dbb741cef5712b9a46b9611ecb1cf/src/components/AccordionMenu/styles.module.scss#L19

We need to do one of two things:

1. Move all transition / transform logic into `Button`. This would give all buttons the physical push effect. Personally I like the push effect so I think this is a good solution.

or

2. Remove the transition logic from `Button` and put it back into `AccordionMenu` without breaking the feature.

Without this change, things will still work but there is a greater chance that someone will accidentally break this feature in the future. I.E. It's fragile.

**Comment by kumar303** [comment]
@mirefly thanks for adding the new `Button` component 🙏  Would you be able to look at this follow-up? It's nothing urgent.

**Comment by mirefly** [comment]
@kumar303 Sure, I will have a look at it.

**Comment by ioanarusiczki** [comment]
@kumar303 Buttons are functional and I  don't see any visual regressions. 
Verified on -dev - FF67(win10).
