### ISSUE TITLE
Keyboard navigation won't show correctly the linter warnings from the next file

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#887]
Followup for https://github.com/mozilla/addons-code-manager/issues/825

1. Go to https://code.addons-dev.allizom.org/en-US/compare/390151/versions/1688198...1688302/?messageUid=ab807c4e19fe4db1bd5c99497aee7fc0&path=popup%2Fjs%2Fpopup.js and press `z`
2. Observe the next page

Expected result:
The line with the linter message is at the top of the page.

Actual result:
The top of the page is displayed. 

Notes:
Reproducible on -dev with FF67 -Win10. 

![line 54 not visible](https://user-images.githubusercontent.com/33448286/60245123-88f0b880-98c4-11e9-982d-721af52e9036.gif)

**Comment by bobsilverberg** [comment]
Looking at the markup for the resulting page, it seems odd. The `id` for the `td` for the line on which the message resides is `D54`, but I thought for a file with no changes the `id` would be `N54`. Hmmm. I'll investigate further.

**Comment by mirefly** [comment]
It looks that scrolling to linter message is not working when navigating into a file (using 'a' or 'z') which has been loaded before.
https://code.addons-dev.allizom.org/en-US/browse/502724/versions/1541510/?messageUid=3267292346394c72b7b2cefad3eea174&path=lib%2Fbrowser-polyfill.js#I0
![a](https://user-images.githubusercontent.com/4984681/60368326-d6952000-99ad-11e9-81bb-797ab4f9fcba.gif)

**Comment by kumar303** [comment]
What do you mean by scrolling to a linter message? Could you provide precise steps to reproduce the scrolling bug you are seeing? It sounds like it might be https://github.com/mozilla/addons-code-manager/issues/887

**Comment by mirefly** [comment]
@kumar303 
### Steps to reproduce:
1. Go to https://code.addons-dev.allizom.org/en-US/browse/502724/versions/1541510/?messageUid=3267292346394c72b7b2cefad3eea174&path=lib%2Fbrowser-polyfill.js#I0 (refresh if already opened)
2. Press the key  'a', then 'z'
3. Scroll to the bottom of the page
4. Press the key 'a' . The linter message is not at the top (expected to be).
### Anything else we should know?
If skipping 2nd step, this problem cannot be reproduced.

**Comment by kumar303** [comment]
@mirefly oh, I see now. Thanks. @bobsilverberg just discovered this same bug and has filed https://github.com/mozilla/addons-server/issues/11739 for an API change which should fix it.

**Comment by bobsilverberg** [comment]
> @mirefly oh, I see now. Thanks. @bobsilverberg just discovered this same bug and has filed [mozilla/addons-server#11739](https://github.com/mozilla/addons-server/issues/11739) for an API change which should fix it.

This issue that @mirefly reported at has not been resolved. I believe that our code does not currently support scrolling line 0 into view (although I could be wrong about that). In any case, even with the fix from https://github.com/mozilla/addons-server/issues/11739, the problem is reproducible where pressing `a` on a page which has been manually scrolled to the bottom does not scroll the line with the message into view.

This is actually a separate issue from the one reported in this issue. @mirefly Could you open a separate issue with your STR so we can investigate and respond to it appropriately?

**Comment by mirefly** [comment]
@bobsilverberg I filed #905

**Comment by ioanarusiczki** [comment]
@bobsilverberg Looks like it's working now. - dev FF67(Win10)

![going to the linter warning](https://user-images.githubusercontent.com/33448286/60576692-8d1a4b80-9d86-11e9-9a76-bb63cd463e57.gif)
