### ISSUE TITLE
Create a shared getCodeLineAnchorGetter function

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-code-manager#889]
This supports #887 

https://github.com/mozilla/addons-code-manager/commit/9010bcb01320e58a5304905067cb6ef90e6c72b0 introduced a special [`getCodeLineAnchor`](https://github.com/mozilla/addons-code-manager/blob/9010bcb01320e58a5304905067cb6ef90e6c72b0/src/pages/Compare/utils.tsx#L77) function which can be used for the `Compare` page when a `diff` is present. There already existed a [`getCodeLineAnchor`](https://github.com/mozilla/addons-code-manager/blob/9010bcb01320e58a5304905067cb6ef90e6c72b0/src/components/CodeView/utils.tsx#L44) function for use on the `Browse` page.

We need this same dual functionality in the [`goToRelativeMessage`](https://github.com/mozilla/addons-code-manager/blob/9010bcb01320e58a5304905067cb6ef90e6c72b0/src/reducers/fileTree.tsx#L391) function in order to generate a correct `hash` to add to the `location`. I initially just copied the [logic](https://github.com/mozilla/addons-code-manager/blob/7f5dced331ff5cd21cfd9073db1dc3c1b418519f/src/pages/Compare/index.tsx#L174-L178) from the `Compare` page into the `KeyboardShortcuts` component, but it got complicated when trying to write tests, so I figured it would be better to extract the logic out of both `Compare` and `CodeView` and create a shared function, which could potentially be mocked in tests.

I have started working on this. @kumar303 what do you think?

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
- I filed https://github.com/mozilla/addons-code-manager/issues/914 but I don't think it's a regression caused by this issue. 
- It's been noticed by @kumar that diffs are loading very slow , in my case it won't take 20 seconds, it just won't load - but it's been filed already.
