### ISSUE TITLE
yarn start-local-prod is broken (blank page, CSP errors)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#899]
### Describe the problem and steps to reproduce it:

- Run `yarn start-local-prod` [as documented](https://github.com/mozilla/addons-code-manager#yarn-start-local-prod)
- Clear your browser cache
- Load http://localhost:3000

### What happened?

The page at `localhost:3000` is blank and there are numerous console errors:

<img width="1043" alt="Screenshot 2019-07-02 09 42 04" src="https://user-images.githubusercontent.com/55398/60522037-e6627c00-9cad-11e9-8e46-300fa77869a4.png">

### What did you expect to happen?

The page should load

### Anything else we should know?

Maybe the CDN URL just needs fixing or maybe there are CSP problems, too.

**Comment by kumar303** [comment]
`yarn start-local-dev` and `yarn start-local-stage` are broken in the same way

**Comment by willdurand** [comment]
That's because `yarn start` does a `rm -f .env.local` I believe.

**Comment by willdurand** [comment]
> That's because `yarn start` does a `rm -f .env.local` I believe. I thought I fixed that because I hit this problem many times after the npm scripts have been updated.

ahm, there is an issue with the `PUBLIC_URL` too, which means that's a CSP problem too. 😭

**Comment by AlexandraMoga** [comment]
@willdurand this looks  like a "qa:not needed" issue :)

**Comment by willdurand** [comment]
> @willdurand this looks like a "qa:not needed" issue :)

indeed, thanks!
