### ISSUE TITLE
Don't just show a blank page for errors (500s)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#900]
### Describe the problem and steps to reproduce it:

* Turn off development mode with the config somehow (see https://github.com/mozilla/addons-code-manager/issues/899)
* Load a page that throws an error. For example, the front page of the local development site (http://localhost:3000/) has a button to throw an error.

### What happened?

You see a blank page as shown in the screencast for https://github.com/mozilla/addons-code-manager/issues/896

### What did you expect to happen?

You should see a 500 page indicating that the site experienced an unexpected error.

### Anything else we should know?

We probably just need to add an [error boundary](https://reactjs.org/docs/error-boundaries.html).

**Comment by bobsilverberg** [comment]
FYI, I wasn't able to reproduce this problem using the STR above, nor that in https://github.com/mozilla/addons-code-manager/issues/899. When accessing the site via `yarn start-local-prod` I do not see the home page with the links to generate an error, but instead am told to log in. But logging in doesn't work with `yarn start-local-prod`. I tried hacking some other settings to "Turn off development mode", but was unsuccessful. In the end I simply hacked the home page to throw an error when logged out, and was able to test a patch that way.

If there's a better STR it would be good to document it, and that would also help QA test this when I submit a patch.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I changed the milestone because there's no push this week.

**Comment by AlexandraMoga** [comment]
@bobsilverberg can this be validated with the STR from #896 ?

If I'm accessing one of the pages mentioned in the issue I can see an error now rather than just a blank page:

![image](https://user-images.githubusercontent.com/31961530/69819548-db355d00-1207-11ea-83af-94f15a39fff6.png)
