### ISSUE TITLE
Global linter message not scrolled to view when using keyboard navigation between messages

### ISSUE THREAD

**Issue by mirefly** [mozilla/addons-code-manager#905]
### Steps to reproduce:
1. Go to https://code.addons-dev.allizom.org/en-US/browse/502724/versions/1541510/?messageUid=3267292346394c72b7b2cefad3eea174&path=lib%2Fbrowser-polyfill.js#I0 (refresh if already opened)
2. Press the key  'a', then 'z'
3. Scroll to the bottom of the page
4. Press the key 'a' . The linter message is not at the top (expected to be).
### Anything else we should know?
If skipping 2nd step, this problem cannot be reproduced.

**Comment by wagnerand** [comment]
@kumar303 is this a duplicate of #878?

**Comment by kumar303** [comment]
> @kumar303 is this a duplicate of #878?

It's not. Confusingly, *global* messages apply to an entire file (#905) whereas *general* messages apply to the entire add-on (#878). Names are hard. We should rename *global* someday but there is a lot of code already invested in it.

**Comment by ioanarusiczki** [comment]
@mirefly I tested the scenario with https://code.addons-dev.allizom.org/en-US/browse/502724/versions/1541510/?messageUid=3267292346394c72b7b2cefad3eea174&path=lib%2Fbrowser-polyfill.js#I0 
and I could not reproduce the issue: after scrolling down when I press `a` , the message is shown at the top of the page. 

![the linter message is shown ](https://user-images.githubusercontent.com/33448286/68122706-9f162180-ff13-11e9-8310-ea637a7f15ce.gif)

Verified on dev with FF70(Win10).
