### ISSUE TITLE
HTML title not updated when navigating to the homepage

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#912]
### Describe the problem and steps to reproduce it:

1. Go to https://code.addons-dev.allizom.org/en-US/browse/616702/versions/1688024/
2. Click the top-left "addons-code-manager" link (to go to the homepage)

### What happened?

The HTML title (or tab title) has not been updated. The add-on's name is displayed instead.

### What did you expect to happen?

The homepage title should be used.

**Comment by ioanarusiczki** [comment]
@willdurand 
Right now the addons-code-manager link was replaced by the add-on name https://github.com/mozilla/addons-code-manager/issues/756 making this issue no longer valid.

**Comment by willdurand** [comment]
@ioanarusiczki  Yes and no. I think, before, there was no html title for the homepage at all and it is still possible to access the homepage.

**Comment by ioanarusiczki** [comment]
@wagnerand This patch has has no effect on the UI if the old addons-code-manager link is no longer available on the Browse and Compare pages. 
The Name of the add-on replaced the link.  https://github.com/mozilla/addons-code-manager/issues/756

Do you still want that to be available somewhere on these pages?

**Comment by wagnerand** [comment]
@willdurand is there issue here that the homepage has. no html `title` element? How can you reach the homepage?

**Comment by willdurand** [comment]
There used to be an issue but now it's not possible to navigate to the homepage using client-side navigation anymore.

**Comment by ioanarusiczki** [comment]
@wagnerand @willdurand I filed it here https://github.com/mozilla/addons-code-manager/issues/984
