### ISSUE TITLE
Building a comparison map is slow for large files

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#924]
**For QA**: please check for regressions in other compare pages. The fix for this may not make a huge impact -- i.e. the file will still load "slowly."

### Describe the problem and steps to reproduce it:

- Sign in
- Load https://code.addons-dev.allizom.org/en-US/compare/495710/versions/1541610...1688333/
- Click on `package-lock.json` to view it

(Also see https://github.com/mozilla/addons-code-manager/issues/779)

### What happened?

It loads very slowly

### What did you expect to happen?

It should load quickly

### Anything else we should know?

Most of the problem in loading this file (which has ~8,000 lines) is the tokenization for highlighting but there is some low hanging fruit in creating a comparison map. Speeding up the comparison map won't make a huge difference but it's easy to do!

**Comment by AlexandraMoga** [comment]
I did not find regressions in the compare view. 

As it was anticipated, this patch did not fix the slow loading issue,or the browser freeze issue mentioned in #779
