### ISSUE TITLE
Building DiffView widgets is slow for large files

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#926]
**For QA**: please check for regressions in other compare pages. The fix for this may not make a huge impact -- i.e. the file will still load "slowly."

### Describe the problem and steps to reproduce it:

- Sign in
- Load https://code.addons-dev.allizom.org/en-US/compare/495710/versions/1541610...1688333/
- Click on `package-lock.json` to view it

(Also see https://github.com/mozilla/addons-code-manager/issues/779)

### What happened?

It loads very slowly

### What did you expect to happen?

It should load quickly

### Anything else we should know?

Part of rendering a diff on a compare page involves building a map of "widgets," like inserting an inline linter message, for example. This takes a significant amount of time on large files (those with many lines).

**Comment by AlexandraMoga** [comment]
No regressions found in the compare view.
The slowness is still persisting though, but this was anticipated.
