### ISSUE TITLE
Add a tokenize worker to speed up code highlighting

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#928]
Tokenizing a file to highlight the code makes the file render slowly. See https://github.com/mozilla/addons-code-manager/issues/402 for STR -- a minified diff like this is the most dramatic example.

I confirmed in benchmarks that the tokenizer is the main offender so it's worth our time to try switching to a [worker model](https://github.com/otakustay/react-diff-view/blob/master/site/components/DiffView/Tokenize.worker.js).

Specifically, while profiling a production build from d07fbc30e7571dd8d72b8db449de926fac59c2fc and loading the minified diff from https://github.com/mozilla/addons-code-manager/issues/402, [`tokenize()`](https://github.com/otakustay/react-diff-view/blob/58d0b1497549f9b28cfa3e3d7978a2c86f822f67/src/tokenize/index.js#L6) accounts for 95% of the time, i.e. 7.32 seconds.

**Comment by kumar303** [comment]
We need a Web Worker for this feature, which isn't coming until create-react-app 3.1 ([roadmap](https://github.com/facebook/create-react-app/projects/8#card-22946440)). PR: https://github.com/facebook/create-react-app/pull/5886

Before Web Workers are officially supported, we would need something like [`react-app-rewired`](https://github.com/timarney/react-app-rewired) or [`craco`](https://github.com/sharegate/craco) to set [`output.globalObject = 'this'`](https://github.com/facebook/create-react-app/pull/5886/files#diff-dc0c4e7c623b73660da1809fc60cf6baR181) in the webpack config, at least until https://github.com/webpack/webpack-dev-server/issues/1595 is fixed.

@willdurand @bobsilverberg maybe we should try and wait until CRA 3.1 is released? What do you think?

**Comment by bobsilverberg** [comment]
Sounds reasonable to me.

**Comment by willdurand** [comment]
I think waiting for CRA 3.1 would be wise, even though the current PR does not support TypeScript. I guess we'll workaround that if needed, though.

I like this suggestion in the meantime: https://github.com/mozilla/addons-code-manager/issues/402#issuecomment-473349325. I would even say that minified code is barely readable anyway, with or without syntax HL (I don't read minified code a lot but usually I find it more confusing when syntax HL is enabled).

**Comment by kumar303** [comment]
Good call on disabling highlighting on large files. I'll do that in https://github.com/mozilla/addons-code-manager/issues/942

**Comment by kumar303** [comment]
This is supported in `create-react-app` out of the box now. This article explains how to do it with a `workerize!` import: https://kentcdodds.com/blog/speed-up-your-app-with-web-workers

**Comment by bobsilverberg** [comment]
Removing this from the project as we determined this is not something we want to do at this time. See https://github.com/mozilla/addons-code-manager/pull/1411#issuecomment-582088619
