### ISSUE TITLE
Warning message shown by the Console for some binary files 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#933]
This is a followup after discussions with @bobsilverberg 

STR:
1. Load the following files 
https://code.addons-dev.allizom.org/en-US/compare/390151/versions/1688198...1688302/?path=popup%2Ffonts%2Fglyphicons-halflings-regular.svg
or
https://code.addons-dev.allizom.org/en-US/compare/390151/versions/1688198...1688302/?path=popup%2Ffonts%2Fglyphicons-halflings-regular.eot
2. Check the Console

Results:
Console returns several warnings such as
`No changes were mapped for line 1` and so on 

This is reproducible on -dev with FF67 (Win10). 

![Console](https://user-images.githubusercontent.com/33448286/60893129-01625c80-a269-11e9-9a87-457107f1577b.png)

**Comment by kumar303** [comment]
I guess we could change this to a debug message.

**Comment by kumar303** [comment]
To be clear, I think the warning is not indicative of a problem. React just renders a lot and the state it's in is probably valid.
