### ISSUE TITLE
Orange line is not available in the overview for warnings at the top of the pages

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#941]
STR:
1. Go to the following examples 
in Browse Pages
https://code.addons-dev.allizom.org/en-US/browse/495710/versions/1541609/?path=META-INF%2Fmanifest.mf
https://code.addons-dev.allizom.org/en-US/browse/8542/versions/1655535/#I5
or in Compare pages 
https://code.addons.allizom.org/en-US/compare/1002795/versions/2474840...2474841/?messageUid=7d5b3eb6f0264ea3bddee675e62e5337&path=META-INF%2Fmanifest.mf

Expected result:
The warnings can be selected using the overview (there's an orange line). 

Actual result:
The orange line is not available for the warnings at the top of the page.

Notes:
Reproducible on -dev and -stage for Browser and Compare view.

![no orange overview](https://user-images.githubusercontent.com/33448286/61037904-a8173c00-a3d4-11e9-8e41-52273fb057f9.gif)

**Comment by kumar303** [comment]
Thanks for filing. This is definitely something I'd like to fix. We had it filed already as https://github.com/mozilla/addons-code-manager/issues/677 (I just updated the title as it was slightly misleading)
