### ISSUE TITLE
Speed up large diffs by disabling syntax highlighting

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#942]
### Describe the problem and steps to reproduce it:

- Sign in
- Load a diff that has very long lines (such as a minified library): https://code.addons-dev.allizom.org/en-US/compare/502955/versions/1541798...1541798/?path=popup%2Fpopup.js
- Or load a diff that has many lines: https://code.addons-dev.allizom.org/en-US/compare/495710/versions/1541610...1688333/?path=package-lock.json

### What happened?

The diff loads too slowly and sometimes freezes the browser

### What did you expect to happen?

The diff should load quickly without syntax highlighting

### Anything else we should know?

Turning off syntax highlighting will be a temporary measure until we can speed up the tokenization process (the slow part of highlighting): https://github.com/mozilla/addons-code-manager/issues/928

**Comment by kumar303** [comment]
For QA: please let me know if you still find any slow loading diffs after this.

**Comment by AlexandraMoga** [comment]
@kumar303 I have a few examples of slow loading diffs on -dev:

1. https://code.addons-dev.allizom.org/en-US/compare/385621/versions/1655456...1688374/?path=public%2Fjs%2Fbackground.js
2. https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1541685...1688187/?path=src%2Fjs%2FGrammarly-bg.js
3. https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1541685...1688187/?path=src%2Fjs%2Feditor-popup.js

It is worth noting that all these diffs have ~20k lines

I have another example of an add-on with many contents for which navigating throughout all the files is quite slow: https://code.addons-dev.allizom.org/en-US/compare/1865/versions/1529553...1688304/

On the plus side, the browser no longer freezes when I'm trying to open either of these files.

**Comment by kumar303** [comment]
Thanks. I added https://github.com/mozilla/addons-code-manager/issues/946 to track the long file diff problem.

**Comment by kumar303** [comment]
> I have another example of an add-on with many contents for which navigating throughout all the files is quite slow: https://code.addons-dev.allizom.org/en-US/compare/1865/versions/1529553...1688304/

Oof, good find. This is an API issue so I filed https://github.com/mozilla/addons-server/issues/11838

**Comment by AlexandraMoga** [comment]
marking this as verified fixed then, since the issues discovered are all filed as followups.
