### ISSUE TITLE
Diffs of very long files are slow to load

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#946]
### Describe the problem and steps to reproduce it:

Try to view a diff of a file with many lines (~20K lines). Examples:

* https://code.addons-dev.allizom.org/en-US/compare/385621/versions/1655456...1688374/?path=public%2Fjs%2Fbackground.js
* https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1541685...1688187/?path=src%2Fjs%2FGrammarly-bg.js
* https://code.addons-dev.allizom.org/en-US/compare/502868/versions/1541685...1688187/?path=src%2Fjs%2Feditor-popup.js

### What happened?

It takes 5-7 seconds to load the diff

### What did you expect to happen?

The diff should load faster

### Anything else we should know?

Disabling syntax highlighting (https://github.com/mozilla/addons-code-manager/issues/942) improved performance here but it's still slow because so many rows of text need to be rendered.

**Comment by AlexandraMoga** [comment]
Verified on -dev with Fx68, Win10x64

The compare pages for long/slow files are loading faster now - performance is not that great but I understand this is also coming from the API.

Reviewers have the option to view the original file by clicking on "Show the original diff" in a notification displayed at the top of the page. They can also switch back to trimmed view through the same option.

![image](https://user-images.githubusercontent.com/31961530/61802617-758c2b00-ae39-11e9-9f10-51a303ac5823.png)
![image](https://user-images.githubusercontent.com/31961530/61802625-791fb200-ae39-11e9-9ac2-101c55ed63b3.png)

There is however an issue with keyboard navigation between diffs, for which I've files #971

**Comment by kumar303** [comment]
> The compare pages for long/slow files are loading faster now - performance is not that great but I understand this is also coming from the API.

Yep. This is the API issue for improving the response times: https://github.com/mozilla/addons-server/issues/11904
