### ISSUE TITLE
The browse page for very long files is loading slowly 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#947]
Extending issue #946 to the browse page as well

Try to open the browse page for the following files (~20k lines):

- https://code.addons-dev.allizom.org/en-US/browse/502868/versions/1688187/?path=src%2Fjs%2Feditor-popup.js
- https://code.addons-dev.allizom.org/en-US/browse/502868/versions/1688187/?path=src%2Fjs%2FGrammarly-bg.js
- https://code.addons-dev.allizom.org/en-US/browse/385621/versions/1655456?path=public%2Fjs%2Fbackground.js

**Actual result:**
It takes about 5 - 7 seconds for the code to load

**Expected result:**
The code should load faster

**Comment by kumar303** [comment]
Thanks for filing. Even a file with 3,000 lines is slow: https://code.addons-dev.allizom.org/en-US/browse/385621/versions/1655456/?path=public%2Fjs%2Foptions.js

**Comment by kumar303** [comment]
I did some profiling. The biggest win here would be trimming the content, like in https://github.com/mozilla/addons-code-manager/pull/951 . I played with disabling syntax highlighting but it doesn't speed it up by much.

**Comment by AlexandraMoga** [comment]
Verified on -dev with Fx68, Win10x64

First of all, large/slow files are loaded faster now - still they aren't impressively fast (the API is also at fault here) but an improvement is indeed noticeable:

![2019-07-24_14-43-19](https://user-images.githubusercontent.com/31961530/61792455-74e99980-ae25-11e9-8483-135c79333c41.gif)
 

The reviewer has the option to view the original file by clicking on a link at the top of the code viewer. Additionally, they can switch back to trimmed code through the same option.

![image](https://user-images.githubusercontent.com/31961530/61792779-2e486f00-ae26-11e9-9178-d4fb0fd0c342.png)
![image](https://user-images.githubusercontent.com/31961530/61792780-30aac900-ae26-11e9-8fd2-2acfab3febd1.png)


@kumar303 I have the following scenario which might have been intended but I'd like to clarify it either way:
When I'm loading a large/slow file and then opt to "View the original file" the `allowSlowPages=true` parameter is set in the URL. Then, if I navigate to a different file path, `allowSlowPages=true` persists in the URL.  Would it be possible to reset this parameter as well, to avoid running into slow loading files again? Reviewers can opt to see the original file if needed.

**Comment by kumar303** [comment]
> Would it be possible to reset this parameter as well, to avoid running into slow loading files again? Reviewers can opt to see the original file if needed.

Yes, I think this is worth filing an issue for. Thanks.

**Comment by AlexandraMoga** [comment]
Filed https://github.com/mozilla/addons-code-manager/issues/977
