### ISSUE TITLE
Add `REACT_APP_REVIEWERS_HOST` in all envs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-code-manager#954]
From: https://github.com/mozilla/addons-code-manager/issues/858#issuecomment-512330447

---

We need to add the `REACT_APP_REVIEWERS_HOST` env var in all environments. This should be done before this week's push (`2019.07.11`). A patch has been proposed in https://github.com/mozilla-services/cloudops-deployment/pull/3305.

**Comment by bqbn** [comment]
https://github.com/mozilla-services/cloudops-deployment/pull/3305 merged and pushed to -dev and -stage.

**Comment by bqbn** [comment]
This got deployed to -prod last week.
