### ISSUE TITLE
Allow the current version to be "unset"

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#955]
**QA**: please check for regressions in TBA

The header needs to use [`currentVersion`](https://github.com/mozilla/addons-code-manager/blob/e64917da1db5bf9714c62b288e0a534103c5d224/src/reducers/versions.tsx#L317) to display the add-on name (https://github.com/mozilla/addons-code-manager/issues/756). Since this is a global component, it's also rendered on the home page where the current version is irrelevant. There is no *unset* current version state. We need to add that. This will enable the header component to render skeleton text as the current version loads.

Some ideas:
- introduce `false` to convey an unset current version
- have the home page dispatch `unsetCurrentVersion()` to enter this state

**Comment by ioanarusiczki** [comment]
@kumar303 I verified this on dev with FF68(Win10) and I did not find regressions. 
- the Browse page: shows the name of the add-on on the top left side of the page. While hovering above the tab the title is: `Browse Name: Version` 

![Browse](https://user-images.githubusercontent.com/33448286/62470426-16b4a300-b7a3-11e9-8d44-8ac96ff2d474.png)

- the Compare page: shows the name of the add-on on the top left side. While hovering above the tab the title is: `Compare Name: oldversionid...newversionid`

![Compare](https://user-images.githubusercontent.com/33448286/62470718-b5d99a80-b7a3-11e9-8356-7a8c3c1e59d2.png)
