### ISSUE TITLE
Convert createStoreWithVersion() to use object parameters

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#965]
In https://github.com/mozilla/addons-code-manager/pull/937/ , [`createStoreWithVersion()`](https://github.com/mozilla/addons-code-manager/blob/cf403fafad6a0ecc3ef783a4b1e036cd6be09b2d/src/test-helpers.tsx#L716) grew an extra option but it was added as a positional argument. Since the first positional argument is also optional, let's convert all arguments to a single object.

For example, after converting it to use object parameters, it can be called like this:

```js
// This passes in all options:
createStoreWithVersion({ version: '...', makeCurrent: true });

// This will create a store with the default version:
createStoreWithVersion({ makeCurrent: true });

// This will use the default for makeCurrent when creating a version.
createStoreWithVersion({ version: '...' });
```

**Comment by Shubhamchinda** [comment]
Hey @kumar303 , Can I take it?

**Comment by kumar303** [comment]
@Shubhamchinda sure, go for it. Thanks! Let me know if you have any questions. It helps to mention my username in any pull requests, just so I don't miss them.
