### ISSUE TITLE
The tooltip displaying line numbers for linter messages in Code Overview is sometimes inaccurate 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#970]
### Describe the problem and steps to reproduce it:
1.  Go to the following browse file page:
https://code.addons-dev.allizom.org/en-US/browse/502868/versions/1688187/?allowSlowPages=true&path=src%2Fjs%2Feditor-popup.js
2. Hover over a linter message in Code Overview
3. Look at the line number displayed by the tooltip
4. Click on the linter message

### What happened?
You will land on a different line number than the one displayed by the tooltip

### What did you expect to happen?
The line number displayed by the tooltip and the actual line number that throws the linter message should coincide

### Anything else we should know?
- also reproduces in the compare page - see https://code.addons-dev.allizom.org/en-US/compare/1865/versions/1529553...1688304/?allowSlowPages=true&path=lib%2Fadblockplus.js
- you might want to see the original file to be able to jump to linter messages until #967 gets fixed

![2019-07-24_15-48-59](https://user-images.githubusercontent.com/31961530/61795577-6a7ece00-ae2c-11e9-8605-9c6cbeea7ed2.gif)

**Comment by kumar303** [comment]
The behavior is correct. The overview has to create "windows" of code which is a range of line numbers. When clicking on a linter message, as you can see from the screencast, it takes you to the right place. This tooltip is a bit confusing, though. It could be fixed but this is low priority.
