### ISSUE TITLE
The `allowSlowPages` parameter should be reset when the user navigates to a different file

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-code-manager#977]
Follow up for #947 

### Describe the problem and steps to reproduce it:
1. Open the browse page for a slow loading file - see https://code.addons-dev.allizom.org/en-US/browse/502868/versions/1688187/?path=src%2Fjs%2Feditor-popup.js
2. Click on "View the original file" in the notification displayed at the top of the page
3. Select another slow loading file from the file tree - see `src/js/Grammarly-bg.js`

### What happened?
The new file will load slowly. This happens because the `allowSlowPages=true` parameter was activated when the  "View the original file" option was selected for the previous file.

### What did you expect to happen?
The `allowSlowPages` parameter should be reset when the user navigates to a different file, to avoid running into slow loading files.

### Anything else we should know?
This issue will also reproduce in the Compare page

![2019-07-29_11-45-49](https://user-images.githubusercontent.com/31961530/62034367-91efe500-b1f6-11e9-9814-d843fb7c842f.gif)

**Comment by wagnerand** [comment]
I am not sure it should reset. There are good reasons for doing either, so maybe a different approach would be more useful.

**Comment by kumar303** [comment]
@wagnerand should we close the issue for now and wait until it becomes a problem? 

I wasn't entirely sure how reviewers would want to deal with large files. They may want to turn on slowness intentionally (to view complete files) and turn it off again when not needed.

**Comment by wagnerand** [comment]
At which point do we know whether we would truncate a file (if `allowSlowPages` isn't passed)? Do we know this before a specific file is being loaded? I am thinking we could add an always-visible checkbox somewhere that allows switching between the two states at any time. The workflow I am thinking of is:

1. Reviewer loads a large file, but it's an important one, so they need to see it completely.
2. Reviewer goes to next large file, and they want to back to the truncated view. They uncheck the checkbox, the code-manager aborts loading the file fully and instead loads the truncated file.

That way, it allows loading large files consistently (which is needed most of the time), and have an option to switch back at any time, without having to wait for the file you are not interested in to be loaded fully.

**Comment by kumar303** [comment]
@wagnerand we're on the same page. What you are requesting already happens but in a different way. It currently works like this:

1. Reviewer loads a large file, but it's an important one, so they need to see it completely. They click *View the original file*.
2. Reviewer goes to next large file. The large file loads completely but the top of it has a warning saying that the file is loading slowly. It has a link that says *View a shortened file*. This will get them back to the fast loading state.

**Comment by kumar303** [comment]
The UI will let you know when you are in "allow slow pages" mode and it gives you a way to exit out of it. Thus, I don't think we need to automatically escape out of slow mode.
