### ISSUE TITLE
Add Reviewer Tools back link on Browse and Compare pages

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-code-manager#984]
STR:
1. Load dev and go to a Browse page and then a Compare page such as 
https://code.addons-dev.allizom.org/en-US/browse/616911/versions/1688344/
https://code.addons-dev.allizom.org/en-US/compare/616909/versions/1688312...1688345/
2. Observe the top of the page (the dark grey area)

Expected result:
There is a link to the reviewer's page such as https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/webext-csp78

Actual result:
The link is not available. 

Notes:
reproducible on -dev and -stage with FF68(Win10).

**Comment by kumar303** [comment]
Why would someone need to navigate to the home page? There is nothing useful there.

If anything, we probably need a link "back" to Reviewer Tools.

**Comment by willdurand** [comment]
> Why would someone need to navigate to the home page? There is nothing useful there.

I like that we link to the github repo to file issues.

**Comment by ioanarusiczki** [comment]
@kumar303  Ok, I updated this issue. 
It was filed for https://github.com/mozilla/addons-code-manager/issues/912 (discussions are there).

This patch won't be reverted but for now it is of no use if we don't link to code-manager homepage or reviewer tools which yes, would be useful instead of code-manager homepage.

**Comment by ioanarusiczki** [comment]
@kumar303 The add-on review page from rev tools is opened in a new tab. 

![new tabs](https://user-images.githubusercontent.com/33448286/69330029-de09de00-0c5a-11ea-9e51-98297ec6ede1.gif)

verified on dev with FF70(Win10).
