### ISSUE TITLE
Render saved draft comments for diffs, inline

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#990]
### Describe the problem and steps to reproduce it:

Consider this imaginary UI flow:

- Sign in as a reviewer
- Open a version compare page
- Click on the line number of a diff, enter a comment, press save
- Refresh the browser page

### What happened?

n/a

### What did you expect to happen?

The saved draft comments should be displayed

### Anything else we should know?

See https://github.com/mozilla/addons-code-manager/issues/713 for doing this same thing in browse mode.

**Comment by bobsilverberg** [comment]
@kumar303 I believe this was fixed via https://github.com/mozilla/addons-code-manager/commit/76fdcaeb0d1ae06c87f996ba28e96ad425f7bb25. Do you agree?

**Comment by kumar303** [comment]
Yes, thanks!

**Comment by ioanarusiczki** [comment]
@kumar303 I posted 25+ comments on a compare page - https://code.addons-dev.allizom.org/en-US/compare/495710/versions/1688333...1688369/
After refreshing the pages the comments are still available. 
Verified on dev with FF70(win10).
