### ISSUE TITLE
Comment form is too wide on files with wide lines

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-code-manager#997]
When commenting on a file in browse mode (https://github.com/mozilla/addons-code-manager/issues/112) the comment form is too wide if the file has at least one very long line. This makes it difficult to type into the comment box.

Example (from a prototype):

<img width="873" alt="Screenshot 2019-08-06 17 00 38" src="https://user-images.githubusercontent.com/55398/62580533-f69ce680-b86b-11e9-9ef6-e2648e5bbfdc.png">

**Comment by ioanarusiczki** [comment]
@kumar303 
For most of the files I've checked on AMO stage it looks good, meaning that the long code lines are no longer extended on a single line, therefore there's no scroll bar at the bottom of the page. 
The comment box looks as [described](https://user-images.githubusercontent.com/55398/68180132-22596680-ff58-11e9-877e-53a02af6e4a7.png)

Examples:
https://code.addons.allizom.org/en-US/browse/9609/versions/2475106/?path=cliqz%2Fcore%2Fcontent-script.bundle.js
https://code.addons.allizom.org/en-US/browse/9609/versions/2475106/?path=cliqz%2Fmyoffrz-helper%2Fcategory-pattern.json
https://code.addons-dev.allizom.org/en-US/browse/502965/versions/1688284/?path=popup.html

But I've also found some files that won't look alright (this add-on loads quite slow, and I received again the yellow warning on the top of the page): 
https://code.addons.allizom.org/en-US/browse/9609/versions/2475106/?path=dist%2Fpanel_react.js

![js files with scroll bar](https://user-images.githubusercontent.com/33448286/68302632-1500c100-00ab-11ea-9be4-8a2a0031684e.gif)


It's a busy week on the testing side but this needs some further investigation - I'll continue to check some other add-ons on Friday.

**Comment by kumar303** [comment]
> ...I've also found some files that won't look alright (this add-on loads quite slow, and I received again the yellow warning on the top of the page):
> https://code.addons.allizom.org/en-US/browse/9609/versions/2475106/?path=dist%2Fpanel_react.js
> 

I'd like to fix this -- can you file a separate bug? Also, is there an example to reproduce this on dev?

> It's a busy week on the testing side but this needs some further investigation - I'll continue to check some other add-ons on Friday.

No rush! Thanks for digging into it.

**Comment by kumar303** [comment]
> > ...I've also found some files that won't look alright (this add-on loads quite slow, and I received again the yellow warning on the top of the page):
> > https://code.addons.allizom.org/en-US/browse/9609/versions/2475106/?path=dist%2Fpanel_react.js
> 
> I'd like to fix this -- can you file a separate bug? Also, is there an example to reproduce this on dev?

Actually, I found a way to reproduce it and I have a fix. I filed it here: https://github.com/mozilla/addons-code-manager/issues/1207

**Comment by ioanarusiczki** [comment]
@kumar303 Thanks! I'll mark this verified on dev with FF70(Win10).
